/**
 * stitaP Tool Store — Analytics Tools
 *
 * DuckDB-style in-house columnar database with SQL, XQL, and MDX query engines.
 * Exports to PowerBI, Excel, Google Sheets, Tableau.
 * Runs entirely in the browser. Zero external dependencies.
 */

import type { ToolManifest } from "../tool-types";

export const ANALYTICS_TOOLS: ToolManifest[] = [
  {
    id: "analytics.csv_import",
    name: "Import CSV",
    description:
      "Parse CSV text into a columnar table with auto-detected types (int, float, bool, string, date). Returns row count and schema.",
    category: "analytics",
    icon: "Table",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["csv", "import", "data"],
    color: "#10b981",
    parameters: [
      { name: "csv", type: "string", description: "Raw CSV text content", required: true },
      { name: "tableName", type: "string", description: "Name for the table (default: csv_import)", required: false },
    ],
    capabilities: [{ name: "csv-import", description: "Parse CSV with auto-detected types", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 12500,
    rating: 4.7,
    ratingCount: 342,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.json_import",
    name: "Import JSON",
    description:
      "Import a JSON array of objects into a columnar table with auto-detected types.",
    category: "analytics",
    icon: "Table",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["json", "import", "data"],
    color: "#10b981",
    parameters: [
      { name: "data", type: "string", description: "JSON string (array of objects)", required: true },
      { name: "tableName", type: "string", description: "Name for the table (default: json_import)", required: false },
    ],
    capabilities: [{ name: "json-import", description: "Parse JSON arrays into columnar tables", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 11200,
    rating: 4.6,
    ratingCount: 298,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.sql",
    name: "SQL Query",
    description:
      "Execute a SQL-like query against registered tables. Supports SELECT, WHERE, GROUP BY, ORDER BY, LIMIT, JOIN, aggregations (COUNT, SUM, AVG, MIN, MAX), CASE expressions, and arithmetic.",
    category: "analytics",
    icon: "Terminal",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["sql", "query", "database"],
    color: "#10b981",
    parameters: [
      { name: "query", type: "string", description: 'SQL query, e.g. "SELECT dept, COUNT(*) as cnt FROM sales GROUP BY dept ORDER BY cnt DESC LIMIT 10"', required: true },
      { name: "tableName", type: "string", description: "Optional: name of a single table to query (shortcuts FROM clause)", required: false },
    ],
    capabilities: [{ name: "sql-engine", description: "Full SQL query engine with JOINs, GROUP BY, window functions", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 18500,
    rating: 4.8,
    ratingCount: 512,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.xql",
    name: "XQL Query",
    description:
      "Execute an XQL (eXtended Query Language) query — a hybrid SQL+JSON path+graph traversal language. Supports relational queries, JSON path expressions (@.field, $.data.nested), graph traversal, time-series windowing, UNNEST, LET bindings, COALESCE.",
    category: "analytics",
    icon: "Terminal",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["xql", "query", "hybrid", "json-path"],
    color: "#8b5cf6",
    parameters: [
      { name: "query", type: "string", description: 'XQL query, e.g. "SELECT name, @.metadata.tags, SUM(amount) as total FROM orders WHERE @.status = \'active\' GROUP BY name"', required: true },
    ],
    capabilities: [{ name: "xql-engine", description: "Hybrid SQL+JSON path+graph traversal query language", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 8200,
    rating: 4.5,
    ratingCount: 189,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.mdx",
    name: "MDX Query",
    description:
      "Execute an MDX (Multidimensional Expressions) query for OLAP-style analytics. Supports CROSSJOIN, FILTER, ORDER, TOPCOUNT/BOTTOMCOUNT, HEAD/TAIL, aggregate functions, calculated members (WITH MEMBER), IIF, CASE, and NON EMPTY.",
    category: "analytics",
    icon: "Grid3X3",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["mdx", "olap", "cubes", "bi"],
    color: "#f59e0b",
    parameters: [
      { name: "query", type: "string", description: 'MDX query, e.g. "SELECT [Measures].[Sales Amount] ON COLUMNS, [Product].[Category] ON ROWS FROM [SalesCube]"', required: true },
    ],
    capabilities: [{ name: "mdx-engine", description: "MDX OLAP query engine compatible with PowerBI/Excel/Tableau syntax", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 6800,
    rating: 4.4,
    ratingCount: 156,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.window",
    name: "Window Function Query",
    description:
      "Execute SQL with DuckDB-style window functions (ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, FIRST_VALUE, LAST_VALUE, NTILE, SUM/AVG/COUNT OVER PARTITION BY ... ORDER BY ...).",
    category: "analytics",
    icon: "Layers",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["window", "analytics", "rank"],
    color: "#06b6d4",
    parameters: [
      { name: "query", type: "string", description: 'SQL with window functions, e.g. "SELECT name, amount, ROW_NUMBER() OVER (PARTITION BY dept ORDER BY amount DESC) as rank FROM employees"', required: true },
    ],
    capabilities: [{ name: "window-functions", description: "DuckDB-style window function support", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 7400,
    rating: 4.6,
    ratingCount: 203,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.describe",
    name: "Describe Table",
    description:
      "Show schema and summary statistics (count, nulls, min, max, sum, avg, distinct) for all columns in a table.",
    category: "analytics",
    icon: "Info",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["schema", "stats", "metadata"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table", required: true },
    ],
    capabilities: [{ name: "describe", description: "Show table schema and statistics", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 9800,
    rating: 4.5,
    ratingCount: 267,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.csv_export",
    name: "Export CSV",
    description:
      "Export a table to CSV text format. Use after querying to get downloadable results.",
    category: "analytics",
    icon: "Download",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["csv", "export"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table", required: true },
    ],
    capabilities: [{ name: "csv-export", description: "Export tables to CSV format", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 10200,
    rating: 4.6,
    ratingCount: 278,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.json_export",
    name: "Export JSON",
    description:
      "Export a table to a JSON array of row objects.",
    category: "analytics",
    icon: "Download",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["json", "export"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table", required: true },
    ],
    capabilities: [{ name: "json-export", description: "Export tables to JSON format", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 9500,
    rating: 4.5,
    ratingCount: 256,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.export_powerbi",
    name: "Export for Power BI",
    description:
      "Export a table as a Power BI-compatible CSV with metadata header, plus auto-generated DAX measure templates for numeric columns.",
    category: "analytics",
    icon: "Download",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["powerbi", "dax", "export", "bi"],
    color: "#f59e0b",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table to export", required: true },
    ],
    capabilities: [{ name: "powerbi-export", description: "Export to Power BI compatible CSV + DAX templates", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 5600,
    rating: 4.4,
    ratingCount: 134,
    updatedAt: "2024-01-15",
    slmFriendly: false,
  },
  {
    id: "analytics.export_excel",
    name: "Export for Excel",
    description:
      "Export a table as an Excel-compatible file — CSV with BOM and formatting, or XML Spreadsheet (SSML) with styles and typed cells.",
    category: "analytics",
    icon: "Download",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["excel", "spreadsheet", "export"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table to export", required: true },
      { name: "format", type: "string", description: "Format: 'csv' (default) or 'xml' for native Excel XML", required: false, enum: ["csv", "xml"] },
    ],
    capabilities: [{ name: "excel-export", description: "Export to Excel CSV or XML Spreadsheet format", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 7200,
    rating: 4.5,
    ratingCount: 189,
    updatedAt: "2024-01-15",
    slmFriendly: false,
  },
  {
    id: "analytics.export_sheets",
    name: "Export for Google Sheets",
    description:
      "Export a table as Google Sheets-compatible CSV with schema metadata, plus auto-generated Sheets formulas for analysis.",
    category: "analytics",
    icon: "Download",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["google-sheets", "export", "formulas"],
    color: "#34a853",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table to export", required: true },
    ],
    capabilities: [{ name: "sheets-export", description: "Export to Google Sheets compatible CSV + formulas", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 4800,
    rating: 4.3,
    ratingCount: 112,
    updatedAt: "2024-01-15",
    slmFriendly: false,
  },
  {
    id: "analytics.export_tableau",
    name: "Export for Tableau",
    description:
      "Export a table as a Tableau-compatible TSV with typed columns, plus auto-generated Tableau workbook manifest (.twb) for auto-import.",
    category: "analytics",
    icon: "Download",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["tableau", "export", "twb", "tsv"],
    color: "#e97627",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table to export", required: true },
    ],
    capabilities: [{ name: "tableau-export", description: "Export to Tableau TSV + workbook manifest", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 3900,
    rating: 4.2,
    ratingCount: 98,
    updatedAt: "2024-01-15",
    slmFriendly: false,
  },
  {
    id: "analytics.join",
    name: "Join Tables",
    description:
      "Inner join two tables on a matching column. Returns a combined table with columns from both.",
    category: "analytics",
    icon: "GitMerge",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["join", "relational"],
    color: "#10b981",
    parameters: [
      { name: "leftTable", type: "string", description: "Left table name", required: true },
      { name: "rightTable", type: "string", description: "Right table name", required: true },
      { name: "onColumn", type: "string", description: "Column name to join on (must exist in both tables)", required: true },
      { name: "resultName", type: "string", description: "Name for the result table (default: joined)", required: false },
    ],
    capabilities: [{ name: "join", description: "Inner join two tables on matching column", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 8900,
    rating: 4.6,
    ratingCount: 234,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.groupby",
    name: "Group By Aggregation",
    description:
      "Group rows by one or more columns and compute aggregations (count, sum, avg, min, max) on specified columns.",
    category: "analytics",
    icon: "BarChart3",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["groupby", "aggregation", "statistics"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Source table name", required: true },
      { name: "groupBy", type: "string", description: "Comma-separated column names to group by", required: true },
      { name: "aggregations", type: "string", description: 'Comma-separated agg definitions, e.g. "count(*), sum(amount), avg(price)"', required: true },
      { name: "resultName", type: "string", description: "Name for the result table", required: false },
    ],
    capabilities: [{ name: "groupby", description: "Group-by aggregation with multiple functions", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 10500,
    rating: 4.7,
    ratingCount: 289,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.sort",
    name: "Sort Table",
    description: "Sort a table by a column in ascending or descending order.",
    category: "analytics",
    icon: "ArrowUpDown",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["sort", "order"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Table to sort", required: true },
      { name: "column", type: "string", description: "Column name to sort by", required: true },
      { name: "descending", type: "boolean", description: "Sort descending (default: false)", required: false },
    ],
    capabilities: [{ name: "sort", description: "Sort table by column", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 9200,
    rating: 4.5,
    ratingCount: 245,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.filter",
    name: "Filter Rows",
    description:
      "Keep only rows matching a condition. Returns a new table with matching rows.",
    category: "analytics",
    icon: "Filter",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["filter", "where"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Table to filter", required: true },
      { name: "column", type: "string", description: "Column to test", required: true },
      { name: "op", type: "string", description: "Operator: eq, neq, gt, lt, gte, lte, contains, startswith", required: true },
      { name: "value", type: "string", description: "Value to compare against", required: true },
    ],
    capabilities: [{ name: "filter", description: "Filter rows by condition", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 8700,
    rating: 4.5,
    ratingCount: 231,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.create_table",
    name: "Create Empty Table",
    description:
      "Create a new empty table with a defined schema. Useful for building datasets incrementally.",
    category: "analytics",
    icon: "Plus",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["create", "schema"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Name for the new table", required: true },
      { name: "columns", type: "string", description: 'Column definitions, e.g. "id:i32, name:str, amount:f64, active:bool"', required: true },
    ],
    capabilities: [{ name: "create-table", description: "Create empty tables with custom schemas", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 7800,
    rating: 4.4,
    ratingCount: 198,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.insert_rows",
    name: "Insert Rows",
    description:
      "Append one or more rows to an existing table. Values must match the table's column order and types.",
    category: "analytics",
    icon: "PlusSquare",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["insert", "data"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Table to insert into", required: true },
      { name: "rows", type: "string", description: 'JSON array of arrays, e.g. "[[1, \\"Alice\\", 100, true], [2, \\"Bob\\", 200, false]]"', required: true },
    ],
    capabilities: [{ name: "insert-rows", description: "Append rows to existing tables", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 7200,
    rating: 4.4,
    ratingCount: 187,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
  {
    id: "analytics.schema_export",
    name: "Export Schema",
    description:
      "Export the schema of a table as JSON — column names, types, nullable flags. Useful for documentation and cross-platform compatibility.",
    category: "analytics",
    icon: "FileJson",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["schema", "export", "metadata"],
    color: "#10b981",
    parameters: [
      { name: "tableName", type: "string", description: "Name of the table", required: true },
    ],
    capabilities: [{ name: "schema-export", description: "Export table schema as JSON", requiresBrowser: false, requiresNetwork: false, offline: true }],
    installs: 6100,
    rating: 4.3,
    ratingCount: 156,
    updatedAt: "2024-01-15",
    slmFriendly: true,
  },
];
