/**
 * Business Vertical Tools — Financial Scenarios, Chit Fund, Real Estate
 *
 * 45+ tools for three major business verticals.
 * Tools do the heavy lifting — SLMs just decide what to call.
 */

import type { ToolManifest } from "../tool-types";

// ═══════════════════════════════════════════════════════════════════════════════
// FINANCIAL SCENARIO TOOLS
// ═══════════════════════════════════════════════════════════════════════════════

export const FINANCIAL_TOOLS: ToolManifest[] = [
  {
    id: "fin.calc.loan",
    name: "Loan Calculator",
    description: "Calculate EMI, total interest, amortization schedule for any loan (home, car, personal, gold). Supports prepayment modeling and tax benefits.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "loan", "emi", "amortization", "prepayment"],
    icon: "Calculator",
    color: "#10b981",
    parameters: [
      { name: "principal", type: "number", description: "Loan amount in ₹", required: true },
      { name: "annualRate", type: "number", description: "Annual interest rate (e.g. 8.5 for 8.5%)", required: true },
      { name: "tenureMonths", type: "number", description: "Loan tenure in months", required: true },
      { name: "prepayment", type: "number", description: "Annual prepayment amount (optional)", required: false },
      { name: "processingFee", type: "number", description: "Processing fee in ₹ or %", required: false },
    ],
    capabilities: [{ name: "loan-calc", description: "Calculate EMI and amortization", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.sip",
    name: "SIP Calculator",
    description: "Calculate SIP returns with step-up, inflation adjustment, and LTCG tax. Shows year-wise wealth growth.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "sip", "mutual fund", "investment", "returns"],
    icon: "TrendingUp",
    color: "#10b981",
    parameters: [
      { name: "monthlyAmount", type: "number", description: "Monthly SIP amount in ₹", required: true },
      { name: "annualReturnRate", type: "number", description: "Expected annual return (e.g. 12 for 12%)", required: true },
      { name: "durationYears", type: "number", description: "Investment duration in years", required: true },
      { name: "stepUpPercent", type: "number", description: "Annual step-up percentage (optional)", required: false },
      { name: "inflationRate", type: "number", description: "Inflation rate (default 6%)", required: false },
    ],
    capabilities: [{ name: "sip-calc", description: "Calculate SIP returns", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.fd",
    name: "FD Calculator",
    description: "Calculate Fixed Deposit maturity with compounding (quarterly/monthly/yearly), TDS, and inflation-adjusted returns.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "fd", "fixed deposit", "compounding", "maturity"],
    icon: "Landmark",
    color: "#10b981",
    parameters: [
      { name: "principal", type: "number", description: "FD amount in ₹", required: true },
      { name: "annualRate", type: "number", description: "Annual interest rate", required: true },
      { name: "tenureYears", type: "number", description: "Tenure in years", required: true },
      { name: "compounding", type: "string", description: "Compounding frequency: quarterly, monthly, yearly", required: false },
    ],
    capabilities: [{ name: "fd-calc", description: "Calculate FD maturity", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.rd",
    name: "RD Calculator",
    description: "Calculate Recurring Deposit maturity with compounding and effective rate.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "rd", "recurring deposit", "savings"],
    icon: "PiggyBank",
    color: "#10b981",
    parameters: [
      { name: "monthlyDeposit", type: "number", description: "Monthly deposit amount in ₹", required: true },
      { name: "annualRate", type: "number", description: "Annual interest rate", required: true },
      { name: "tenureMonths", type: "number", description: "Tenure in months", required: true },
    ],
    capabilities: [{ name: "rd-calc", description: "Calculate RD maturity", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.tax",
    name: "Income Tax Calculator",
    description: "Calculate income tax under old and new regime (FY 2025-26). Shows regime comparison, effective rate, take-home, and recommends better regime.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "tax", "income tax", "old regime", "new regime", "deductions"],
    icon: "Receipt",
    color: "#10b981",
    parameters: [
      { name: "grossIncome", type: "number", description: "Annual gross income in ₹", required: true },
      { name: "section80C", type: "number", description: "Section 80C deductions (PPF, LIC, etc.)", required: false },
      { name: "section24", type: "number", description: "Section 24 home loan interest deduction", required: false },
      { name: "section80D", type: "number", description: "Section 80D health insurance deduction", required: false },
      { name: "hra", type: "number", description: "HRA exemption amount", required: false },
    ],
    capabilities: [{ name: "tax-calc", description: "Calculate income tax", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.goal",
    name: "Goal-Based Planner",
    description: "Calculate monthly investment needed to reach a financial goal (child education, retirement, house). Shows asset allocation and feasibility.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "goal", "planning", "investment", "retirement", "education"],
    icon: "Target",
    color: "#10b981",
    parameters: [
      { name: "targetAmount", type: "number", description: "Goal amount in ₹", required: true },
      { name: "targetDate", type: "string", description: "Target date (YYYY-MM-DD)", required: true },
      { name: "riskProfile", type: "string", description: "Conservative, moderate, or aggressive", required: true },
      { name: "currentSavings", type: "number", description: "Current savings amount", required: false },
    ],
    capabilities: [{ name: "goal-planner", description: "Plan investments for financial goals", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.stamp_duty",
    name: "Stamp Duty Calculator",
    description: "Calculate stamp duty and registration charges for any Indian state. State-wise rates built-in.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "stamp duty", "registration", "property", "real estate"],
    icon: "FileText",
    color: "#10b981",
    parameters: [
      { name: "propertyValue", type: "number", description: "Property value in ₹", required: true },
      { name: "state", type: "string", description: "Indian state name", required: true },
    ],
    capabilities: [{ name: "stamp-duty", description: "Calculate stamp duty and registration", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.swp",
    name: "SWP Calculator",
    description: "Calculate Systematic Withdrawal Plan — how long a corpus lasts with monthly withdrawals and returns.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "swp", "withdrawal", "retirement", "corpus"],
    icon: "ArrowDownRight",
    color: "#10b981",
    parameters: [
      { name: "corpus", type: "number", description: "Total corpus amount in ₹", required: true },
      { name: "monthlyWithdrawal", type: "number", description: "Monthly withdrawal amount in ₹", required: true },
      { name: "annualReturnRate", type: "number", description: "Expected annual return rate", required: true },
    ],
    capabilities: [{ name: "swp-calc", description: "Calculate SWP duration", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fin.calc.compare",
    name: "Investment Comparator",
    description: "Compare multiple investment options side-by-side (SIP vs FD vs PPF vs NPS). Shows best option by each metric.",
    category: "microfinance",
    subcategory: "calculator",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["finance", "compare", "investment", "sip", "fd", "ppf", "nps"],
    icon: "Scale",
    color: "#10b981",
    parameters: [
      { name: "amount", type: "number", description: "Investment amount in ₹", required: true },
      { name: "duration", type: "number", description: "Duration in years", required: true },
      { name: "options", type: "string", description: "Comma-separated: sip,fd,ppf,nps", required: true },
    ],
    capabilities: [{ name: "compare-investments", description: "Compare investment options", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHIT FUND TOOLS
// ═══════════════════════════════════════════════════════════════════════════════

export const CHITFUND_TOOLS: ToolManifest[] = [
  {
    id: "chit.group.create",
    name: "Create Chit Group",
    description: "Create a new chit group with members. Auto-calculates monthly contribution, commission, and generates member IDs.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "chitfund", "group", "create", "members"],
    icon: "Users",
    color: "#8b5cf6",
    parameters: [
      { name: "name", type: "string", description: "Chit group name", required: true },
      { name: "chitValue", type: "number", description: "Monthly chit value in ₹", required: true },
      { name: "numberOfMembers", type: "number", description: "Number of members (equal to months)", required: true },
      { name: "members", type: "string", description: "JSON array of {name, phone, address}", required: true },
      { name: "state", type: "string", description: "State for compliance", required: true },
    ],
    capabilities: [{ name: "chit-create", description: "Create chit group", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.round.bid",
    name: "Record Chit Bid",
    description: "Record a bid for the current chit round. Validates member eligibility and bid amount.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "bid", "auction", "discount"],
    icon: "Gavel",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
      { name: "memberId", type: "string", description: "Member ID", required: true },
      { name: "bidAmount", type: "number", description: "Bid amount in ₹ (lower = higher discount)", required: true },
    ],
    capabilities: [{ name: "chit-bid", description: "Record bid for chit round", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.round.close",
    name: "Close Chit Round",
    description: "Close bidding, determine winner, calculate dividend per member, and generate disbursement summary.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "close", "winner", "dividend", "disbursement"],
    icon: "CheckCircle",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
      { name: "bids", type: "string", description: "JSON array of {memberId, bidAmount}", required: true },
    ],
    capabilities: [{ name: "chit-close", description: "Close round and determine winner", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.collection.record",
    name: "Record Chit Collection",
    description: "Record a member's monthly contribution payment. Supports cash, cheque, UPI, bank transfer.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "collection", "payment", "contribution"],
    icon: "IndianRupee",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
      { name: "memberId", type: "string", description: "Member ID", required: true },
      { name: "amount", type: "number", description: "Amount paid", required: true },
      { name: "method", type: "string", description: "Payment method: cash, cheque, upi, bank_transfer", required: true },
    ],
    capabilities: [{ name: "chit-collection", description: "Record collection payment", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.member.statement",
    name: "Member Statement",
    description: "Generate complete statement for a chit member: contributions, dividends received, prize won, net position.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "statement", "member", "dividends", "position"],
    icon: "FileText",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
      { name: "memberId", type: "string", description: "Member ID", required: true },
    ],
    capabilities: [{ name: "chit-statement", description: "Generate member statement", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.foreman.report",
    name: "Foreman Report",
    description: "Generate foreman commission report: total commission earned, collections, disbursements, defaults.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "foreman", "commission", "report"],
    icon: "BarChart3",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
    ],
    capabilities: [{ name: "chit-foreman", description: "Generate foreman report", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.compliance.check",
    name: "Chit Compliance Check",
    description: "Check regulatory compliance: RERA, state limits, documentation, bonds. Based on Chit Funds Act 1982.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "compliance", "rera", "regulatory", "legal"],
    icon: "ShieldCheck",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
    ],
    capabilities: [{ name: "chit-compliance", description: "Check regulatory compliance", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.default.notice",
    name: "Generate Default Notice",
    description: "Generate formatted default notice for a member. Supports warning, final, and legal notice types.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "default", "notice", "legal", "warning"],
    icon: "AlertTriangle",
    color: "#8b5cf6",
    parameters: [
      { name: "groupId", type: "string", description: "Chit group ID", required: true },
      { name: "memberId", type: "string", description: "Member ID", required: true },
      { name: "missedRounds", type: "string", description: "Comma-separated missed round numbers", required: true },
    ],
    capabilities: [{ name: "chit-notice", description: "Generate default notice", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "chit.dashboard",
    name: "Chit Fund Dashboard",
    description: "Generate complete dashboard: all groups, collection rates, disbursements, defaults, commission earned.",
    category: "microfinance",
    subcategory: "chitfund",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["chit", "dashboard", "overview", "analytics"],
    icon: "LayoutDashboard",
    color: "#8b5cf6",
    parameters: [],
    capabilities: [{ name: "chit-dashboard", description: "Generate chit fund dashboard", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// REAL ESTATE TOOLS
// ═══════════════════════════════════════════════════════════════════════════════

export const REALESTATE_TOOLS: ToolManifest[] = [
  {
    id: "re.project.create",
    name: "Create Real Estate Project",
    description: "Create a new project with full cost estimation: land, construction, approvals, marketing, finance costs. Auto-generates profit analysis.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "project", "create", "cost", "estimation"],
    icon: "Building2",
    color: "#f59e0b",
    parameters: [
      { name: "name", type: "string", description: "Project name", required: true },
      { name: "location", type: "string", description: "Project location/address", required: true },
      { name: "city", type: "string", description: "City name", required: true },
      { name: "state", type: "string", description: "State name", required: true },
      { name: "type", type: "string", description: "apartment, villa, plot, commercial, mixed", required: true },
      { name: "landAreaAcres", type: "number", description: "Land area in acres", required: true },
      { name: "floors", type: "number", description: "Number of floors", required: true },
      { name: "landCost", type: "number", description: "Land acquisition cost in ₹", required: true },
      { name: "constructionCostPerSqFt", type: "number", description: "Construction cost per sq ft", required: true },
      { name: "sellingPricePerSqFt", type: "number", description: "Selling price per sq ft", required: true },
    ],
    capabilities: [{ name: "re-create", description: "Create RE project with cost estimation", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.cost.estimate",
    name: "Cost Estimation",
    description: "Quick cost estimation for a project: total cost, revenue, profit margin, breakeven units. What-if on different price points.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "cost", "estimation", "breakeven", "profit"],
    icon: "DollarSign",
    color: "#f59e0b",
    parameters: [
      { name: "landAreaAcres", type: "number", description: "Land area in acres", required: true },
      { name: "floors", type: "number", description: "Number of floors", required: true },
      { name: "constructionCostPerSqFt", type: "number", description: "Construction cost per sq ft", required: true },
      { name: "sellingPricePerSqFt", type: "number", description: "Selling price per sq ft", required: true },
      { name: "state", type: "string", description: "State name (for land rates)", required: true },
    ],
    capabilities: [{ name: "re-cost", description: "Quick cost estimation", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.sales.pipeline",
    name: "Sales Pipeline",
    description: "Generate sales pipeline report: leads, visits, negotiations, bookings, conversions, revenue vs target.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "sales", "pipeline", "conversion", "revenue"],
    icon: "Filter",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
    ],
    capabilities: [{ name: "re-pipeline", description: "Generate sales pipeline", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.crm.followup",
    name: "CRM Follow-up List",
    description: "Generate daily follow-up list: today's follow-ups, overdue, upcoming, hot leads, lost recovery candidates.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "crm", "followup", "leads", "hot"],
    icon: "Phone",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
    ],
    capabilities: [{ name: "re-followup", description: "Generate follow-up list", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.cashflow.report",
    name: "Cash Flow Report",
    description: "Generate project cash flow report: inflows, outflows, category breakdown, 12-month projection.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "cashflow", "report", "inflow", "outflow"],
    icon: "ArrowUpDown",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
      { name: "period", type: "string", description: "Period: month, quarter, year", required: false },
    ],
    capabilities: [{ name: "re-cashflow", description: "Generate cash flow report", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.profitability",
    name: "Profitability Analysis",
    description: "Calculate project profitability: ROI, IRR, gross/net margin, payback period, cost breakdown, revenue by unit.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "profit", "roi", "irr", "margin", "analysis"],
    icon: "PieChart",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
    ],
    capabilities: [{ name: "re-profit", description: "Calculate profitability", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.compliance.track",
    name: "Compliance Tracker",
    description: "Track RERA registration, approvals status, upcoming expiries, violations, compliance score.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "compliance", "rera", "approvals", "legal"],
    icon: "ClipboardCheck",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
    ],
    capabilities: [{ name: "re-compliance", description: "Track compliance status", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.forecast.revenue",
    name: "Revenue Forecast",
    description: "Forecast revenue based on current sales velocity. Shows monthly projections, target date, confidence level.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "forecast", "revenue", "velocity", "projection"],
    icon: "LineChart",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
      { name: "monthsAhead", type: "number", description: "Months to forecast (default 12)", required: false },
    ],
    capabilities: [{ name: "re-forecast", description: "Forecast revenue", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.dashboard",
    name: "Real Estate Dashboard",
    description: "Complete company dashboard: all projects, units sold, revenue, profit, inventory value, approvals pending.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "dashboard", "overview", "company"],
    icon: "LayoutDashboard",
    color: "#f59e0b",
    parameters: [],
    capabilities: [{ name: "re-dashboard", description: "Generate RE company dashboard", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "re.unit.pricing",
    name: "Unit Pricing Engine",
    description: "Calculate optimal unit pricing based on floor, facing, view, size. Auto-applies premiums and discounts.",
    category: "microfinance",
    subcategory: "realestate",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["realestate", "pricing", "unit", "premium", "floor", "facing"],
    icon: "Tag",
    color: "#f59e0b",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID", required: true },
      { name: "basePricePerSqFt", type: "number", description: "Base price per sq ft", required: true },
      { name: "floorRise", type: "number", description: "Per floor premium in ₹/sq ft", required: false },
      { name: "facingPremiums", type: "string", description: "JSON: {north: 0, south: 2, east: 5, west: 3}", required: false },
    ],
    capabilities: [{ name: "re-pricing", description: "Calculate unit pricing", requiresBrowser: false, requiresNetwork: false, offline: true }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
];
