/**
 * DiagramDesign Tools
 *
 * Visual architecture and flow mapping using Mermaid syntax.
 * Generates user journeys, component trees, data flows, architecture,
 * state machines, ER diagrams, and route maps.
 */

import type { ToolManifest } from "../tool-types";

export const DIAGRAM_TOOLS: ToolManifest[] = [
  {
    id: "diagram.user_journey",
    name: "User Journey Diagram",
    description: "Generate a user journey sequence diagram from route data",
    longDescription: "Creates a Mermaid sequence diagram showing the flow a user takes through the application, including authentication gates, page navigation, and interactive elements.",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "sequence", "user-journey", "flow"],
    icon: "GitBranch",
    color: "#06b6d4",
    parameters: [
      { name: "routes", type: "string", description: "JSON array of route data with path, isProtected, and interactions", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "User Journey" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid sequence diagrams", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "diagram.component_tree",
    name: "UI Component Tree",
    description: "Generate a component hierarchy diagram",
    longDescription: "Creates a Mermaid graph showing the containment hierarchy of UI components, from root layout to leaf elements.",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "component", "hierarchy", "tree"],
    icon: "Network",
    color: "#06b6d4",
    parameters: [
      { name: "components", type: "string", description: "JSON array of component data with name, children, and type", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "UI Component Tree" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid component tree diagrams", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "diagram.data_flow",
    name: "Data Flow Diagram",
    description: "Generate a data flow diagram showing how data moves through the system",
    longDescription: "Creates a Mermaid graph showing data flow between frontend, backend, databases, and external APIs with labeled transitions.",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "data-flow", "system", "integration"],
    icon: "ArrowRightLeft",
    color: "#06b6d4",
    parameters: [
      { name: "nodes", type: "string", description: "JSON array of node data with id, label, and type", required: true },
      { name: "edges", type: "string", description: "JSON array of edge data with from, to, label, and type", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "Data Flow" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid data flow diagrams", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "diagram.architecture",
    name: "System Architecture",
    description: "Generate a layered system architecture diagram",
    longDescription: "Creates a Mermaid diagram showing the high-level system architecture organized in layers (Presentation, Application, Data, Infrastructure).",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "architecture", "system", "layers"],
    icon: "LayoutGrid",
    color: "#06b6d4",
    parameters: [
      { name: "layers", type: "string", description: "JSON array of layer data with name and components", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "System Architecture" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid architecture diagrams", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "diagram.state_machine",
    name: "State Machine Diagram",
    description: "Generate a state machine diagram for interactive flows",
    longDescription: "Creates a Mermaid state diagram showing state transitions for multi-step wizards, shopping carts, or other interactive state machines.",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "state-machine", "workflow", "transitions"],
    icon: "RefreshCw",
    color: "#06b6d4",
    parameters: [
      { name: "states", type: "string", description: "JSON array of state names", required: true },
      { name: "transitions", type: "string", description: "JSON array of transitions with from, to, and event", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "State Machine" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid state machine diagrams", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "diagram.er_diagram",
    name: "ER Diagram",
    description: "Generate an Entity-Relationship diagram for data models",
    longDescription: "Creates a Mermaid ER diagram showing entities, their fields, primary keys, and relationships (1:1, 1:N, N:M).",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "er", "database", "data-model"],
    icon: "TableProperties",
    color: "#06b6d4",
    parameters: [
      { name: "entities", type: "string", description: "JSON array of entity data with name and fields", required: true },
      { name: "relationships", type: "string", description: "JSON array of relationships with from, to, and type", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "Data Model" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid ER diagrams", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "diagram.route_map",
    name: "Route Navigation Map",
    description: "Generate a route navigation map showing all routes and relationships",
    longDescription: "Creates a Mermaid graph showing all routes in the application with parent-child relationships, distinguishing protected routes from public ones.",
    category: "diagram",
    subcategory: "architecture",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["diagram", "mermaid", "routes", "navigation", "sitemap"],
    icon: "Map",
    color: "#06b6d4",
    parameters: [
      { name: "routes", type: "string", description: "JSON array of route data with path, children, and isProtected", required: true },
      { name: "title", type: "string", description: "Diagram title", required: false, default: "Route Navigation Map" },
    ],
    capabilities: [
      { name: "generate_diagram", description: "Generate Mermaid route navigation maps", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];
