/**
 * E-Commerce Operations — Store Tool Manifests
 *
 * These tools let agents RUN a store — not just view dashboards.
 * Each tool performs an action: classify tickets, process refunds,
 * update orders, manage inventory, respond to reviews, detect fraud.
 */

import type { ToolManifest } from "../tool-types";

export const ECOMMERCE_TOOLS: ToolManifest[] = [
  // ── Customer Service ──

  {
    id: "ecom.classify_ticket",
    name: "Classify Customer Ticket",
    description: "Read a customer message, detect intent, assign category and priority. Agent handles classification without human triage.",
    longDescription:
      "Analyzes customer ticket subject and message to automatically categorize (order issue, return, refund, complaint, etc.) and prioritize (low/medium/high/urgent). Returns suggested action based on category and order history.",
    category: "integrations",
    subcategory: "customer-service",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "customer-service", "ticket", "classification", "NLP"],
    icon: "MessageSquare",
    color: "#6366f1",
    parameters: [
      { name: "subject", type: "string", description: "Ticket subject line", required: true },
      { name: "message", type: "string", description: "Customer message body", required: true },
      { name: "orderId", type: "string", description: "Related order ID if available", required: false },
    ],
    capabilities: [{ name: "ticket-classification", description: "Classify intent and priority", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.auto_reply",
    name: "Auto-Reply to Ticket",
    description: "Generate and send contextual reply to customer ticket based on category, history, and order data.",
    longDescription:
      "Agent reads the ticket, checks order status, and generates a personalized response. Handles refunds, replacements, and escalations automatically when policy allows.",
    category: "integrations",
    subcategory: "customer-service",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "customer-service", "auto-reply", "refund", "NLP"],
    icon: "Reply",
    color: "#6366f1",
    parameters: [
      { name: "ticketId", type: "string", description: "Ticket ID to reply to", required: true },
      { name: "action", type: "enum", description: "Action to take", required: true, enum: ["reply", "refund", "replace", "escalate", "close"] },
      { name: "message", type: "string", description: "Reply message (auto-generated if omitted)", required: false },
      { name: "refundAmount", type: "number", description: "Refund amount in cents if action is refund", required: false },
    ],
    capabilities: [{ name: "ticket-reply", description: "Generate and send replies", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.process_refund",
    name: "Process Refund",
    description: "Process a payment refund for an order. Calculates amount, applies policy, processes reversal, notifies customer.",
    longDescription:
      "End-to-end refund processing: validates refund eligibility, calculates amount (full/partial), processes payment reversal through gateway, updates order status, sends confirmation to customer.",
    category: "integrations",
    subcategory: "customer-service",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "refund", "payment", "customer-service"],
    icon: "RotateCcw",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID to refund", required: true },
      { name: "ticketId", type: "string", description: "Associated ticket ID", required: false },
      { name: "amount", type: "number", description: "Refund amount in cents (omit for full refund)", required: false },
      { name: "reason", type: "string", description: "Refund reason", required: true },
    ],
    capabilities: [{ name: "refund-processing", description: "Process payment reversals", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.bulk_process_tickets",
    name: "Bulk Process Ticket Queue",
    description: "Process multiple tickets autonomously: auto-reply to simple ones, escalate complex ones, skip ambiguous ones.",
    longDescription:
      "Agent processes the ticket queue in bulk. For each ticket: classifies, decides if auto-reply is safe, generates response, sends it. Complex issues get escalated. Returns summary of all actions taken.",
    category: "integrations",
    subcategory: "customer-service",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "customer-service", "bulk", "automation", "queue"],
    icon: "ListChecks",
    color: "#6366f1",
    parameters: [
      { name: "maxTickets", type: "number", description: "Maximum tickets to process", required: false, default: 50 },
      { name: "autoReplyThreshold", type: "number", description: "Confidence threshold (0-1) for auto-reply", required: false, default: 0.85 },
    ],
    capabilities: [{ name: "bulk-processing", description: "Process ticket queue autonomously", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Order Management ──

  {
    id: "ecom.update_order_status",
    name: "Update Order Status",
    description: "Move order through lifecycle: confirmed → processing → packed → shipped → delivered. Notifies customer at each step.",
    longDescription:
      "Updates order status in the system and sends appropriate customer notification. Handles the full order lifecycle without human intervention.",
    category: "integrations",
    subcategory: "order-management",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "order", "status", "lifecycle", "notification"],
    icon: "Package",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID to update", required: true },
      { name: "status", type: "enum", description: "New order status", required: true, enum: ["confirmed", "processing", "packed", "shipped", "out_for_delivery", "delivered", "cancelled"] },
      { name: "trackingNumber", type: "string", description: "Tracking number (required for shipped)", required: false },
      { name: "carrier", type: "string", description: "Shipping carrier", required: false },
    ],
    capabilities: [{ name: "order-lifecycle", description: "Update order status and notify", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.cancel_order",
    name: "Cancel Order",
    description: "Cancel order, process automatic refund, restock inventory, notify customer. Handles cancellation policy checks.",
    longDescription:
      "Agent checks if order is cancellable (not yet shipped), processes refund per policy, restocks inventory, sends cancellation confirmation. Returns refund amount and confirmation.",
    category: "integrations",
    subcategory: "order-management",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "order", "cancel", "refund", "inventory"],
    icon: "XCircle",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID to cancel", required: true },
      { name: "reason", type: "string", description: "Cancellation reason", required: true },
      { name: "refundFull", type: "boolean", description: "Whether to refund full amount (vs. restocking fee)", required: false, default: true },
    ],
    capabilities: [{ name: "order-cancellation", description: "Cancel order with refund and restock", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.process_return",
    name: "Process Return Request",
    description: "Handle end-to-end return flow: approve/reject, generate return label, track return shipment, process refund or exchange.",
    longDescription:
      "Agent reviews return request, checks return policy (window, condition, reason), approves or rejects, generates prepaid return label, tracks return shipment, processes refund/exchange when received.",
    category: "integrations",
    subcategory: "order-management",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "return", "refund", "exchange", "shipping"],
    icon: "RotateCw",
    color: "#6366f1",
    parameters: [
      { name: "returnId", type: "string", description: "Return request ID", required: true },
      { name: "decision", type: "enum", description: "Approve or reject", required: true, enum: ["approve", "reject"] },
      { name: "refundType", type: "enum", description: "Type of refund", required: false, enum: ["full", "partial", "exchange", "store_credit"] },
      { name: "refundAmount", type: "number", description: "Partial refund amount in cents", required: false },
    ],
    capabilities: [{ name: "return-processing", description: "Full return lifecycle management", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.send_notification",
    name: "Send Order Notification",
    description: "Send personalized order notifications: confirmation, shipping update, delivery, delay alert. Agent composes message with order context.",
    longDescription:
      "Generates and sends contextual notifications to customers about their orders. Includes order details, tracking links, and personalized messages based on the notification type.",
    category: "integrations",
    subcategory: "order-management",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "notification", "email", "sms", "order"],
    icon: "Bell",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID", required: true },
      { name: "type", type: "enum", description: "Notification type", required: true, enum: ["confirmation", "shipping_update", "delivery", "delay_alert"] },
      { name: "customMessage", type: "string", description: "Custom message to include", required: false },
    ],
    capabilities: [{ name: "notifications", description: "Send order-related notifications", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Inventory ──

  {
    id: "ecom.update_inventory",
    name: "Update Inventory",
    description: "Adjust stock levels after sale, return, adjustment, or damage. Triggers low-stock alerts automatically.",
    longDescription:
      "Updates product stock quantity with reason tracking (sale, return, adjustment, damage, theft). Automatically triggers reorder alerts when stock drops below threshold.",
    category: "integrations",
    subcategory: "inventory",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "inventory", "stock", "reorder"],
    icon: "Boxes",
    color: "#6366f1",
    parameters: [
      { name: "productId", type: "string", description: "Product ID", required: true },
      { name: "quantity", type: "number", description: "Quantity change (positive = add, negative = remove)", required: true },
      { name: "reason", type: "enum", description: "Reason for change", required: true, enum: ["sale", "return", "adjustment", "restock", "damage", "theft"] },
      { name: "notes", type: "string", description: "Additional notes", required: false },
    ],
    capabilities: [{ name: "inventory-management", description: "Update stock with reason tracking", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.auto_reorder",
    name: "Auto-Reorder Stock",
    description: "Automatically place reorder when stock drops below threshold. Calculates quantity based on sales velocity and supplier lead time.",
    longDescription:
      "Agent analyzes historical sales velocity, current stock level, and supplier lead time to calculate optimal reorder quantity. Places purchase order with supplier automatically.",
    category: "integrations",
    subcategory: "inventory",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "inventory", "reorder", "procurement", "supplier"],
    icon: "Truck",
    color: "#6366f1",
    parameters: [
      { name: "productId", type: "string", description: "Product ID to reorder", required: true },
      { name: "salesVelocityDays", type: "number", description: "Days of sales history to use for calculation", required: false, default: 30 },
    ],
    capabilities: [{ name: "auto-reorder", description: "Calculate and place reorder automatically", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.prevent_stockout",
    name: "Prevent Stockout",
    description: "Cross-reference pending orders with available stock. Identify products at risk and take proactive action.",
    longDescription:
      "Scans all products, compares current stock against pending orders, calculates days until stockout, and takes action: halt sales, trigger rush orders, or notify purchasing team.",
    category: "integrations",
    subcategory: "inventory",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "inventory", "stockout", "prevention", "proactive"],
    icon: "AlertTriangle",
    color: "#6366f1",
    parameters: [],
    capabilities: [{ name: "stockout-prevention", description: "Detect and prevent stockouts proactively", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Product Catalog ──

  {
    id: "ecom.upsert_product",
    name: "Add/Update Product",
    description: "Create or update product listing with optimized title, description, and tags. Agent generates SEO-friendly content.",
    longDescription:
      "Creates a new product or updates an existing one. Agent generates optimized product title, description, and search tags based on product data and category conventions.",
    category: "integrations",
    subcategory: "catalog",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "product", "catalog", "SEO", "listing"],
    icon: "ShoppingBag",
    color: "#6366f1",
    parameters: [
      { name: "name", type: "string", description: "Product name", required: true },
      { name: "price", type: "number", description: "Price in cents", required: true },
      { name: "description", type: "string", description: "Product description (auto-generated if omitted)", required: false },
      { name: "category", type: "string", description: "Product category", required: false },
      { name: "sku", type: "string", description: "Stock keeping unit", required: false },
      { name: "stock", type: "number", description: "Initial stock quantity", required: false },
    ],
    capabilities: [{ name: "product-management", description: "Create and update product listings", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.optimize_listing",
    name: "Optimize Product Listing",
    description: "Rewrite product title, description, and tags for SEO and conversion. Agent analyzes search data and best practices.",
    longDescription:
      "Agent reads current listing, analyzes search trends and competitor listings, then rewrites title, description, and tags for maximum visibility and conversion. Shows before/after with reasoning.",
    category: "integrations",
    subcategory: "catalog",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "product", "SEO", "optimization", "listing"],
    icon: "Sparkles",
    color: "#6366f1",
    parameters: [
      { name: "productId", type: "string", description: "Product ID to optimize", required: true },
      { name: "focus", type: "enum", description: "Optimization focus", required: false, enum: ["seo", "conversion", "both"], default: "both" },
    ],
    capabilities: [{ name: "listing-optimization", description: "Optimize product listings for search and conversion", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.adjust_price",
    name: "Dynamic Price Adjustment",
    description: "Adjust product price based on demand, competition, inventory levels, and pricing rules.",
    longDescription:
      "Agent monitors sales velocity, competitor prices, and stock levels to recommend price adjustments within configured bounds (min/max margin). Applies change and logs reasoning.",
    category: "integrations",
    subcategory: "catalog",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "pricing", "dynamic", "competitive", "margin"],
    icon: "DollarSign",
    color: "#6366f1",
    parameters: [
      { name: "productId", type: "string", description: "Product ID", required: true },
      { name: "newPrice", type: "number", description: "New price in cents", required: true },
      { name: "reason", type: "string", description: "Reason for price change", required: true },
    ],
    capabilities: [{ name: "dynamic-pricing", description: "Adjust prices based on market conditions", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Shipping ──

  {
    id: "ecom.create_shipment",
    name: "Create Shipping Label",
    description: "Generate shipping label, compare carrier rates, select optimal shipping option. Agent handles full shipping workflow.",
    longDescription:
      "Compares rates across carriers (FedEx, UPS, USPS, DHL), selects cheapest or fastest option based on config, generates shipping label, assigns tracking number, updates order status.",
    category: "integrations",
    subcategory: "shipping",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "shipping", "label", "carrier", "tracking"],
    icon: "Truck",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID to ship", required: true },
      { name: "carrier", type: "string", description: "Preferred carrier (auto-selected if omitted)", required: false },
      { name: "service", type: "string", description: "Shipping service level", required: false },
    ],
    capabilities: [{ name: "shipping-label", description: "Generate labels and compare carrier rates", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.track_shipment",
    name: "Track Shipment",
    description: "Monitor shipment transit, detect delays, proactively notify customers. Agent watches all active shipments.",
    longDescription:
      "Polls carrier API for tracking updates, detects exceptions (delays, failed delivery, returned), composes proactive customer notification with updated ETA.",
    category: "integrations",
    subcategory: "shipping",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "shipping", "tracking", "proactive", "exception"],
    icon: "MapPin",
    color: "#6366f1",
    parameters: [
      { name: "trackingNumber", type: "string", description: "Tracking number", required: true },
      { name: "carrier", type: "string", description: "Carrier name", required: true },
    ],
    capabilities: [{ name: "shipment-tracking", description: "Monitor transit and detect exceptions", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Reviews ──

  {
    id: "ecom.respond_to_review",
    name: "Respond to Review",
    description: "Generate and post personalized response to customer review. Agent matches tone to sentiment.",
    longDescription:
      "Reads review content and sentiment, generates appropriate response (thankful for positive, apologetic for negative, helpful for questions), posts response on behalf of store.",
    category: "integrations",
    subcategory: "reviews",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "review", "response", "reputation", "sentiment"],
    icon: "Star",
    color: "#6366f1",
    parameters: [
      { name: "reviewId", type: "string", description: "Review ID", required: true },
      { name: "productId", type: "string", description: "Product ID", required: true },
      { name: "response", type: "string", description: "Response text (auto-generated if omitted)", required: false },
      { name: "tone", type: "enum", description: "Response tone", required: false, enum: ["professional", "friendly", "apologetic"], default: "professional" },
    ],
    capabilities: [{ name: "review-response", description: "Generate and post review responses", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.analyze_reviews",
    name: "Analyze Reviews",
    description: "Extract sentiment, issues, and actionable insights from product reviews. Agent identifies product improvement opportunities.",
    longDescription:
      "Processes product reviews to extract sentiment breakdown, top complaints, top praises, and actionable product improvement suggestions. Includes response rate metrics.",
    category: "integrations",
    subcategory: "reviews",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "review", "sentiment", "analytics", "insights"],
    icon: "BarChart3",
    color: "#6366f1",
    parameters: [
      { name: "productId", type: "string", description: "Product ID (omit for all products)", required: false },
      { name: "limit", type: "number", description: "Maximum reviews to analyze", required: false, default: 100 },
    ],
    capabilities: [{ name: "review-analysis", description: "Analyze sentiment and extract insights", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Fraud Detection ──

  {
    id: "ecom.check_fraud",
    name: "Check Order for Fraud",
    description: "Analyze order for fraud indicators: address mismatch, velocity, payment patterns, behavioral signals.",
    longDescription:
      "Scores order 0-100 based on: billing/shipping address mismatch, order velocity (too many orders from same IP), unusual amount, new account with high-value order, known fraud patterns.",
    category: "integrations",
    subcategory: "fraud",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "fraud", "security", "detection", "scoring"],
    icon: "ShieldAlert",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID to check", required: true },
    ],
    capabilities: [{ name: "fraud-detection", description: "Score orders for fraud risk", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.hold_order",
    name: "Hold Suspicious Order",
    description: "Place order on hold pending review. Notifies security team and preserves evidence for investigation.",
    longDescription:
      "Freezes order processing, flags in system, sends alert to security team with fraud score and evidence. Preserves all order data for investigation.",
    category: "integrations",
    subcategory: "fraud",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "fraud", "security", "hold", "investigation"],
    icon: "Lock",
    color: "#6366f1",
    parameters: [
      { name: "orderId", type: "string", description: "Order ID to hold", required: true },
      { name: "reason", type: "string", description: "Hold reason", required: true },
      { name: "fraudScore", type: "number", description: "Fraud score (0-100)", required: true },
      { name: "flags", type: "array", description: "Fraud indicators detected", required: false },
    ],
    capabilities: [{ name: "order-hold", description: "Freeze suspicious orders for review", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  // ── Operations ──

  {
    id: "ecom.daily_report",
    name: "Daily Sales Report",
    description: "Calculate actionable daily sales metrics. Agent produces numbers and actions, not charts.",
    longDescription:
      "Generates daily summary: orders, revenue, AOV, returns, refunds, new vs repeat customers, top products, and issues requiring attention. Pure operational data.",
    category: "integrations",
    subcategory: "operations",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "sales", "report", "daily", "operations"],
    icon: "FileText",
    color: "#6366f1",
    parameters: [
      { name: "date", type: "string", description: "Date (YYYY-MM-DD, defaults to today)", required: false },
    ],
    capabilities: [{ name: "daily-report", description: "Calculate daily operational metrics", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },

  {
    id: "ecom.at_risk_customers",
    name: "Identify At-Risk Customers",
    description: "Find customers likely to churn or complain. Agent proactively reaches out before issues escalate.",
    longDescription:
      "Analyzes customer behavior: time since last order, support ticket history, review sentiment, order value trends. Identifies customers at risk of churning and suggests re-engagement actions.",
    category: "integrations",
    subcategory: "operations",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["ecommerce", "churn", "retention", "customer", "proactive"],
    icon: "Users",
    color: "#6366f1",
    parameters: [],
    capabilities: [{ name: "churn-detection", description: "Identify at-risk customers proactively", requiresBrowser: false, requiresNetwork: true, offline: false }],
    slmFriendly: true,
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: new Date().toISOString(),
  },
];
