/**
 * Awesome Harness Engineering — CAR Framework Tools
 *
 * Control-Agency-Runtime governance with evaluation gates,
 * spend rails, and sandboxed execution boundaries.
 */

import type { ToolManifest } from "../tool-types";

export const HARNESS_TOOLS: ToolManifest[] = [
  {
    id: "harness.car_config",
    name: "CAR Configuration",
    description: "Configure the Control-Agency-Runtime harness for agent governance",
    longDescription: "Sets up the CAR framework with Control (permissions, approvals), Agency (autonomy levels, tool access), and Runtime (token budgets, cost caps, timeouts) layers.",
    category: "harness",
    subcategory: "governance",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["harness", "car", "governance", "control", "agency", "runtime"],
    icon: "Shield",
    color: "#f59e0b",
    parameters: [
      { name: "name", type: "string", description: "Harness name", required: true },
      { name: "autonomyLevel", type: "enum", description: "Default agent autonomy level", required: false, default: "semi-autonomous", enum: ["supervised", "semi-autonomous", "autonomous"] },
      { name: "tokenBudget", type: "number", description: "Session token budget", required: false, default: 100000 },
      { name: "costCap", type: "number", description: "Session cost cap in USD", required: false, default: 5.0 },
    ],
    capabilities: [
      { name: "configure_harness", description: "Set up CAR framework governance", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "harness.register_agent",
    name: "Register Agent",
    description: "Register a new agent in the harness with capabilities and budgets",
    longDescription: "Creates an agent profile with role, autonomy level, allowed tools, and token budget. The harness tracks usage and enforces limits.",
    category: "harness",
    subcategory: "governance",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["harness", "agent", "register", "capabilities", "budget"],
    icon: "UserPlus",
    color: "#f59e0b",
    parameters: [
      { name: "name", type: "string", description: "Agent name", required: true },
      { name: "role", type: "string", description: "Agent role (e.g., crawler, auditor, diagrammer)", required: true },
      { name: "autonomyLevel", type: "enum", description: "Agent autonomy level", required: false, default: "semi-autonomous", enum: ["supervised", "semi-autonomous", "autonomous"] },
      { name: "tokenBudget", type: "number", description: "Maximum tokens for this agent", required: false, default: 10000 },
    ],
    capabilities: [
      { name: "register_agent", description: "Create agent profile in harness", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "harness.spend_check",
    name: "Check Spend Rails",
    description: "Verify resource usage is within limits before executing actions",
    longDescription: "Checks the CAR framework spend rails to verify that a proposed action (token usage, cost, time, memory) is within the configured limits.",
    category: "harness",
    subcategory: "governance",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["harness", "spend", "budget", "limits", "rail"],
    icon: "Gauge",
    color: "#f59e0b",
    parameters: [
      { name: "resource", type: "enum", description: "Resource type to check", required: true, enum: ["tokens", "cost", "time", "memory"] },
      { name: "amount", type: "number", description: "Amount of resource to use", required: true },
    ],
    capabilities: [
      { name: "check_spend", description: "Verify action is within spend rails", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "harness.gate_evaluate",
    name: "Evaluate Gates",
    description: "Run verification gates to check analysis completeness",
    longDescription: "Evaluates the registered verification gates against current progress. Each gate has conditions (route coverage, component catalog, design tokens, etc.) that must pass for the audit to be marked complete.",
    category: "harness",
    subcategory: "governance",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["harness", "gates", "evaluation", "verification", "completeness"],
    icon: "CheckCircle",
    color: "#f59e0b",
    parameters: [
      { name: "context", type: "string", description: "JSON object of metric values for gate conditions", required: false, default: "{}" },
    ],
    capabilities: [
      { name: "evaluate_gates", description: "Run verification gate pipeline", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "harness.generate_agents_md",
    name: "Generate AGENTS.md",
    description: "Generate the AGENTS.md governance file from the current harness configuration",
    longDescription: "Produces a complete AGENTS.md file documenting the harness configuration, control policies, agency capabilities, runtime budgets, evaluation gates, and required tool capabilities.",
    category: "harness",
    subcategory: "governance",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["harness", "agents-md", "governance", "documentation", "config"],
    icon: "FileCode",
    color: "#f59e0b",
    parameters: [],
    capabilities: [
      { name: "generate_agents_md", description: "Produce AGENTS.md governance file", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "harness.action_check",
    name: "Check Action Policy",
    description: "Verify if an action is allowed by the control policy",
    longDescription: "Checks whether a proposed action is allowed, blocked, or requires human approval under the current CAR control layer policies.",
    category: "harness",
    subcategory: "governance",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["harness", "policy", "permission", "approval", "control"],
    icon: "Lock",
    color: "#f59e0b",
    parameters: [
      { name: "action", type: "string", description: "Action to check (e.g., deploy, crawl, audit)", required: true },
    ],
    capabilities: [
      { name: "check_action", description: "Verify action against control policy", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];
