/**
 * stitaP HuggingFace Tools
 *
 * Tools for searching, downloading, and managing AI models from HuggingFace Hub.
 */

import type { ToolManifest } from "../tool-types";

export const HUGGINGFACE_TOOLS: ToolManifest[] = [
  {
    id: "huggingface.search",
    name: "Search HuggingFace Models",
    description: "Search the HuggingFace Hub for AI models. Supports filtering by GGUF files, parameter count, RAM requirements, and tags.",
    category: "llm",
    tags: ["huggingface", "models", "search", "gguf"],
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    icon: "🔍",
    color: "#FFD21E",
    parameters: [
      { name: "query", type: "string", required: true, description: "Search query (e.g., 'qwen2.5', 'llama', 'phi-3')" },
      { name: "ggufOnly", type: "boolean", required: false, description: "Only show models with GGUF files (default: true)", default: true },
      { name: "maxRAMGB", type: "number", required: false, description: "Maximum RAM in GB for estimated model size (default: 16)", default: 16 },
      { name: "limit", type: "number", required: false, description: "Maximum number of results (default: 20)", default: 20 },
    ],
    capabilities: [
      { name: "searchModels", description: "Search HuggingFace Hub for AI models", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-29",
    slmFriendly: true,
  },
  {
    id: "huggingface.download",
    name: "Download HuggingFace Model",
    description: "Download a GGUF model file from HuggingFace Hub. Supports progress tracking, pause/resume, and automatic quantization selection.",
    category: "llm",
    tags: ["huggingface", "download", "gguf", "model"],
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    icon: "⬇️",
    color: "#FFD21E",
    parameters: [
      { name: "modelId", type: "string", required: true, description: "HuggingFace model ID (e.g., 'Qwen/Qwen2.5-1.5B-Instruct-GGUF')" },
      { name: "quant", type: "string", required: false, description: "Quantization level (e.g., 'Q4_K_M', 'Q8_0', 'F16'). Auto-selected if not specified." },
      { name: "maxRAMGB", type: "number", required: false, description: "Available RAM in GB for quantization selection (default: 16)" },
    ],
    capabilities: [
      { name: "downloadModel", description: "Download GGUF model files from HuggingFace", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-29",
    slmFriendly: true,
  },
  {
    id: "huggingface.list_downloaded",
    name: "List Downloaded Models",
    description: "List all HuggingFace models that have been downloaded and are available locally.",
    category: "llm",
    tags: ["huggingface", "models", "local"],
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    icon: "📦",
    color: "#FFD21E",
    parameters: [],
    capabilities: [
      { name: "listDownloaded", description: "List locally downloaded models", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-29",
    slmFriendly: true,
  },
  {
    id: "huggingface.delete",
    name: "Delete Downloaded Model",
    description: "Delete a downloaded HuggingFace model from local storage to free up disk space.",
    category: "llm",
    tags: ["huggingface", "delete", "cleanup"],
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    icon: "🗑️",
    color: "#FF4444",
    parameters: [
      { name: "modelId", type: "string", required: true, description: "HuggingFace model ID" },
      { name: "filename", type: "string", required: true, description: "GGUF filename to delete" },
    ],
    capabilities: [
      { name: "deleteModel", description: "Delete downloaded model files", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-29",
    slmFriendly: true,
  },
  {
    id: "huggingface.quant_info",
    name: "Get Quantization Info",
    description: "Get detailed information about a quantization level including bits per weight, quality score, speed score, and RAM requirements.",
    category: "llm",
    tags: ["huggingface", "quantization", "info"],
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    icon: "📊",
    color: "#FFD21E",
    parameters: [
      { name: "quant", type: "string", required: false, description: "Quantization level (e.g., 'Q4_K_M'). If omitted, returns all levels." },
    ],
    capabilities: [
      { name: "quantInfo", description: "Get quantization level details", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-29",
    slmFriendly: true,
  },
  {
    id: "huggingface.recommend",
    name: "Recommend Model",
    description: "Get a recommended model and quantization level based on available RAM and use case.",
    category: "llm",
    tags: ["huggingface", "recommend", "model"],
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    icon: "💡",
    color: "#FFD21E",
    parameters: [
      { name: "ramGB", type: "number", required: true, description: "Available RAM in GB" },
      { name: "category", type: "string", required: false, description: "Use case: 'general', 'code', 'math', 'multilingual', 'tiny'" },
    ],
    capabilities: [
      { name: "recommendModel", description: "Recommend model based on RAM and use case", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-29",
    slmFriendly: true,
  },
];
