/**
 * Integration Tools — Store manifests for Database, Email/SMS, Payment,
 * Storage, Maps, Collaboration, Hardware, and OS Integration tools.
 */

import type { ToolManifest } from "../tool-types";

// ═══════════════════════════════════════════════════════════════════
// DATABASE TOOLS
// ═══════════════════════════════════════════════════════════════════

export const DATABASE_TOOLS: ToolManifest[] = [
  {
    id: "database.query",
    name: "Database Query",
    description: "Execute SQL queries against PostgreSQL, MySQL, SQLite, or MongoDB",
    longDescription: "Run parameterized SQL queries against any supported database. Supports prepared statements, transactions, and result streaming. Works with PostgreSQL, MySQL, SQLite, and MongoDB.",
    category: "integrations",
    subcategory: "database",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["database", "sql", "nosql", "query"],
    icon: "Database",
    color: "#6366f1",
    parameters: [
      { name: "provider", type: "string", description: "Database provider", required: true, enum: ["postgresql", "mysql", "sqlite", "mongodb"] },
      { name: "query", type: "string", description: "SQL query or MongoDB operation", required: true },
      { name: "params", type: "array", description: "Query parameters for prepared statements", required: false },
      { name: "connectionId", type: "string", description: "Reuse an existing connection", required: false },
    ],
    capabilities: [
      { name: "query", description: "Execute SQL queries and return rows", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 8500,
    rating: 4.7,
    ratingCount: 189,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "database.connect",
    name: "Database Connect",
    description: "Create a persistent connection with pooling",
    longDescription: "Establish a persistent database connection with connection pooling, automatic reconnection, and SSL/TLS support.",
    category: "integrations",
    subcategory: "database",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["database", "connection", "pool"],
    icon: "Plug",
    color: "#6366f1",
    parameters: [
      { name: "provider", type: "string", description: "Database provider", required: true, enum: ["postgresql", "mysql", "sqlite", "mongodb"] },
      { name: "host", type: "string", description: "Database host", required: false },
      { name: "port", type: "number", description: "Port number", required: false },
      { name: "database", type: "string", description: "Database name", required: true },
      { name: "username", type: "string", description: "Username", required: false },
      { name: "password", type: "string", description: "Password", required: false },
      { name: "ssl", type: "boolean", description: "Enable SSL", required: false, default: false },
    ],
    capabilities: [
      { name: "connect", description: "Create persistent connections", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 7200,
    rating: 4.6,
    ratingCount: 145,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "database.schema",
    name: "Schema Inspector",
    description: "Inspect tables, columns, indexes, and relationships",
    longDescription: "Introspect database schema to discover tables, columns, types, primary keys, foreign keys, indexes, and constraints.",
    category: "integrations",
    subcategory: "database",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["database", "schema", "introspection"],
    icon: "TableProperties",
    color: "#6366f1",
    parameters: [
      { name: "connectionId", type: "string", description: "Connection ID to inspect", required: true },
      { name: "table", type: "string", description: "Specific table to inspect", required: false },
      { name: "includeIndexes", type: "boolean", description: "Include index information", required: false, default: true },
    ],
    capabilities: [
      { name: "schema", description: "Read database schema metadata", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 5400,
    rating: 4.5,
    ratingCount: 98,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "database.migrate",
    name: "Database Migration",
    description: "Run schema migrations with rollback support",
    longDescription: "Execute forward and rollback migrations. Supports dry-run mode to preview changes without applying them.",
    category: "integrations",
    subcategory: "database",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["database", "migration", "schema"],
    icon: "GitBranch",
    color: "#6366f1",
    parameters: [
      { name: "connectionId", type: "string", description: "Connection ID", required: true },
      { name: "operations", type: "array", description: "Migration operations", required: true },
      { name: "dryRun", type: "boolean", description: "Preview without applying", required: false, default: false },
    ],
    capabilities: [
      { name: "migrate", description: "Execute schema migrations", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 4100,
    rating: 4.4,
    ratingCount: 76,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
];

// ═══════════════════════════════════════════════════════════════════
// COMMUNICATION TOOLS
// ═══════════════════════════════════════════════════════════════════

export const COMMUNICATION_TOOLS: ToolManifest[] = [
  {
    id: "email.send",
    name: "Send Email",
    description: "Send emails via SMTP, SendGrid, Resend, or Postmark",
    longDescription: "Send transactional and marketing emails through multiple providers. Supports HTML templates, attachments, and tracking.",
    category: "integrations",
    subcategory: "email",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["email", "send", "smtp", "notification"],
    icon: "Mail",
    color: "#f59e0b",
    parameters: [
      { name: "provider", type: "string", description: "Email provider", required: true, enum: ["smtp", "sendgrid", "resend", "postmark"] },
      { name: "to", type: "array", description: "Recipient email addresses", required: true },
      { name: "from", type: "string", description: "Sender email address", required: true },
      { name: "subject", type: "string", description: "Email subject", required: true },
      { name: "text", type: "string", description: "Plain text body", required: false },
      { name: "html", type: "string", description: "HTML body", required: false },
    ],
    capabilities: [
      { name: "send", description: "Send emails via provider API or SMTP", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 9200,
    rating: 4.8,
    ratingCount: 234,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "email.template",
    name: "Email Template",
    description: "Render HTML email templates with variables",
    longDescription: "Compile Mustache-style templates with variable interpolation into HTML emails.",
    category: "integrations",
    subcategory: "email",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["email", "template", "render"],
    icon: "FileText",
    color: "#f59e0b",
    parameters: [
      { name: "template", type: "string", description: "Template string with {{variables}}", required: true },
      { name: "variables", type: "object", description: "Template variables", required: true },
      { name: "format", type: "string", description: "Output format", required: false, enum: ["html", "text"], default: "html" },
    ],
    capabilities: [
      { name: "render", description: "Render email templates", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 6300,
    rating: 4.6,
    ratingCount: 112,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "sms.send",
    name: "Send SMS",
    description: "Send SMS messages via Twilio, Vonage, or AWS SNS",
    longDescription: "Send SMS messages globally through Twilio, Vonage, or AWS SNS. Supports delivery status tracking.",
    category: "integrations",
    subcategory: "sms",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["sms", "twilio", "notification"],
    icon: "MessageSquare",
    color: "#f59e0b",
    parameters: [
      { name: "provider", type: "string", description: "SMS provider", required: true, enum: ["twilio", "vonage", "sns"] },
      { name: "to", type: "string", description: "Phone number", required: true },
      { name: "from", type: "string", description: "Sender number or short code", required: false },
      { name: "body", type: "string", description: "Message text", required: true },
    ],
    capabilities: [
      { name: "send", description: "Send SMS via provider API", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 5800,
    rating: 4.5,
    ratingCount: 87,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "voice.call",
    name: "Voice Call / TTS",
    description: "Voice calls or TTS audio via Twilio, ElevenLabs, or Azure",
    longDescription: "Make outbound voice calls or generate text-to-speech audio files using AI voices.",
    category: "integrations",
    subcategory: "voice",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["voice", "tts", "speech", "call"],
    icon: "Phone",
    color: "#f59e0b",
    parameters: [
      { name: "provider", type: "string", description: "Voice provider", required: true, enum: ["twilio", "elevenlabs", "azure-tts"] },
      { name: "to", type: "string", description: "Phone number (for calls)", required: false },
      { name: "text", type: "string", description: "Text to speak", required: true },
      { name: "voice", type: "string", description: "Voice ID or name", required: false },
      { name: "language", type: "string", description: "Language code", required: false, default: "en-US" },
    ],
    capabilities: [
      { name: "tts", description: "Generate speech from text", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 4900,
    rating: 4.4,
    ratingCount: 65,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];

// ═══════════════════════════════════════════════════════════════════
// PAYMENT / COMMERCE TOOLS
// ═══════════════════════════════════════════════════════════════════

export const COMMERCE_TOOLS: ToolManifest[] = [
  {
    id: "payment.create_checkout",
    name: "Create Checkout",
    description: "Create Stripe checkout for one-time or subscription payments",
    longDescription: "Create a Stripe checkout session for products, subscriptions, or invoices. Returns a URL to redirect the customer.",
    category: "integrations",
    subcategory: "payments",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["payment", "stripe", "checkout"],
    icon: "CreditCard",
    color: "#8b5cf6",
    parameters: [
      { name: "provider", type: "string", description: "Payment provider", required: true, enum: ["stripe", "paddle", "lemon-squeezy"] },
      { name: "amount", type: "number", description: "Amount in smallest currency unit (cents)", required: true },
      { name: "currency", type: "string", description: "ISO currency code", required: true },
      { name: "productName", type: "string", description: "Product name", required: true },
      { name: "mode", type: "string", description: "Payment mode", required: false, enum: ["payment", "subscription"], default: "payment" },
    ],
    capabilities: [
      { name: "checkout", description: "Create payment checkout sessions", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 7800,
    rating: 4.7,
    ratingCount: 156,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "payment.verify",
    name: "Verify Payment",
    description: "Verify a completed payment by session or transaction ID",
    longDescription: "Confirm a payment was successful by checking the session status with the payment provider.",
    category: "integrations",
    subcategory: "payments",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["payment", "verify", "webhook"],
    icon: "CheckCircle",
    color: "#8b5cf6",
    parameters: [
      { name: "provider", type: "string", description: "Payment provider", required: true, enum: ["stripe", "paddle", "lemon-squeezy"] },
      { name: "sessionId", type: "string", description: "Checkout session ID", required: true },
    ],
    capabilities: [
      { name: "verify", description: "Verify payment status", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 5100,
    rating: 4.6,
    ratingCount: 98,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "payment.invoice",
    name: "Generate Invoice",
    description: "Generate PDF invoices with line items and taxes",
    longDescription: "Create professional PDF invoices with customizable branding, line items, tax calculations, and notes.",
    category: "integrations",
    subcategory: "payments",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["invoice", "pdf", "billing"],
    icon: "Receipt",
    color: "#8b5cf6",
    parameters: [
      { name: "items", type: "array", description: "Line items with name, quantity, unitPrice", required: true },
      { name: "currency", type: "string", description: "ISO currency code", required: true },
      { name: "tax", type: "number", description: "Tax rate (0-1)", required: false, default: 0 },
      { name: "notes", type: "string", description: "Additional notes", required: false },
    ],
    capabilities: [
      { name: "invoice", description: "Generate PDF invoices", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 4200,
    rating: 4.5,
    ratingCount: 72,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "payment.subscription",
    name: "Manage Subscription",
    description: "Create, update, or cancel recurring subscriptions",
    longDescription: "Manage the full subscription lifecycle: create, update plan, pause, resume, and cancel.",
    category: "integrations",
    subcategory: "payments",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["subscription", "billing", "recurring"],
    icon: "RefreshCw",
    color: "#8b5cf6",
    parameters: [
      { name: "provider", type: "string", description: "Payment provider", required: true, enum: ["stripe", "paddle"] },
      { name: "action", type: "string", description: "Action to perform", required: true, enum: ["create", "update", "cancel", "list"] },
      { name: "customerId", type: "string", description: "Customer ID", required: false },
      { name: "priceId", type: "string", description: "Price/plan ID", required: false },
    ],
    capabilities: [
      { name: "subscribe", description: "Manage recurring subscriptions", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 3800,
    rating: 4.3,
    ratingCount: 54,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
];

// ═══════════════════════════════════════════════════════════════════
// CLOUD STORAGE TOOLS
// ═══════════════════════════════════════════════════════════════════

export const STORAGE_TOOLS: ToolManifest[] = [
  {
    id: "storage.upload",
    name: "Upload File",
    description: "Upload files to S3, GCS, Azure Blob, or local storage",
    longDescription: "Upload files to any cloud storage provider with metadata, ACLs, and content-type detection.",
    category: "integrations",
    subcategory: "storage",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["storage", "upload", "s3", "cloud"],
    icon: "Upload",
    color: "#10b981",
    parameters: [
      { name: "provider", type: "string", description: "Storage provider", required: true, enum: ["s3", "gcs", "azure", "local"] },
      { name: "bucket", type: "string", description: "Bucket name", required: true },
      { name: "key", type: "string", description: "Object key/path", required: true },
      { name: "content", type: "string", description: "File content (string or base64)", required: true },
      { name: "contentType", type: "string", description: "MIME type", required: false },
    ],
    capabilities: [
      { name: "upload", description: "Upload files to cloud storage", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 6400,
    rating: 4.6,
    ratingCount: 132,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "storage.download",
    name: "Download File",
    description: "Download files from cloud storage",
    longDescription: "Download files from any cloud storage provider. Supports range requests for partial downloads.",
    category: "integrations",
    subcategory: "storage",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["storage", "download"],
    icon: "Download",
    color: "#10b981",
    parameters: [
      { name: "provider", type: "string", description: "Storage provider", required: true, enum: ["s3", "gcs", "azure", "local"] },
      { name: "bucket", type: "string", description: "Bucket name", required: true },
      { name: "key", type: "string", description: "Object key/path", required: true },
    ],
    capabilities: [
      { name: "download", description: "Download files from cloud storage", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 5900,
    rating: 4.5,
    ratingCount: 108,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "storage.list",
    name: "List Files",
    description: "List files in a bucket with prefix filtering",
    longDescription: "List objects in a cloud storage bucket with prefix filtering, pagination, and delimiter support.",
    category: "integrations",
    subcategory: "storage",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["storage", "list", "browse"],
    icon: "FolderOpen",
    color: "#10b981",
    parameters: [
      { name: "provider", type: "string", description: "Storage provider", required: true, enum: ["s3", "gcs", "azure", "local"] },
      { name: "bucket", type: "string", description: "Bucket name", required: true },
      { name: "prefix", type: "string", description: "Key prefix filter", required: false },
      { name: "maxKeys", type: "number", description: "Max results", required: false, default: 100, min: 1, max: 1000 },
    ],
    capabilities: [
      { name: "list", description: "List objects in a bucket", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 5200,
    rating: 4.4,
    ratingCount: 89,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "storage.share",
    name: "Generate Share Link",
    description: "Generate a presigned URL for secure file sharing",
    longDescription: "Create time-limited presigned URLs for sharing private files without exposing credentials.",
    category: "integrations",
    subcategory: "storage",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["storage", "share", "presigned"],
    icon: "Share2",
    color: "#10b981",
    parameters: [
      { name: "provider", type: "string", description: "Storage provider", required: true, enum: ["s3", "gcs", "azure"] },
      { name: "bucket", type: "string", description: "Bucket name", required: true },
      { name: "key", type: "string", description: "Object key", required: true },
      { name: "expiresInMinutes", type: "number", description: "Link expiry in minutes", required: false, default: 60, min: 5, max: 10080 },
    ],
    capabilities: [
      { name: "share", description: "Generate presigned share URLs", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 4800,
    rating: 4.5,
    ratingCount: 78,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];

// ═══════════════════════════════════════════════════════════════════
// MAPS & GEOCODING TOOLS
// ═══════════════════════════════════════════════════════════════════

export const MAPS_TOOLS: ToolManifest[] = [
  {
    id: "maps.geocode",
    name: "Geocode Address",
    description: "Convert address text to GPS coordinates",
    longDescription: "Forward geocode using OpenStreetMap (free, no API key) or Google Maps. Returns coordinates, formatted address, and relevance score.",
    category: "integrations",
    subcategory: "maps",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["maps", "geocode", "location"],
    icon: "MapPin",
    color: "#06b6d4",
    parameters: [
      { name: "address", type: "string", description: "Address to geocode", required: true },
      { name: "limit", type: "number", description: "Max results", required: false, default: 5 },
      { name: "countryCode", type: "string", description: "ISO country code filter", required: false },
      { name: "provider", type: "string", description: "Map provider", required: false, enum: ["osm", "google", "mapbox"], default: "osm" },
    ],
    capabilities: [
      { name: "geocode", description: "Convert addresses to coordinates", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 7600,
    rating: 4.7,
    ratingCount: 167,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "maps.reverse-geocode",
    name: "Reverse Geocode",
    description: "Convert GPS coordinates to an address",
    longDescription: "Reverse geocode coordinates to get a human-readable address using OpenStreetMap or Google Maps.",
    category: "integrations",
    subcategory: "maps",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["maps", "reverse-geocode"],
    icon: "MapPin",
    color: "#06b6d4",
    parameters: [
      { name: "lat", type: "number", description: "Latitude", required: true },
      { name: "lng", type: "number", description: "Longitude", required: true },
      { name: "provider", type: "string", description: "Map provider", required: false, enum: ["osm", "google"], default: "osm" },
    ],
    capabilities: [
      { name: "reverse", description: "Convert coordinates to addresses", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 5400,
    rating: 4.5,
    ratingCount: 98,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "maps.route",
    name: "Calculate Route",
    description: "Driving, cycling, or walking route between waypoints",
    longDescription: "Calculate optimal routes using OSRM with turn-by-turn directions, distance, and ETA.",
    category: "integrations",
    subcategory: "maps",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["maps", "route", "navigation"],
    icon: "Navigation",
    color: "#06b6d4",
    parameters: [
      { name: "waypoints", type: "array", description: "Array of {lat, lng} points", required: true },
      { name: "profile", type: "string", description: "Transport mode", required: false, enum: ["car", "bike", "foot"], default: "car" },
      { name: "steps", type: "boolean", description: "Include turn-by-turn steps", required: false, default: true },
    ],
    capabilities: [
      { name: "route", description: "Calculate routes between points", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 4900,
    rating: 4.4,
    ratingCount: 76,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "maps.isochrone",
    name: "Isochrone",
    description: "Areas reachable within N minutes from a point",
    longDescription: "Calculate isochrone polygons showing areas reachable within specified time ranges.",
    category: "integrations",
    subcategory: "maps",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["maps", "isochrone", "accessibility"],
    icon: "Circle",
    color: "#06b6d4",
    parameters: [
      { name: "lat", type: "number", description: "Center latitude", required: true },
      { name: "lng", type: "number", description: "Center longitude", required: true },
      { name: "ranges", type: "array", description: "Time ranges in minutes", required: true },
      { name: "profile", type: "string", description: "Transport mode", required: false, enum: ["car", "bike", "foot"], default: "car" },
    ],
    capabilities: [
      { name: "isochrone", description: "Calculate reachable areas", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 3200,
    rating: 4.3,
    ratingCount: 45,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "maps.geofence",
    name: "Geofence",
    description: "Create and check geographic boundary zones",
    longDescription: "Manage geofences: create circular or polygonal zones, check if points are inside, and list active geofences.",
    category: "integrations",
    subcategory: "maps",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["maps", "geofence", "boundary"],
    icon: "Hexagon",
    color: "#06b6d4",
    parameters: [
      { name: "action", type: "string", description: "Action to perform", required: true, enum: ["create", "check", "delete", "list"] },
      { name: "fence", type: "object", description: "Geofence definition (for create)", required: false },
      { name: "point", type: "object", description: "Point to check (for check)", required: false },
    ],
    capabilities: [
      { name: "geofence", description: "Manage geographic boundaries", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 2800,
    rating: 4.2,
    ratingCount: 34,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];

// ═══════════════════════════════════════════════════════════════════
// COLLABORATION TOOLS
// ═══════════════════════════════════════════════════════════════════

export const COLLABORATION_TOOLS: ToolManifest[] = [
  {
    id: "collab.session.create",
    name: "Create Session",
    description: "Create a real-time collaboration session",
    longDescription: "Create a WebSocket-based session for multi-agent or multi-user collaboration with presence tracking.",
    category: "integrations",
    subcategory: "collaboration",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["collaboration", "session", "realtime"],
    icon: "Users",
    color: "#ec4899",
    parameters: [
      { name: "name", type: "string", description: "Session name", required: true },
      { name: "ownerId", type: "string", description: "Owner user ID", required: true },
      { name: "maxUsers", type: "number", description: "Max participants", required: false, default: 20 },
    ],
    capabilities: [
      { name: "session", description: "Create collaboration sessions", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 3600,
    rating: 4.4,
    ratingCount: 52,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "collab.session.join",
    name: "Join Session",
    description: "Join an existing session with presence tracking",
    longDescription: "Join a collaboration session and receive real-time presence updates for all participants.",
    category: "integrations",
    subcategory: "collaboration",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["collaboration", "join", "presence"],
    icon: "UserPlus",
    color: "#ec4899",
    parameters: [
      { name: "sessionId", type: "string", description: "Session ID to join", required: true },
      { name: "userId", type: "string", description: "Your user ID", required: true },
      { name: "name", type: "string", description: "Display name", required: true },
    ],
    capabilities: [
      { name: "join", description: "Join collaboration sessions", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 3400,
    rating: 4.3,
    ratingCount: 48,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "collab.ot.transform",
    name: "Operational Transform",
    description: "Resolve concurrent editing conflicts via OT",
    longDescription: "Transform concurrent text editing operations to maintain consistency across multiple editors.",
    category: "integrations",
    subcategory: "collaboration",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["collaboration", "ot", "conflict-resolution"],
    icon: "GitMerge",
    color: "#ec4899",
    parameters: [
      { name: "document", type: "string", description: "Current document text", required: true },
      { name: "operations", type: "array", description: "Concurrent operations to resolve", required: true },
      { name: "strategy", type: "string", description: "Resolution strategy", required: false, enum: ["ot", "last-write-wins"], default: "ot" },
    ],
    capabilities: [
      { name: "ot", description: "Operational transform for text", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 2100,
    rating: 4.2,
    ratingCount: 28,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
  {
    id: "collab.channel.create",
    name: "Create Channel",
    description: "Create a messaging channel in a session",
    longDescription: "Create public, private, or direct messaging channels within a collaboration session.",
    category: "integrations",
    subcategory: "collaboration",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["collaboration", "channel", "chat"],
    icon: "MessageCircle",
    color: "#ec4899",
    parameters: [
      { name: "sessionId", type: "string", description: "Session ID", required: true },
      { name: "name", type: "string", description: "Channel name", required: true },
      { name: "type", type: "string", description: "Channel type", required: false, enum: ["public", "private", "direct"], default: "public" },
    ],
    capabilities: [
      { name: "channel", description: "Create messaging channels", requiresBrowser: false, requiresNetwork: true, offline: false },
    ],
    installs: 2600,
    rating: 4.2,
    ratingCount: 36,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];

// ═══════════════════════════════════════════════════════════════════
// HARDWARE TOOLS
// ═══════════════════════════════════════════════════════════════════

export const HARDWARE_TOOLS: ToolManifest[] = [
  {
    id: "hardware.camera",
    name: "Capture Photo",
    description: "Capture photo from device camera (mobile/web)",
    longDescription: "Access device camera to capture photos. Supports front/back camera selection and resolution control.",
    category: "integrations",
    subcategory: "hardware",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["hardware", "camera", "photo", "mobile"],
    icon: "Camera",
    color: "#f97316",
    parameters: [
      { name: "facingMode", type: "string", description: "Camera facing", required: false, enum: ["user", "environment"], default: "environment" },
      { name: "width", type: "number", description: "Max width", required: false, default: 1920 },
      { name: "height", type: "number", description: "Max height", required: false, default: 1080 },
      { name: "quality", type: "number", description: "JPEG quality (0-1)", required: false, default: 0.92, min: 0.1, max: 1 },
    ],
    capabilities: [
      { name: "camera", description: "Capture photos from device camera", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 5200,
    rating: 4.5,
    ratingCount: 89,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "hardware.gps",
    name: "Get GPS Location",
    description: "Get current GPS position from the device",
    longDescription: "Access device GPS to get current latitude, longitude, altitude, accuracy, and heading.",
    category: "integrations",
    subcategory: "hardware",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["hardware", "gps", "location", "mobile"],
    icon: "Locate",
    color: "#f97316",
    parameters: [
      { name: "highAccuracy", type: "boolean", description: "High accuracy mode", required: false, default: true },
      { name: "timeout", type: "number", description: "Timeout in ms", required: false, default: 10000 },
    ],
    capabilities: [
      { name: "gps", description: "Get device GPS location", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 4800,
    rating: 4.4,
    ratingCount: 76,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "hardware.clipboard",
    name: "Clipboard",
    description: "Read/write text or images to system clipboard",
    longDescription: "Access the system clipboard for reading text, writing text, and reading images.",
    category: "integrations",
    subcategory: "hardware",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["hardware", "clipboard"],
    icon: "Clipboard",
    color: "#f97316",
    parameters: [
      { name: "action", type: "string", description: "Clipboard action", required: true, enum: ["read", "write", "readImage"] },
      { name: "text", type: "string", description: "Text to write (for write action)", required: false },
    ],
    capabilities: [
      { name: "clipboard", description: "Read/write clipboard content", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 6100,
    rating: 4.6,
    ratingCount: 112,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "hardware.speech",
    name: "Text-to-Speech",
    description: "Speak text using device speech synthesis",
    longDescription: "Convert text to speech using the browser's speech synthesis engine with language and voice control.",
    category: "integrations",
    subcategory: "hardware",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["hardware", "speech", "tts", "audio"],
    icon: "Volume2",
    color: "#f97316",
    parameters: [
      { name: "text", type: "string", description: "Text to speak", required: true },
      { name: "lang", type: "string", description: "Language code", required: false, default: "en-US" },
      { name: "rate", type: "number", description: "Speech rate (0.1-10)", required: false, default: 1, min: 0.1, max: 10 },
      { name: "pitch", type: "number", description: "Speech pitch (0-2)", required: false, default: 1, min: 0, max: 2 },
    ],
    capabilities: [
      { name: "tts", description: "Text-to-speech synthesis", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 4200,
    rating: 4.3,
    ratingCount: 56,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "hardware.motion",
    name: "Accelerometer",
    description: "Read device motion sensors (accelerometer + gyroscope)",
    longDescription: "Access device motion sensors for accelerometer and gyroscope data. Useful for motion-triggered workflows.",
    category: "integrations",
    subcategory: "hardware",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["hardware", "accelerometer", "gyroscope", "mobile"],
    icon: "Activity",
    color: "#f97316",
    parameters: [
      { name: "duration", type: "number", description: "Sample duration in ms", required: false, default: 5000 },
    ],
    capabilities: [
      { name: "motion", description: "Read accelerometer and gyroscope", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 2900,
    rating: 4.2,
    ratingCount: 34,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
];

// ═══════════════════════════════════════════════════════════════════
// OS INTEGRATION TOOLS
// ═══════════════════════════════════════════════════════════════════

export const OS_TOOLS: ToolManifest[] = [
  {
    id: "os.system-info",
    name: "System Information",
    description: "Get platform, CPUs, memory, screen, locale info",
    longDescription: "Retrieve system-level information including platform, architecture, CPU count, memory, screen resolution, and locale.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "system", "info"],
    icon: "Monitor",
    color: "#64748b",
    parameters: [],
    capabilities: [
      { name: "system-info", description: "Read system information", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 6800,
    rating: 4.6,
    ratingCount: 143,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "os.file.read",
    name: "Read File",
    description: "Read a file from the local filesystem",
    longDescription: "Read file contents from the local filesystem. In Electron: full access. In browser: File System Access API.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "filesystem", "read"],
    icon: "File",
    color: "#64748b",
    parameters: [
      { name: "path", type: "string", description: "File path", required: true },
    ],
    capabilities: [
      { name: "read", description: "Read file contents", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 5400,
    rating: 4.5,
    ratingCount: 98,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "os.file.write",
    name: "Write File",
    description: "Write content to a local file",
    longDescription: "Write string or binary content to a file on the local filesystem.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "filesystem", "write"],
    icon: "FileEdit",
    color: "#64748b",
    parameters: [
      { name: "path", type: "string", description: "File path", required: true },
      { name: "content", type: "string", description: "File content", required: true },
    ],
    capabilities: [
      { name: "write", description: "Write file contents", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 5100,
    rating: 4.4,
    ratingCount: 87,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "os.file.list",
    name: "List Directory",
    description: "List files and subdirectories in a path",
    longDescription: "List directory contents with file type, size, and modification time.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "filesystem", "list"],
    icon: "FolderOpen",
    color: "#64748b",
    parameters: [
      { name: "path", type: "string", description: "Directory path", required: true },
      { name: "recursive", type: "boolean", description: "List recursively", required: false, default: false },
    ],
    capabilities: [
      { name: "list", description: "List directory contents", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 4800,
    rating: 4.4,
    ratingCount: 76,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "os.file.watch",
    name: "Watch File",
    description: "Watch a file or directory for changes",
    longDescription: "Monitor filesystem changes with create, modify, delete, and rename event detection.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "filesystem", "watch"],
    icon: "Eye",
    color: "#64748b",
    parameters: [
      { name: "path", type: "string", description: "Path to watch", required: true },
      { name: "recursive", type: "boolean", description: "Watch recursively", required: false, default: false },
    ],
    capabilities: [
      { name: "watch", description: "Watch filesystem for changes", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 3900,
    rating: 4.3,
    ratingCount: 54,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
  {
    id: "os.tray",
    name: "System Tray",
    description: "Create or update a system tray icon (Electron)",
    longDescription: "Manage system tray icons with context menus for desktop applications.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "tray", "electron", "desktop"],
    icon: "LayoutDashboard",
    color: "#64748b",
    parameters: [
      { name: "title", type: "string", description: "Tray tooltip text", required: true },
      { name: "icon", type: "string", description: "Icon path or data URL", required: false },
      { name: "menu", type: "array", description: "Context menu items", required: false },
    ],
    capabilities: [
      { name: "tray", description: "Manage system tray", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 2400,
    rating: 4.1,
    ratingCount: 28,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
  {
    id: "os.process.list",
    name: "List Processes",
    description: "List running system processes",
    longDescription: "Enumerate running processes with CPU and memory usage for monitoring and debugging.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "process", "monitoring"],
    icon: "Activity",
    color: "#64748b",
    parameters: [],
    capabilities: [
      { name: "processes", description: "List system processes", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 3200,
    rating: 4.2,
    ratingCount: 42,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
  {
    id: "os.execute",
    name: "Execute Command",
    description: "Execute a shell command (sandboxed)",
    longDescription: "Run shell commands in a sandboxed environment with timeout and working directory control.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "shell", "execute"],
    icon: "Terminal",
    color: "#64748b",
    parameters: [
      { name: "command", type: "string", description: "Shell command", required: true },
      { name: "cwd", type: "string", description: "Working directory", required: false },
      { name: "timeout", type: "number", description: "Timeout in ms", required: false, default: 30000 },
    ],
    capabilities: [
      { name: "execute", description: "Run shell commands", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 4600,
    rating: 4.4,
    ratingCount: 68,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
  {
    id: "os.notify",
    name: "Desktop Notification",
    description: "Send native desktop or browser notification",
    longDescription: "Display system-level notifications with title, body, and icon.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "notification", "alert"],
    icon: "Bell",
    color: "#64748b",
    parameters: [
      { name: "title", type: "string", description: "Notification title", required: true },
      { name: "body", type: "string", description: "Notification body", required: false },
      { name: "icon", type: "string", description: "Icon URL", required: false },
    ],
    capabilities: [
      { name: "notify", description: "Send desktop notifications", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 5600,
    rating: 4.5,
    ratingCount: 94,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "os.power",
    name: "Power Management",
    description: "Check power source and prevent display sleep",
    longDescription: "Query battery status and manage display sleep settings for long-running tasks.",
    category: "integrations",
    subcategory: "os",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["os", "power", "battery"],
    icon: "Battery",
    color: "#64748b",
    parameters: [
      { name: "action", type: "string", description: "Power action", required: true, enum: ["getSource", "preventSleep", "allowSleep"] },
    ],
    capabilities: [
      { name: "power", description: "Manage power and sleep settings", requiresBrowser: true, requiresNetwork: false, offline: true },
    ],
    installs: 2100,
    rating: 4.1,
    ratingCount: 24,
    updatedAt: "2026-08-30",
    slmFriendly: false,
  },
];

// ═══════════════════════════════════════════════════════════════════
// ALL INTEGRATION TOOLS
// ═══════════════════════════════════════════════════════════════════

export const INTEGRATION_TOOLS: ToolManifest[] = [
  ...DATABASE_TOOLS,
  ...COMMUNICATION_TOOLS,
  ...COMMERCE_TOOLS,
  ...STORAGE_TOOLS,
  ...MAPS_TOOLS,
  ...COLLABORATION_TOOLS,
  ...HARDWARE_TOOLS,
  ...OS_TOOLS,
];
