/**
 * OpenViking Context Store Tools
 *
 * Tiered context storage (L0/L1/L2) for organizing extracted
 * webbuilder assets without overwhelming LLM context windows.
 */

import type { ToolManifest } from "../tool-types";

export const VIKING_TOOLS: ToolManifest[] = [
  {
    id: "viking.create_project",
    name: "Create Viking Project",
    description: "Initialize a new viking:// context store for a webbuilder project",
    longDescription: "Creates a new hierarchical context namespace under viking://resources/ for organizing crawled website assets across L0 (Abstract), L1 (Overview), and L2 (Details) tiers.",
    category: "viking",
    subcategory: "context",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["viking", "context", "tiered", "storage", "openviking"],
    icon: "Database",
    color: "#6366f1",
    parameters: [
      { name: "name", type: "string", description: "Project name", required: true },
      { name: "baseUrl", type: "string", description: "Base URL of the target website", required: true },
    ],
    capabilities: [
      { name: "create_project", description: "Create a new viking:// project namespace", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "viking.index_resource",
    name: "Index Resource",
    description: "Store a crawled resource in the appropriate tier (L0/L1/L2)",
    longDescription: "Indexes a crawled webpage, component, or API endpoint into the viking:// hierarchical store. L0 stores ~100-token summaries, L1 stores ~2,000-token overviews, L2 stores full raw content.",
    category: "viking",
    subcategory: "context",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["viking", "index", "tiered", "L0", "L1", "L2"],
    icon: "FolderTree",
    color: "#6366f1",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID to index into", required: true },
      { name: "path", type: "string", description: "Resource path (e.g., /landing)", required: true },
      { name: "tier", type: "enum", description: "Storage tier", required: true, enum: ["L0", "L1", "L2"] },
      { name: "summary", type: "string", description: "L0 abstract summary (~100 tokens)", required: true },
    ],
    capabilities: [
      { name: "index_resource", description: "Store crawled data in tiered context", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "viking.query",
    name: "Query Context",
    description: "Search and retrieve resources from the viking:// store with budget-aware tier loading",
    longDescription: "Queries the tiered context store with a search term and token budget. Automatically loads L0 summaries first, then L1 overviews if the budget allows, and only loads L2 details when explicitly requested.",
    category: "viking",
    subcategory: "context",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["viking", "query", "search", "budget-aware", "retrieval"],
    icon: "Search",
    color: "#6366f1",
    parameters: [
      { name: "projectId", type: "string", description: "Project ID to search", required: true },
      { name: "search", type: "string", description: "Search query", required: false },
      { name: "tier", type: "enum", description: "Maximum tier to load", required: false, default: "L1", enum: ["L0", "L1", "L2"] },
      { name: "tokenBudget", type: "number", description: "Maximum tokens to return", required: false, default: 4000 },
    ],
    capabilities: [
      { name: "query_context", description: "Budget-aware tiered retrieval", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "viking.build_context",
    name: "Build LLM Context",
    description: "Generate an SLM-friendly context block from indexed resources",
    longDescription: "Queries the viking:// store and builds a compact, token-budgeted context string suitable for injection into SLM prompts. Returns only the most relevant L0 summaries and L1 overviews.",
    category: "viking",
    subcategory: "context",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["viking", "context", "llm", "prompt", "rag"],
    icon: "MessageSquare",
    color: "#6366f1",
    parameters: [
      { name: "query", type: "string", description: "Search query for relevant context", required: true },
      { name: "tokenBudget", type: "number", description: "Maximum tokens for context block", required: false, default: 4000 },
    ],
    capabilities: [
      { name: "build_context", description: "Generate budgeted context for LLM prompts", requiresBrowser: false, requiresNetwork: false, offline: true },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
  {
    id: "viking.webbuilder_audit",
    name: "WebBuilder Audit",
    description: "Run requirement analysis audit across 6 functional pillars",
    longDescription: "Performs comprehensive automated audit of a webbuilder project covering: Architecture & Routing, Component Library & Design Tokens, Data Management & APIs, Interactive Behavior, Performance/Accessibility/SEO, and Agentic Integration Readiness.",
    category: "viking",
    subcategory: "audit",
    version: "1.0.0",
    author: "stitaP",
    license: "MIT",
    tags: ["viking", "audit", "webbuilder", "requirements", "analysis", "seo", "a11y"],
    icon: "ClipboardCheck",
    color: "#6366f1",
    parameters: [
      { name: "url", type: "string", description: "Target URL to audit", required: true },
      { name: "depth", type: "enum", description: "Audit depth", required: false, default: "full", enum: ["quick", "full", "deep"] },
    ],
    capabilities: [
      { name: "webbuilder_audit", description: "Automated requirement analysis across 6 pillars", requiresBrowser: true, requiresNetwork: true, offline: false },
    ],
    installs: 0,
    rating: 0,
    ratingCount: 0,
    updatedAt: "2026-08-30",
    slmFriendly: true,
  },
];
