/**
 * Capture replay — "capture once, replay on every version release."
 *
 * A capture document stores everything needed to reproduce itself: source
 * URL, viewport, mode, selector/region, and metadata. From that we generate
 * a self-contained Playwright script that re-drives the same page against a
 * *new* version and produces a fresh base raster — so documentation captures
 * survive version changes without re-authoring annotations or metadata.
 *
 * Pure and deterministic: the same document always yields the same script,
 * which makes this module smoke-testable in Node. The script is generated,
 * not model-authored — a 2-bit model hallucinating navigation code would be
 * less reliable than replaying the exact parameters that produced the
 * capture in the first place.
 */
import type { CaptureDocument, CaptureRequest } from "./types";

/** The replayable essence of a capture — everything the script needs. */
export interface CaptureRecipe {
  schemaVersion: 1;
  title: string;
  url?: string;
  mode: CaptureRequest["mode"];
  viewport: { width: number; height: number; deviceScaleFactor: number };
  selector?: string;
  region?: { x: number; y: number; width: number; height: number };
  readiness: {
    strategy: CaptureRequest["readiness"]["strategy"];
    additionalDelayMs: number;
    timeoutMs: number;
    /** CSS selector waited for when `strategy` is "selector". */
    selector?: string;
  };
  scrolling: {
    stepRatio: number;
    delayMs: number;
    maximumHeight: number;
    maximumPasses: number;
  };
  output: {
    rasterFormat: string;
    includeMetadata: boolean;
  };
}

/** Build the replay recipe from a captured document. */
export function buildCaptureRecipe(document: CaptureDocument): CaptureRecipe {
  const s = document.source;
  return {
    schemaVersion: 1,
    title: s.title || "Untitled capture",
    url: s.url,
    mode: s.mode,
    viewport: { ...s.viewport },
    region: undefined,
    readiness: {
      strategy: "load",
      additionalDelayMs: 500,
      timeoutMs: 60_000,
    },
    scrolling: {
      stepRatio: 0.8,
      delayMs: 250,
      maximumHeight: 100_000,
      maximumPasses: 40,
    },
    output: {
      rasterFormat: "png",
      includeMetadata: true,
    },
  };
}

/** Build the replay recipe from a request (pre-capture preview). */
export function recipeFromRequest(request: CaptureRequest): CaptureRecipe {
  return {
    schemaVersion: 1,
    title: "Replay capture",
    url: request.source.type === "url" ? request.source.url : undefined,
    mode: request.mode,
    viewport: { ...request.viewport },
    selector: request.source.selector,
    region: request.region,
    readiness: { ...request.readiness },
    scrolling: { ...request.scrolling },
    output: {
      rasterFormat: request.output.rasterFormat,
      includeMetadata: request.output.includeMetadata,
    },
  };
}

/** Escape a string for embedding inside a JS single-quoted string. */
function jsString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
}

/**
 * Generate a Playwright-compatible script that reproduces the capture
 * against any target URL. Deterministic; every parameter comes from the
 * recipe.
 */
export function buildReplayScript(recipe: CaptureRecipe, targetUrl?: string): string {
  const url = targetUrl ?? recipe.url;
  const lines: string[] = [];
  const p = (n: number) => "  ".repeat(n);

  lines.push(`// Generated by stitaP — capture replay recipe v${recipe.schemaVersion}`);
  lines.push(`// Title: ${recipe.title}`);
  lines.push(`// Mode: ${recipe.mode} · Viewport: ${recipe.viewport.width}×${recipe.viewport.height}@${recipe.viewport.deviceScaleFactor}x`);
  if (recipe.url) lines.push(`// Source: ${recipe.url}`);
  lines.push(`// Run:  npx playwright test ${slug(recipe.title)}.spec.ts`);
  lines.push("// Re-run on every version release to refresh the capture.");
  lines.push("");
  lines.push(`import { test, expect } from "@playwright/test";`);
  lines.push("");
  lines.push(`test("capture ${jsString(recipe.title)}", async ({ page }) => {`);
  lines.push(p(1) + `await page.setViewportSize({ width: ${recipe.viewport.width}, height: ${recipe.viewport.height} });`);
  const waitUntil =
    recipe.readiness.strategy === "network-idle"
      ? "networkidle"
      : recipe.readiness.strategy === "dom-content-loaded"
        ? "domcontentloaded"
        : "load";
  lines.push(p(1) + `await page.goto("${jsString(url ?? "")}", { waitUntil: "${waitUntil}", timeout: ${recipe.readiness.timeoutMs} });`);
  lines.push("");
  lines.push(p(1) + `// Wait for page readiness (${recipe.readiness.strategy}).`);
  if (recipe.readiness.strategy === "selector") {
    lines.push(
      p(1) +
        `await page.waitForSelector("${jsString(recipe.readiness.selector ?? "")}", { timeout: ${recipe.readiness.timeoutMs} });`,
    );
  } else if (recipe.readiness.strategy === "network-idle") {
    lines.push(p(1) + `await page.waitForLoadState("networkidle", { timeout: ${recipe.readiness.timeoutMs} });`);
  } else if (recipe.readiness.strategy === "manual") {
    lines.push(p(1) + `// Manual readiness — continue when the page looks ready.`);
  }
  lines.push(p(1) + `await page.waitForTimeout(${recipe.readiness.additionalDelayMs});`);
  lines.push("");
  lines.push(p(1) + `// Load lazy content by scrolling (mirrors the original capture).`);
  lines.push(p(1) + `await page.evaluate(async ({ step, delay, maxHeight }) => {`);
  lines.push(p(2) + `const vh = window.innerHeight;`);
  lines.push(p(2) + `let y = 0;`);
  lines.push(p(2) + `while (y < Math.min(document.body.scrollHeight, maxHeight)) {`);
  lines.push(p(3) + `window.scrollTo(0, y);`);
  lines.push(p(3) + `y += Math.max(200, vh * step);`);
  lines.push(p(3) + `await new Promise((r) => setTimeout(r, delay));`);
  lines.push(p(2) + `}`);
  lines.push(p(2) + `window.scrollTo(0, 0);`);
  lines.push(p(1) + `}, { step: ${recipe.scrolling.stepRatio}, delay: ${recipe.scrolling.delayMs}, maxHeight: ${recipe.scrolling.maximumHeight} });`);
  lines.push("");

  const output = `capture-${slug(recipe.title)}-${recipe.mode}`;
  if (recipe.mode === "element" && recipe.selector) {
    lines.push(p(1) + `// Element capture (${recipe.selector}).`);
    lines.push(p(1) + `await page.locator("${jsString(recipe.selector)}").first().scrollIntoViewIfNeeded();`);
    lines.push(p(1) + `await page.waitForTimeout(200);`);
    lines.push(p(1) + `await page.locator("${jsString(recipe.selector)}").first().screenshot({ path: "${output}.png" });`);
  } else if (recipe.mode === "region" && recipe.region) {
    lines.push(p(1) + `// Region capture at ${JSON.stringify(recipe.region)}.`);
    lines.push(p(1) + `await page.screenshot({`);
    lines.push(p(2) + `path: "${output}.png",`);
    lines.push(p(2) + `clip: ${JSON.stringify(recipe.region)},`);
    lines.push(p(1) + `});`);
  } else if (recipe.mode === "viewport") {
    lines.push(p(1) + `// Viewport capture.`);
    lines.push(p(1) + `await page.screenshot({ path: "${output}.png" });`);
  } else {
    lines.push(p(1) + `// Full-page capture.`);
    lines.push(p(1) + `await page.screenshot({ path: "${output}.png", fullPage: true });`);
  }
  lines.push("");
  lines.push(p(1) + `// The generated PNG is the new base layer. Re-apply the stored`);
  lines.push(p(1) + `// annotations/metadata from the .vcap project file — coordinates are stable.`);
  lines.push(p(1) + `expect(await page.title()).toBeTruthy();`);
  lines.push(`});`);
  lines.push("");
  return lines.join("\n");
}

/** Recipe as compact JSON (for sidecar export / agent consumption). */
export function recipeToJson(recipe: CaptureRecipe): string {
  return JSON.stringify(recipe, null, 2);
}

function slug(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 48) || "capture"
  );
}
