import { test, describe, before, after } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { createRequire } from "node:module";
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { dist } from "./helpers.mjs";

const W = await import(dist("tools/webtest.js"));
const tmp = (p) => mkdtempSync(join(tmpdir(), `stitap-webtest-${p}-`));

function fakeCtx(cwd, { approve = true } = {}) {
  const approvals = [];
  return {
    approvals,
    ctx: {
      rt: { cfg: { data: { web: { egress_allowlist: [] } } } },
      session: { id: "t" }, cwd, setCwd() {}, signal: new AbortController().signal, toolCallId: "x",
      progress() {}, async requestApproval(r) { approvals.push(r); return approve; }, async clarify() { return null; },
      depth: 0, budget: { remaining: 10 },
    },
  };
}

describe("webtest init", () => {
  test("scaffolds a Playwright Test project and never overwrites", async () => {
    const dir = tmp("init");
    mkdirSync(join(dir, "tests"), { recursive: true });
    writeFileSync(join(dir, "tests", "example.spec.ts"), "// mine\n");
    const { ctx, approvals } = fakeCtx(dir);
    const out = await W.webtestTool.handler({ action: "init", url: "http://localhost:5173", browsers: ["chromium", "webkit"] }, ctx);
    const text = typeof out === "string" ? out : out.content;
    assert.match(text, /Skipped .*tests\/example\.spec\.ts/);
    assert.equal(readFileSync(join(dir, "tests", "example.spec.ts"), "utf8"), "// mine\n");
    for (const f of ["package.json", "playwright.config.ts", "tests/pages/BasePage.ts", "README.md"]) assert.ok(existsSync(join(dir, f)), f);
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
    assert.ok(pkg.devDependencies["@playwright/test"]);
    const cfg = readFileSync(join(dir, "playwright.config.ts"), "utf8");
    for (const s of ["testDir: './tests'", "fullyParallel: true", "['json', { outputFile: 'test-results/results.json' }]", "['html', { open: 'never' }]",
      '"http://localhost:5173"', "screenshot: 'on'", "video: 'retain-on-failure'", "trace: 'retain-on-failure'", "name: 'chromium'", "name: 'webkit'"]) assert.ok(cfg.includes(s), s);
    assert.ok(!cfg.includes("name: 'firefox'"));
    assert.equal(approvals.length, 0, "no npm install without install_deps");
    // fresh dir gets the example spec too
    const dir2 = tmp("init2");
    await W.webtestTool.handler({ action: "init", dir: "sub", url: "https://example.com" }, fakeCtx(dir2).ctx);
    const spec = readFileSync(join(dir2, "sub", "tests", "example.spec.ts"), "utf8");
    assert.match(spec, /from '@playwright\/test'/);
    assert.match(spec, /toHaveTitle/);
    assert.match(spec, /BasePage/);
    rmSync(dir, { recursive: true, force: true }); rmSync(dir2, { recursive: true, force: true });
  });
});

describe("webtest spec generation", () => {
  test("steps become Playwright Test code", () => {
    const code = W.generateSpec("Login works", [
      { action: "fill", selector: "#user", value: "ann" },
      { action: "click", selector: 'role=button[name="Sign in"]' },
      { action: "press", key: "Enter" },
      { action: "select", selector: "select#c", value: "nl" },
      { action: "wait", ms: 200 },
      { action: "expect_text", text: "Welcome" },
      { action: "expect_text", selector: "#msg", text: "ok" },
      { action: "expect_url", url: "/home?x=1" },
      { action: "expect_title", text: "Home (beta)" },
      { action: "expect_visible", selector: "text=Logout" },
      { action: "screenshot", name: "after login" },
    ], { url: "http://localhost:3000/login", screenshotEachStep: true });
    assert.match(code, /^\/\/ Generated by stitaP webtest/);
    assert.match(code, /import \{ test, expect \} from '@playwright\/test';/);
    assert.match(code, /test\("Login works", async \(\{ page \}\) => \{/);
    assert.match(code, /await page\.goto\("http:\/\/localhost:3000\/login"\);/);
    assert.match(code, /await page\.locator\("#user"\)\.first\(\)\.fill\("ann"\);/);
    assert.ok(code.includes(`await page.locator("role=button[name=\\"Sign in\\"]").first().click();`));
    assert.match(code, /await page\.keyboard\.press\("Enter"\);/);
    assert.match(code, /selectOption\("nl"\)/);
    assert.match(code, /await page\.waitForTimeout\(200\);/);
    assert.match(code, /await expect\(page\.getByText\("Welcome"\)\.first\(\)\)\.toBeVisible\(\);/);
    assert.match(code, /await expect\(page\.locator\("#msg"\)\.first\(\)\)\.toContainText\("ok"\);/);
    assert.ok(code.includes(`toHaveURL(new RegExp("\\\\/home\\\\?x=1"))`), code);
    assert.ok(code.includes(`toHaveTitle(new RegExp("Home \\\\(beta\\\\)"))`));
    assert.match(code, /await page\.screenshot\(\{ path: test\.info\(\)\.outputPath\("step-12-screenshot-after-login\.png"\), fullPage: true \}\);/);
    assert.match(code, /outputPath\("step-02-fill\.png"\)/);
    assert.ok(code.trim().endsWith("});"));
    // balanced braces/parens as a cheap syntax sanity check
    const count = (c) => code.split(c).length - 1;
    assert.equal(count("{"), count("}")); assert.equal(count("("), count(")"));
    assert.throws(() => W.generateSpec("x", [{ action: "explode" }]), /unknown step action/);
  });
});

describe("webtest JSON report parser", () => {
  const fixture = {
    config: { rootDir: "/proj/tests" },
    suites: [{
      title: "example.spec.ts", file: "example.spec.ts", line: 0, column: 0, specs: [],
      suites: [{
        title: "smoke", file: "example.spec.ts", line: 3, column: 6,
        specs: [
          { title: "home loads", ok: true, tags: [], id: "a", file: "example.spec.ts", line: 4, column: 3,
            tests: [{ timeout: 30000, annotations: [], expectedStatus: "passed", projectId: "chromium", projectName: "chromium", status: "expected",
              results: [{ workerIndex: 0, status: "passed", duration: 812, errors: [], stdout: [], stderr: [], retry: 0, startTime: "2026-10-04T10:00:00.000Z",
                attachments: [{ name: "screenshot", contentType: "image/png", path: "/proj/test-results/artifacts/home/test-finished-1.png" }] }] }] },
          { title: "login fails", ok: false, tags: [], id: "b", file: "example.spec.ts", line: 9, column: 3,
            tests: [{ timeout: 30000, annotations: [], expectedStatus: "passed", projectId: "webkit", projectName: "webkit", status: "unexpected",
              results: [{ workerIndex: 1, status: "failed", duration: 5100, retry: 0, startTime: "2026-10-04T10:00:01.000Z", stdout: [], stderr: [],
                error: { message: "\u001b[31mError: expect(locator).toBeVisible() failed\u001b[39m\n\nLocator: getByText('Welcome')\nExpected: visible", stack: "..." },
                errors: [{ message: "Error: expect(locator).toBeVisible() failed" }],
                attachments: [
                  { name: "screenshot", contentType: "image/png", path: "/proj/test-results/artifacts/login-webkit/test-failed-1.png" },
                  { name: "video", contentType: "video/webm", path: "/proj/test-results/artifacts/login-webkit/video.webm" },
                  { name: "trace", contentType: "application/zip", path: "/proj/test-results/artifacts/login-webkit/trace.zip" },
                  { name: "stdout-ish", contentType: "text/plain", body: "aGk=" },
                ] }] }] },
          { title: "later", ok: true, tags: [], id: "c", file: "example.spec.ts", line: 20, column: 3,
            tests: [{ projectName: "chromium", status: "skipped", expectedStatus: "skipped", results: [{ status: "skipped", attachments: [] }] }] },
        ],
      }],
    }],
    errors: [],
    stats: { startTime: "2026-10-04T10:00:00.000Z", duration: 6123.4, expected: 1, skipped: 1, unexpected: 1, flaky: 0 },
  };
  test("totals, failing titles, errors and attachment paths", () => {
    const r = W.parseJsonReport(fixture, "/proj");
    assert.deepEqual([r.total, r.expected, r.unexpected, r.flaky, r.skipped, r.durationMs], [3, 1, 1, 0, 1, 6123]);
    assert.equal(r.failures.length, 1);
    const f = r.failures[0];
    assert.equal(f.title, "smoke › login fails");
    assert.equal(f.project, "webkit");
    assert.match(f.error, /^Error: expect\(locator\)\.toBeVisible\(\) failed/);
    assert.ok(!f.error.includes("\u001b"));
    assert.deepEqual(f.attachments.map((a) => a.name), ["screenshot", "video", "trace"]);
    const text = W.formatReport(r, "results.json");
    assert.match(text, /FAILED — 3 tests: 1 passed, 1 failed, 0 flaky, 1 skipped/);
    assert.match(text, /trace: \/proj\/test-results\/artifacts\/login-webkit\/trace\.zip/);
  });
  test("report action reads test-results/results.json", async () => {
    const dir = tmp("report");
    mkdirSync(join(dir, "test-results"), { recursive: true });
    writeFileSync(join(dir, "test-results", "results.json"), JSON.stringify(fixture));
    const out = await W.webtestTool.handler({ action: "report", dir }, fakeCtx(dir).ctx);
    assert.match(String(out), /smoke › login fails \[webkit\]/);
    const none = await W.webtestTool.handler({ action: "report" }, fakeCtx(tmp("empty")).ctx);
    assert.match(String(none), /No results/);
    rmSync(dir, { recursive: true, force: true });
  });
  test("run without a local @playwright/test explains what to do", async () => {
    const out = await W.webtestTool.handler({ action: "run" }, fakeCtx(tmp("run")).ctx);
    assert.match(String(out), /action=init with install_deps=true/);
  });
});

// ---------- browser end-to-end ----------

function chromiumReady() {
  try {
    const req = createRequire(import.meta.url);
    const pw = req("playwright-core");
    return existsSync(pw.chromium.executablePath()) ? true : `chromium not downloaded (${pw.chromium.executablePath()}) — run: node node_modules/playwright-core/cli.js install chromium`;
  } catch (e) { return `playwright-core not installed: ${e.message}`; }
}
const ready = chromiumReady();
if (ready !== true) console.log(`# skipping webtest browser tests: ${ready}`);

const PAGE = `<!doctype html><html><head><title>Demo App</title></head><body>
<h1>Demo</h1>
<form onsubmit="event.preventDefault()"><label>Name <input id="name" name="name"></label>
<select id="color"><option value="r">Red</option><option value="g">Green</option></select>
<label><input type="checkbox" id="agree"> agree</label></form>
<button id="reveal" onclick="document.getElementById('out').textContent='Hello, '+document.getElementById('name').value+'!'">Reveal</button>
<p id="out"></p>
<a href="/about">About us</a>
</body></html>`;

describe("webtest scenario (chromium)", { skip: ready === true ? false : String(ready) }, () => {
  let server, base;
  before(async () => {
    server = createServer((req, res) => {
      res.setHeader("content-type", "text/html");
      res.end(req.url.startsWith("/about") ? "<!doctype html><title>About</title><h2>About page</h2>" : PAGE);
    });
    await new Promise((r) => server.listen(0, "127.0.0.1", r));
    base = `http://127.0.0.1:${server.address().port}`;
  });
  after(async () => { server.closeAllConnections?.(); await new Promise((r) => server.close(r)); });

  test("passing scenario saves screenshots, video, trace, report and spec", async () => {
    const dir = tmp("scn");
    const r = await W.runScenario({
      dir, name: "Reveal greeting", url: base,
      steps: [
        { action: "goto", url: "/" },
        { action: "fill", selector: "#name", value: "Ann" },
        { action: "select", selector: "#color", value: "Green" },
        { action: "check", selector: "#agree" },
        { action: "click", selector: 'role=button[name="Reveal"]' },
        { action: "expect_text", selector: "#out", text: "Hello, Ann!" },
        { action: "expect_title", text: "Demo" },
        { action: "screenshot", name: "greeting" },
        { action: "click", selector: "text=About us" },
        { action: "expect_url", url: "/about" },
        { action: "expect_visible", selector: "h2" },
      ],
    });
    assert.equal(r.ok, true, r.summary);
    assert.equal(r.steps.length, 11);
    const files = readdirSync(r.outDir);
    const pngs = files.filter((f) => f.endsWith(".png"));
    assert.equal(pngs.length, 11, files.join(","));
    assert.ok(files.includes("step-08-screenshot.png"));
    for (const p of pngs) assert.deepEqual([...readFileSync(join(r.outDir, p)).subarray(0, 8)], [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], p);
    assert.ok(r.videoPath?.endsWith(".webm") && existsSync(r.videoPath), "video");
    assert.ok(readFileSync(r.videoPath).length > 1000, "video has content");
    assert.ok(r.tracePath && existsSync(r.tracePath), "trace");
    assert.equal(readFileSync(r.tracePath).subarray(0, 2).toString(), "PK");
    const md = readFileSync(r.reportPath, "utf8");
    assert.match(md, /Result: \*\*PASSED\*\*/);
    assert.match(md, /\| 6 \| expect_text \| #out ∋ "Hello, Ann!" \| pass \|/);
    assert.match(md, /\[step-01-goto\.png\]\(step-01-goto\.png\)/);
    const spec = readFileSync(r.specPath, "utf8");
    assert.ok(r.specPath.endsWith(join("tests", "reveal-greeting.spec.ts")));
    assert.match(spec, /await page\.goto\("\/"\);/);
    assert.match(spec, /toContainText\("Hello, Ann!"\)/);
    assert.match(r.summary, /PASSED — 11\/11 steps/);
    rmSync(dir, { recursive: true, force: true });
  });

  test("failing scenario stops at the failed step and keeps evidence", async () => {
    const dir = tmp("scnfail");
    const { ctx } = fakeCtx(dir);
    const out = await W.webtestTool.handler({
      action: "scenario", name: "missing text", url: base, video: false, step_timeout_ms: 1500,
      steps: [
        { action: "click", selector: "#reveal" },
        { action: "expect_text", text: "This text is not on the page" },
        { action: "click", selector: "#never" },
      ],
    }, ctx);
    assert.equal(out.meta.ok, false);
    assert.match(out.content, /FAILED — 2\/4 steps passed/);
    assert.match(out.content, /Failed at step 3 \(expect_text/);
    assert.match(out.content, /This text is not on the page/);
    const files = readdirSync(out.meta.outDir);
    assert.ok(files.includes("step-03-expect_text-failed.png"), files.join(","));
    assert.ok(!files.some((f) => f.startsWith("step-04")));
    assert.ok(files.includes("trace.zip"));
    assert.ok(!files.some((f) => f.endsWith(".webm")), "video disabled");
    const md = readFileSync(out.meta.report, "utf8");
    assert.match(md, /## Failure/);
    assert.match(md, /!\[failure screenshot\]\(step-03-expect_text-failed\.png\)/);
    // report action picks the newest scenario report
    const rep = await W.webtestTool.handler({ action: "report" }, ctx);
    assert.match(String(rep), /Latest scenario report: .*report\.md/);
    rmSync(dir, { recursive: true, force: true });
  });

  test("egress allowlist blocks navigation", async () => {
    const dir = tmp("egress");
    const r = await W.runScenario({ dir, url: base, steps: [], allowlist: ["example.com"], video: false, trace: false });
    assert.equal(r.ok, false);
    assert.match(r.error, /egress_allowlist/);
    rmSync(dir, { recursive: true, force: true });
  });
});
