/**
 * stitaP Analytics — Export to Reporting Platforms
 *
 * Export columnar query results to formats compatible with:
 * - Microsoft Power BI (.pbix-compatible CSV, DAX template)
 * - Microsoft Excel (.xlsx via xlsx library pattern, .csv)
 * - Google Sheets (CSV with formatting metadata)
 * - Tableau (.hyper-compatible TSV, .twbx manifest)
 *
 * All exports run entirely in-browser. No server needed.
 */

import { type Table, type Column, toCSV, toJSON, type Scalar } from "./columnar";

// ─── Export Formats ─────────────────────────────────────────────────────────

export interface ExportResult {
  filename: string;
  mimeType: string;
  content: string;
  encoding: "utf-8" | "base64";
  metadata: {
    format: string;
    rows: number;
    columns: number;
    generatedAt: string;
  };
}

// ─── Power BI Export ────────────────────────────────────────────────────────

/**
 * Export a table as a Power BI-compatible CSV.
 * Includes metadata header comments that Power BI's "Get Data > Text/CSV" reads.
 */
export function exportForPowerBI(table: Table): ExportResult {
  const csv = toCSV(table);

  // Power BI metadata header
  const metaLines = [
    "# Power BI Import File",
    "# Format: CSV with metadata header",
    "# Generated by stitaP Analytics Engine",
    `# Table: ${table.name}`,
    `# Rows: ${table.rowCount}`,
    `# Columns: ${table.colCount}`,
    `# Generated: ${new Date().toISOString()}`,
    "# Instructions: Import this CSV into Power BI Desktop via Get Data > Text/CSV",
    "# The metadata lines above are ignored by Power BI's CSV parser",
    "",
  ];

  return {
    filename: `${sanitizeFilename(table.name)}_powerbi.csv`,
    mimeType: "text/csv",
    content: metaLines.join("\n") + csv,
    encoding: "utf-8",
    metadata: {
      format: "powerbi-csv",
      rows: table.rowCount,
      columns: table.colCount,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * Generate a DAX measure template for the table.
 */
export function generateDAXTemplate(table: Table): ExportResult {
  const colDefs = table.schema();
  const measures: string[] = [];

  measures.push(`// DAX Measures for table: ${table.name}`);
  measures.push(`// Import this as a measure file in Power BI Model view`);
  measures.push("");

  // Auto-generate sum/avg/count measures for numeric columns
  for (const col of colDefs) {
    if (col.dtype === "f64" || col.dtype === "i32" || col.dtype === "f32" || col.dtype === "i64") {
      measures.push(`Total ${col.name} = SUM('${table.name}'[${col.name}])`);
      measures.push(`Average ${col.name} = AVERAGE('${table.name}'[${col.name}])`);
      measures.push(`Min ${col.name} = MIN('${table.name}'[${col.name}])`);
      measures.push(`Max ${col.name} = MAX('${table.name}'[${col.name}])`);
      measures.push(`Count ${col.name} = COUNT('${table.name}'[${col.name}])`);
      measures.push("");
    }
  }

  measures.push(`Total Rows = COUNTROWS('${table.name}')`);

  return {
    filename: `${sanitizeFilename(table.name)}_dax_measures.dax`,
    mimeType: "text/plain",
    content: measures.join("\n"),
    encoding: "utf-8",
    metadata: {
      format: "dax",
      rows: measures.length,
      columns: 1,
      generatedAt: new Date().toISOString(),
    },
  };
}

// ─── Excel Export ───────────────────────────────────────────────────────────

/**
 * Export a table as a CSV suitable for Excel import.
 * Includes Excel-compatible formatting hints.
 */
export function exportForExcel(table: Table): ExportResult {
  const csv = toCSV(table);

  // Excel BOM + metadata
  const bom = "\uFEFF"; // UTF-8 BOM for Excel
  const metaLines = [
    `"Table: ${table.name}"`,
    `"Generated by stitaP Analytics Engine"`,
    `"${table.rowCount} rows, ${table.colCount} columns"`,
    "",
  ];

  return {
    filename: `${sanitizeFilename(table.name)}_excel.csv`,
    mimeType: "text/csv; charset=utf-8",
    content: bom + metaLines.join("\n") + csv,
    encoding: "utf-8",
    metadata: {
      format: "excel-csv",
      rows: table.rowCount,
      columns: table.colCount,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * Generate an Excel-compatible XML Spreadsheet (SSML format).
 * This can be opened directly in Excel without any conversion.
 */
export function exportForExcelXML(table: Table): ExportResult {
  const rows: string[] = [];
  const colDefs = table.schema();

  rows.push('<?xml version="1.0"?>');
  rows.push('<?mso-application progid="Excel.Sheet"?>');
  rows.push('<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"');
  rows.push(' xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">');

  // Styles
  rows.push('<Styles>');
  rows.push('<Style ss:ID="header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#4472C4" ss:Pattern="Solid"/></Style>');
  rows.push('<Style ss:ID="number"><NumberFormat ss:Format="#,##0.00"/></Style>');
  rows.push('</Styles>');

  rows.push('<Worksheet ss:Name="' + escapeXml(table.name) + '">');
  rows.push('<Table>');

  // Header row
  rows.push('<Row>');
  for (const col of colDefs) {
    rows.push(`<Cell ss:StyleID="header"><Data ss:Type="String">${escapeXml(col.name)}</Data></Cell>`);
  }
  rows.push('</Row>');

  // Data rows
  for (let i = 0; i < table.rowCount; i++) {
    rows.push('<Row>');
    for (const col of colDefs) {
      const dbCol = table.column(col.name);
      const val = dbCol ? dbCol.get(i) : null;
      const type = (col.dtype === "i32" || col.dtype === "i64" || col.dtype === "f32" || col.dtype === "f64") ? "Number" : "String";
      rows.push(`<Cell><Data ss:Type="${type}">${escapeXml(String(val ?? ""))}</Data></Cell>`);
    }
    rows.push('</Row>');
  }

  rows.push('</Table>');
  rows.push('</Worksheet>');
  rows.push('</Workbook>');

  return {
    filename: `${sanitizeFilename(table.name)}_excel.xml`,
    mimeType: "application/vnd.ms-excel",
    content: rows.join("\n"),
    encoding: "utf-8",
    metadata: {
      format: "excel-xml",
      rows: table.rowCount,
      columns: table.colCount,
      generatedAt: new Date().toISOString(),
    },
  };
}

// ─── Google Sheets Export ───────────────────────────────────────────────────

/**
 * Export for Google Sheets import.
 * Produces CSV with a schema metadata block for Google Sheets API.
 */
export function exportForGoogleSheets(table: Table): ExportResult {
  const csv = toCSV(table);
  const colDefs = table.schema();

  // Google Sheets compatible metadata
  const metadata = {
    schema: colDefs.map(c => ({ name: c.name, type: c.dtype })),
    table: table.name,
    generated: new Date().toISOString(),
    engine: "stitaP Analytics",
  };

  const metaLines = [
    `<!-- Google Sheets Import Metadata`,
    JSON.stringify(metadata, null, 2),
    `-->`,
    "",
  ];

  return {
    filename: `${sanitizeFilename(table.name)}_sheets.csv`,
    mimeType: "text/csv",
    content: metaLines.join("\n") + csv,
    encoding: "utf-8",
    metadata: {
      format: "google-sheets-csv",
      rows: table.rowCount,
      columns: table.colCount,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * Generate a Google Sheets formula template for analysis.
 */
export function generateSheetsFormulas(table: Table): ExportResult {
  const colDefs = table.schema();
  const formulas: string[] = [];

  formulas.push(`// Google Sheets Formula Templates for: ${table.name}`);
  formulas.push(`// Paste into cells after importing the CSV data`);
  formulas.push("");

  let colLetter = "A";
  for (const col of colDefs) {
    if (col.dtype === "f64" || col.dtype === "i32" || col.dtype === "f32" || col.dtype === "i64") {
      formulas.push(`// ${col.name} (Column ${colLetter})`);
      formulas.push(`=SUM(${colLetter}2:${colLetter}1000)`);
      formulas.push(`=AVERAGE(${colLetter}2:${colLetter}1000)`);
      formulas.push(`=MIN(${colLetter}2:${colLetter}1000)`);
      formulas.push(`=MAX(${colLetter}2:${colLetter}1000)`);
      formulas.push(`=COUNT(${colLetter}2:${colLetter}1000)`);
      formulas.push("");
    }
    colLetter = nextColLetter(colLetter);
  }

  return {
    filename: `${sanitizeFilename(table.name)}_sheets_formulas.txt`,
    mimeType: "text/plain",
    content: formulas.join("\n"),
    encoding: "utf-8",
    metadata: {
      format: "google-sheets-formulas",
      rows: formulas.length,
      columns: 1,
      generatedAt: new Date().toISOString(),
    },
  };
}

// ─── Tableau Export ─────────────────────────────────────────────────────────

/**
 * Export a table as a Tableau-compatible TSV.
 * Tableau reads TSV natively and this format preserves type information.
 */
export function exportForTableau(table: Table): ExportResult {
  const colDefs = table.schema();
  const lines: string[] = [];

  // Tableau TSV header with type annotations
  const header = colDefs.map(c => `${c.name} (${c.dtype})`).join("\t");
  lines.push(header);

  // Data rows
  for (let i = 0; i < table.rowCount; i++) {
    const row = colDefs.map(c => {
      const col = table.column(c.name);
      const val = col ? col.get(i) : null;
      return val === null ? "" : String(val);
    });
    lines.push(row.join("\t"));
  }

  return {
    filename: `${sanitizeFilename(table.name)}_tableau.tsv`,
    mimeType: "text/tab-separated-values",
    content: lines.join("\n"),
    encoding: "utf-8",
    metadata: {
      format: "tableau-tsv",
      rows: table.rowCount,
      columns: table.colCount,
      generatedAt: new Date().toISOString(),
    },
  };
}

/**
 * Generate a Tableau workbook manifest (.twb XML) for auto-import.
 */
export function exportForTableauManifest(table: Table): ExportResult {
  const colDefs = table.schema();
  const columns = colDefs.map(c => {
    const typeMap: Record<string, string> = {
      i32: "integer", i64: "integer", f32: "real", f64: "real",
      bool: "boolean", str: "string", date: "date", ts: "datetime",
    };
    return `<column caption="${escapeXml(c.name)}" datatype="${typeMap[c.dtype] || "string"}" name="[${escapeXml(c.name)}]" />`;
  });

  const manifest = `<?xml version='1.0' encoding='utf-8' ?>
<workbook source-build='Tableau Desktop' version='18.1'>
  <datasources>
    <datasource caption='${escapeXml(table.name)}' inline='true' version='2'>
      <column caption='Table Name' datatype='string' name='[Table Name]' role='dimension' type='nominal' />
      ${columns.join("\n      ")}
      <rows>
        <row>${
          colDefs.map(c => `<value column-name="[${escapeXml(c.name)}]">${escapeXml(String(colDefs.indexOf(c)))}</value>`).join(" ")
        }</row>
      </rows>
    </datasource>
  </datasources>
</workbook>`;

  return {
    filename: `${sanitizeFilename(table.name)}_tableau.twb`,
    mimeType: "application/vnd.tableau",
    content: manifest,
    encoding: "utf-8",
    metadata: {
      format: "tableau-twb",
      rows: table.rowCount,
      columns: table.colCount,
      generatedAt: new Date().toISOString(),
    },
  };
}

// ─── Universal Export ───────────────────────────────────────────────────────

export type ExportFormat =
  | "powerbi" | "powerbi-dax"
  | "excel" | "excel-xml"
  | "sheets" | "sheets-formulas"
  | "tableau" | "tableau-manifest"
  | "csv" | "json";

/**
 * Universal export function — choose format and get the export.
 */
export function exportTable(table: Table, format: ExportFormat): ExportResult {
  switch (format) {
    case "powerbi": return exportForPowerBI(table);
    case "powerbi-dax": return generateDAXTemplate(table);
    case "excel": return exportForExcel(table);
    case "excel-xml": return exportForExcelXML(table);
    case "sheets": return exportForGoogleSheets(table);
    case "sheets-formulas": return generateSheetsFormulas(table);
    case "tableau": return exportForTableau(table);
    case "tableau-manifest": return exportForTableauManifest(table);
    case "csv": return { filename: `${sanitizeFilename(table.name)}.csv`, mimeType: "text/csv", content: toCSV(table), encoding: "utf-8", metadata: { format: "csv", rows: table.rowCount, columns: table.colCount, generatedAt: new Date().toISOString() } };
    case "json": return { filename: `${sanitizeFilename(table.name)}.json`, mimeType: "application/json", content: JSON.stringify(toJSON(table), null, 2), encoding: "utf-8", metadata: { format: "json", rows: table.rowCount, columns: table.colCount, generatedAt: new Date().toISOString() } };
  }
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "_").substring(0, 50);
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function nextColLetter(letter: string): string {
  const last = letter.charCodeAt(letter.length - 1);
  if (last < 90) { // Z
    return letter.slice(0, -1) + String.fromCharCode(last + 1);
  }
  return "A" + letter;
}
