/**
 * Foundations - documentation from absolute first principles.
 *
 * Written for readers who use software daily but have never worked with
 * AI models, agents, or developer tooling. Every term is defined the
 * first time it appears, every chapter explains WHY before HOW, and each
 * chapter builds on the previous one. Microsoft Style: active voice,
 * present tense, second person, one idea per sentence.
 *
 * These chapters form Part I of the manual; core chapters follow.
 */

import type { PdfChapter } from "./pdf";

const b = {
  p: (text: string) => ({ type: "p" as const, text }),
  h2: (text: string) => ({ type: "h2" as const, text }),
  h3: (text: string) => ({ type: "h3" as const, text }),
  bullet: (text: string) => ({ type: "bullet" as const, text }),
  note: (text: string) => ({ type: "note" as const, text }),
  code: (...lines: string[]) => ({ type: "code" as const, lines }),
};

export const FOUNDATIONS_CHAPTERS: PdfChapter[] = [
  // ─── F1 ────────────────────────────────────────────────────────
  {
    title: "Start here",
    blocks: [
      b.p("This part of the manual assumes you use a computer every day. It does not assume you know what an AI model is, what an agent is, or what any of the words on this platform mean. Each chapter introduces a small number of ideas and uses them in the next chapter."),
      b.h2("The path through Part I"),
      b.p("Read the chapters in order the first time. Each one needs only the ones before it."),
      b.bullet("Words you will meet - the vocabulary used everywhere else."),
      b.bullet("How computers run programs - the ground everything stands on."),
      b.bullet("What an AI model actually is - a precise definition, and why every failure follows from it."),
      b.bullet("Where language models came from - the predecessors, the transformers paper, and how applications evolved."),
      b.bullet("How models are made - datasets, training, fine-tuning, attention, and the hardware libraries."),
      b.bullet("Tokens, context windows, and cost - limits, which activities burn the most tokens, useful-versus-spent arithmetic, and when FP16 out-generates quantized."),
      b.bullet("Quantization - how big models fit on small machines, including the extreme 1-, 2-, and 3-bit builds: when they work, when they do not, and how they are made."),
      b.bullet("What makes software an agent - loops, tools, and decisions."),
      b.bullet("What a tool harness is - where stitaP fits."),
      b.bullet("Your first session, first swarm, and first governed project - three complete walkthroughs."),
      b.note("Nothing in this part requires programming. You can perform every walkthrough by clicking buttons in the web interface."),
    ],
  },
  // ─── F2 ────────────────────────────────────────────────────────
  {
    title: "Words you will meet",
    blocks: [
      b.p("Documentation fails when it uses a word before defining it. This chapter defines every word that appears throughout stitaP's documentation. Short definitions appear here; later chapters expand each one with examples."),
      b.h2("The AI words"),
      b.bullet("Model. A computer file containing patterns learned from enormous amounts of text, plus the program that runs those patterns. You feed it text; it produces text."),
      b.bullet("LLM (large language model). A model trained on so much text that it can hold conversations, answer questions, and write documents. 'Large' refers to its size; some LLMs are huge, others are small enough to fit on a phone."),
      b.bullet("SLM (small language model). A deliberately smaller LLM that runs on ordinary hardware. Slower to reason deeply, but private, free to run, and always available offline."),
      b.bullet("GGUF. A file format for storing models so that everyday programs can run them. Think of it as '.MP4 but for AI models': a standard container everyone agrees on."),
      b.bullet("Token. A chunk of text - often a word piece - which is how models read and write. Models do not see letters; they see tokens. Rough rule: one token is about three-quarters of an English word."),
      b.bullet("Context window. The maximum number of tokens a model can consider at once. It is the model's working memory. When people say a model has '4K context', they mean roughly 4,000 tokens fit in memory."),
      b.bullet("Inference. The act of running a model to get output. Training built the model; inference uses it."),
      b.bullet("Quantization. Storing model numbers with less precision so the model takes less memory and runs faster, at a small quality cost. Chapter F6 explains it fully."),
      b.h2("The agent words"),
      b.bullet("Agent. Software that decides what to do next by asking a model, then does it using tools, then repeats until finished. A chat window answers once; an agent works toward a goal over many steps."),
      b.bullet("Tool. A named capability an agent can call - take a screenshot, search documents, click a button. Tools give agents hands, not just a mouth."),
      b.bullet("Harness. The surrounding system that lets agents run safely: it stores tools, controls permissions, tracks spending of tokens, and records what happened. stitaP is a harness."),
      b.bullet("Swarm. Several agents working together on one goal with defined roles, like workers on a job site."),
      b.bullet("Session. One working conversation between you and configured capabilities. You decide what is available by checking modules on or off."),
      b.bullet("Module. A packaged bundle of related tools plus instructions. Checking a module on adds its abilities to your session; checking it off removes them."),
      b.bullet("Kanban board. A board with columns such as To Do, Doing, and Done. Work items move across it. Agents use these boards exactly as human teams do."),
      b.bullet("Checkpoint. A saved snapshot of progress. If anything crashes, work resumes from the last checkpoint instead of starting over."),
      b.h2("The engineering words"),
      b.bullet("Repository. The folder containing all of stitaP's source files and their history."),
      b.bullet("Typecheck. An automated review that catches mistakes in the code before running it."),
      b.bullet("Smoke test. A quick suite of checks confirming that each part still works after changes."),
      b.bullet("Git. The standard system for recording changes to files, used here so agents save their work the way human developers do."),
      b.bullet("Ticket. A work item in a tracking system such as Jira, describing something to be done and recording what was done."),
      b.note("When any later chapter uses one of these words without explaining it, this page is the explanation. The glossary at the end of the manual repeats every definition alphabetically."),
    ],
  },
  // ─── F3 ────────────────────────────────────────────────────────
  {
    title: "How computers run programs",
    blocks: [
      b.p("You need three ideas from this chapter: memory, storage, and processing. Everything about model sizes and speed later in this manual comes back to them."),
      b.h2("Storage holds files; memory holds work"),
      b.p("Storage (a disk) keeps files when the power is off. Memory (RAM) holds the data a program is using right now, and empties when power goes off. A model lives on storage as a multi-gigabyte file. Before a model can answer anything, the computer must load it into memory - and the model must fit."),
      b.h2("This is why size matters"),
      b.p("If your machine has 8 GB of memory and the operating system needs 3 GB, about 5 GB remain for everything else. A model that needs 7 GB cannot load. No setting fixes this. Your options are a smaller model or a lower-precision copy of the same model - which is exactly what quantization provides in chapter F6."),
      b.h2("Processing turns memory into answers"),
      b.p("The processor performs the actual computation. Three kinds matter here:"),
      b.bullet("CPU. The general-purpose processor every computer has. Always works; not the fastest for models."),
      b.bullet("GPU. The graphics processor, excellent at the repeated math models need. Faster than CPU when present."),
      b.bullet("NPU. A newer chip designed specifically for AI math, found on recent laptops and phones. Often best efficiency per watt rather than raw speed."),
      b.h2("Why stitaP measures instead of guessing"),
      b.p("Which processor wins depends on your specific chip, driver version, and workload. Rather than assuming, stitaP tries each available option with a short test and picks the fastest measured result. That measurement loop is the router described in chapter 4 of the core manual."),
      b.h2("Cores and threads"),
      b.p("A modern CPU contains several cores - independent mini-processors. Operating systems also report threads, which share cores. Running more compute workers than physical cores slows things down, which is why stitaP sizes swarms by physical cores, never by the larger thread count the OS advertises."),
    ],
  },
  // ─── F4 ────────────────────────────────────────────────────────
  {
    title: "What an AI model actually is",
    blocks: [
      b.p("Strip away the mystique and a language model is a prediction machine. Give it text, and it produces the most plausible continuation of that text, one token at a time. This chapter defines that sentence precisely, because every behavior - good and bad - follows from it."),
      b.h2("A precise definition"),
      b.p("A language model is a function that takes a sequence of tokens and assigns a probability to every possible next token. 'Probability' here means exactly what it means in statistics: a number between 0 and 1 expressing how likely that continuation is, given everything the model saw in training and everything in the current input. Generation works by repeatedly picking a next token according to those probabilities, appending it, and predicting again. Nothing more mysterious happens anywhere inside."),
      b.p("The model's internal numbers - its parameters - are the accumulated result of training. Each parameter is a weight in a vast equation that converts 'the text so far' into 'the distribution over next tokens'. A 7B model is an equation with seven billion adjustable numbers. Training set them; inference only reads them."),
      b.p("Three consequences of this definition are worth memorizing now, because they explain almost everything later:"),
      b.bullet("The model computes probabilities; it does not look facts up. Any 'knowledge' is baked into the weights as statistical tendencies."),
      b.bullet("The model sees only its input. If a fact is not in the weights or in the prompt, the model cannot use it - it can only guess plausibly."),
      b.bullet("Generation is one token at a time. The model never plans a whole paragraph in one step; each token conditions on all previous ones."),
      b.h2("Where the ability comes from"),
      b.p("Before you ever received a model, its authors let it practice on enormous amounts of text - books, articles, code, conversations. Billions of times, the training process showed the model a passage with the next word hidden and adjusted its internal parameters based on its guess. After training, those billions of adjustments are the entire product. There is no database of facts inside and no lookup table. Just tuned numbers that happen to make good predictions."),
      b.h2("What this explains"),
      b.p("Understanding the prediction nature explains behaviors you will notice immediately:"),
      b.bullet("Confident mistakes. The model predicts plausible text, not verified truth. Wrong-but-fluent answers are possible."),
      b.bullet("Prompt sensitivity. Because output continues your input, rephrasing the input genuinely changes the prediction."),
      b.bullet("No built-in knowledge of your company. The model never saw your internal documents. If you want it to use them, software must place them into the prompt - which is what the knowledge base module does."),
      b.bullet("Repetition limits. Ask for very long output and quality drifts. Short, structured requests predict better."),
      b.h2("Why models fail, with the concept behind each failure"),
      b.p("Failures stop being mysterious once you trace each one back to the definition. These are the failure modes you will actually meet, and the conceptual fact that causes each:"),
      b.bullet("Hallucination (invented facts). Cause: the model predicts plausible text, not verified truth. A wrong answer can be exactly as statistically fluent as a right one, because fluency is what training rewarded. Mitigation: ground answers in retrieved documents (chapter 14) and require citations or tool-verified evidence."),
      b.bullet("Losing the thread in long conversations. Cause: the context window is finite. Once history exceeds it, the oldest tokens drop out of view entirely - the model is not forgetting, the text is literally absent. Mitigation: bounded sessions, digests instead of transcripts, retrieval instead of full history."),
      b.bullet("Ignoring instructions. Cause: instructions are tokens competing for attention with everything else in the window; long, cluttered prompts dilute them. Mitigation: short system prompts (why the SLM Minimal preset exists) and structured output formats the parser can check."),
      b.bullet("Inconsistency across rephrasing. Cause: different wordings are genuinely different inputs to a probability function; the distribution shifts with them. Mitigation: fixed templates for automation paths, creative phrasing only where variety helps."),
      b.bullet("Degradation after quantization. Cause: fewer digits per parameter is a lossy compression of the training result; rare distinctions blur first. Mitigation: stay at 4-bit or above (chapter F6), quantize only from original weights."),
      b.bullet("Confident wrong code that fails tests. Cause: the model predicts code that looks like correct code - naming, shape, and style all match - without executing anything. Mitigation: never accept unexecuted code; the verification gates in chapters 12 and 19 exist for exactly this."),
      b.note("The pattern across every failure: the model did exactly what its definition says - predicted plausible text - and the harness's job is to add the ground truth, the memory bounds, and the verification that prediction alone cannot provide."),
      b.h2("Instructions are just prompts"),
      b.p("A system prompt is the opening text placed before every conversation that sets behavior: 'You are a careful assistant that replies in JSON.' The model treats it as the start of the document to continue, so it tends to keep following the style. Session modules work by adding their instructions to this opening text - which is why every checked module has a token cost."),
      b.h2("Temperature and determinism"),
      b.p("Models can pick predictions strictly (same input, same output) or sample creatively. stitaP defaults to strict settings for tool calls and structured output, because automation must be repeatable. Creative sampling stays available for writing tasks."),
      b.h2("Small versus large models"),
      b.p("Large models predict better and reason further, but demand server-class hardware. Small models - the SLMs this harness targets - fit in a few gigabytes, respond instantly, and never leak your data because they never leave your machine. The design philosophy of this platform is to give small models narrow, well-defined jobs with structured prompts and verification around them, rather than hoping one giant model handles everything unaided."),
    ],
  },
  // ─── F5 ────────────────────────────────────────────────────────
  {
    title: "Where language models came from",
    blocks: [
      b.p("Chapter F4 defined what a model is. This chapter explains where the idea came from, why a 2017 research paper changed everything, and how a research curiosity became the center of the technology industry. Knowing this history answers a fair question: if prediction is such an old idea, why did everyone suddenly care?"),
      b.h2("The predecessors, in order"),
      b.p("Each generation below solved the previous generation's central limitation. Reading the list top to bottom is reading the problems disappear one by one."),
      b.bullet("Rule-based systems (1960s-1980s). ELIZA and its relatives followed hand-written pattern rules: see 'I feel sad', reply about sadness. Limitation: rules never covered real language; the illusion collapsed quickly."),
      b.bullet("N-gram models (1980s-2000s). The first statistical predictors: estimate the next word from the previous one or two words, counted over a corpus. This is the direct ancestor of modern models - same prediction task, tiny window. Limitation: two words of context cannot capture what a sentence means."),
      b.bullet("Word embeddings (2013, word2vec and successors). Words became vectors of numbers, so 'king' and 'queen' ended up mathematically close. Meaning finally had geometry. Limitation: one vector per word regardless of context - 'bank' of a river and 'bank' of money looked identical."),
      b.bullet("Recurrent networks: RNNs and LSTMs (1997-2017). Neural networks that read a sentence one word at a time, carrying a running summary forward. LSTMs added gates that let them remember longer stretches. These powered the first decent translation and speech systems. Limitation: reading word-by-word is inherently sequential, so training could not scale to web-sized data, and long-range connections still faded."),
      b.bullet("Sequence-to-sequence with attention (2014-2015). For translation, researchers let the decoder 'look back' at all input words with learned weights instead of relying on one compressed summary vector. Attention began as a patch on recurrent models - and turned out to be the main event."),
      b.h2("The transformers paper"),
      b.p("In 2017, eight researchers at Google published 'Attention Is All You Need'. The title was a claim: keep the attention mechanism, delete the recurrent network entirely. The resulting architecture - the Transformer - reads every token in parallel and lets every token directly attend to every other token, with the relevance weights learned during training."),
      b.p("Why this mattered so much, stated plainly: GPUs earn their keep on massive parallel work. Recurrent models, reading one word at a time, wasted that property. Transformers are parallel by construction, so doubling the hardware genuinely doubled the training throughput. For the first time, model quality scaled smoothly with compute, data, and parameters - the observation later formalized as scaling laws. Once quality became a purchasable quantity, investment followed."),
      b.p("The lineage after the paper runs through three families: BERT (2018) read text bidirectionally for understanding tasks; the GPT series (2018 onward) predicted forward and grew steadily; and ChatGPT (2022) - a GPT model tuned to follow instructions conversationally - carried the technology from research papers into general public awareness almost overnight."),
      b.h2("Why LLMs became the person of interest in the tech industry"),
      b.bullet("Generality. One architecture, trained on text alone, turned out to write code, translate, summarize, and reason - tasks that previously needed a separate system each."),
      b.bullet("Scaling laws. Quality improved predictably with size, which turned research spending into a forecastable investment."),
      b.bullet("The interface breakthrough. Instruction tuning made models usable by anyone who can type a sentence - no programming, no training data of your own."),
      b.bullet("Economics of small models. Quantization (chapter F6) let the same ideas run locally, which is the branch of the story this platform builds on: private, offline, hardware you own."),
      b.h2("How applications evolved over time"),
      b.p("Each wave of applications used exactly the capability the models had just become good at. The progression is worth knowing because it locates stitaP in the timeline."),
      b.bullet("Wave 1 - prediction inside products (2017-2020). Autocomplete, smart replies, translation, search ranking. Models improved features quietly inside existing software."),
      b.bullet("Wave 2 - conversation (2020-2022). Instruction-tuned chat models. The chat window became a product category of its own; limitations appeared immediately: confident hallucinations, no memory, no ability to act."),
      b.bullet("Wave 3 - retrieval and grounding (2022-2023). Retrieval-augmented generation connected models to private documents to attack hallucination at its root - give the predictor the facts in its prompt. Vector databases and RAG became standard practice."),
      b.bullet("Wave 4 - tools and agents (2023-2024). Function calling let models request actions - search, click, compute - and agent loops chained those actions toward goals. The industry discovered that acting requires the surrounding harness: permissions, budgets, verification."),
      b.bullet("Wave 5 - governed multi-agent work (now). Teams of role-playing agents executing long projects with checkpoints, gates, and audit trails - the territory this platform occupies, with the deliberate twist that it runs on local hardware you own."),
      b.note("stitaP sits deliberately at wave five with wave-three discipline underneath: local small models, retrieval-grounded answers, tool use inside declared permissions, and verification gates everywhere. Each wave's lesson is baked in as a mechanism, not a slogan."),
    ],
  },
  // ─── F6 ────────────────────────────────────────────────────────
  {
    title: "How models are made: data, training, attention",
    blocks: [
      b.p("You will never train a foundation model - the cost is in the hundreds of millions of dollars - but you should understand the pipeline, because three of its stages reappear at scales you WILL touch: fine-tuning, quantization, and retrieval all borrow their concepts from it. This chapter connects the dots: datasets, training, attention, and the hardware libraries involved."),
      b.h2("Stage 1 - the dataset"),
      b.p("Training begins with text at web scale: trillions of tokens drawn from public pages, books, code repositories, and licensed material. Raw collection is not enough; preparation dominates the effort. Deduplication removes thousands of near-identical copies. Filtering removes spam, boilerplate, and low-quality text. Decontamination removes benchmark test sets so reported scores stay honest. The literature's consistent finding: dataset quality per token matters as much as quantity - a cleaner trillion tokens beats a dirtier two trillion."),
      b.h2("Stage 2 - pretraining"),
      b.p("Pretraining runs the loop from chapter F4 at scale: hide the next token, predict it, measure the error, adjust every parameter a tiny step in the direction that reduces the error (the algorithm is stochastic gradient descent; the adjustment size is the learning rate). Repeat trillions of times across thousands of GPUs for weeks or months. The output is a base model: superb at continuing text, indifferent to instructions - ask it a question and it may continue with three more questions, because that is what question-shaped text looks like in its training data."),
      b.h2("Stage 3 - fine-tuning and alignment"),
      b.p("Fine-tuning continues training on a small, curated dataset that demonstrates the behavior you want. The stages, as the literature names them:"),
      b.bullet("Supervised fine-tuning (SFT). Train on tens of thousands of high-quality example conversations - prompt plus ideal answer. The model learns the FORMAT of being an assistant: answer rather than continue."),
      b.bullet("Reinforcement learning from human feedback (RLHF). Humans rank pairs of model answers; a reward model learns those preferences; the main model is optimized against it. The model learns not just format but judgment - helpful, honest, harmless."),
      b.p("The key insight for you: fine-tuning adjusts the same parameters with the same mathematics as pretraining, just on different data. That is why the concept transfers down the stack - stitaP's deterministic responders, template prompts, and guideline packs are all ways of steering a model's behavior that cost thousands of tokens instead of thousands of GPU-hours."),
      b.h2("The attention mechanism, in plain terms"),
      b.p("Attention is the mechanism that made transformers work, and it is simpler than its reputation. For each token being processed, attention asks three questions using three learned projections called Query, Key, and Value:"),
      b.bullet("Query: what am I looking for? (For the token 'it' in 'the trophy didn't fit because it was too big': a thing that could be too big.)"),
      b.bullet("Key: what does each other token offer? (Each token advertises what it is about.)"),
      b.bullet("Value: if I attend to you, what information do you contribute?"),
      b.p("The model scores the query against every key, converts scores to weights, and blends the values. 'It' ends up attending strongly to 'trophy', and its representation absorbs trophy-ness. Every head in every layer does this simultaneously for all tokens - which is the mechanism behind the model's grip on long-range context that n-grams and RNNs lacked."),
      b.p("One cost follows directly: comparing every token against every other token grows quadratically with sequence length. Doubling the context window quadruples attention work. This is the mathematical reason long contexts cost more, generate slower, and why chapter F5's budget discipline matters at the architecture level, not just the wallet level."),
      b.h2("The hardware libraries, stated precisely"),
      b.p("Training and inference run their math through specialized libraries. Two different layers get confused with each other, so here they are separately:"),
      b.bullet("GPU compute libraries execute the attention and matrix arithmetic on accelerators: CUDA and cuBLAS on NVIDIA hardware, ROCm on AMD, Metal Performance Shaders on Apple, oneDNN and OpenVINO kernels on Intel. These libraries provide tuned implementations of exactly the operations attention needs - large matrix multiplies and softmax over scores. When this manual says a backend is 'llamacpp-cuda' or 'openvino-npu', it means inference is routed through that library family."),
      b.bullet("GLIBC is something entirely different: the C standard library of the Linux operating system - the layer every userspace program uses for basic services like memory allocation and file access. It has nothing to do with attention or GPUs, but it matters to this platform for a deployment reason covered in chapter 7: old servers ship old GLIBC versions, and modern binaries linked against new GLIBC will not start there. That is why the legacy path builds statically against musl, carrying its own library instead of using the host's."),
      b.note("Summary of the two layers: GPU libraries make the math fast on your silicon; GLIBC makes the binary start on your operating system. stitaP's router picks among the first; stitaP's legacy builds are immune to the second."),
      b.h2("Why this chapter matters to you"),
      b.p("Every concept here reappears later in a form you control. Datasets become the knowledge base you ingest. Training objectives become the structured prompts you write. Fine-tuning-by-data becomes guideline packs. Attention's quadratic cost becomes the token budget on every session. You now know why each of those mechanisms exists - not because documentation asserted it, but because the underlying machine makes it necessary."),
    ],
  },
  // ─── F5 ────────────────────────────────────────────────────────
  {
    title: "Tokens, windows, and why things cost what they cost",
    blocks: [
      b.p("Every quantity in this platform - prompt overhead, retrieval budgets, swarm digests - is measured in tokens. This chapter gives you working intuition so budgets stop being abstract."),
      b.h2("What a token looks like"),
      b.p("Models split text into common pieces. 'understanding' might become 'under' + 'standing'. As approximations: 1,000 tokens is roughly 750 words, a full page of text is roughly 500 tokens, and this paragraph is roughly 80 tokens."),
      b.h2("Everything counts against the window"),
      b.p("The context window fills from several sources at once. Knowing the list lets you predict costs:"),
      b.bullet("System prompt. Instructions from enabled modules. This is the fixed cost your session pays every single turn."),
      b.bullet("Conversation history. Everything said so far, growing every turn."),
      b.bullet("Retrieved documents. Text pulled from the knowledge base into the prompt."),
      b.bullet("Tool results. What tools returned last turn, if kept in view."),
      b.bullet("Output. What the model writes now."),
      b.h2("A worked example"),
      b.code(
        "Window:                4,096 tokens  (small model)",
        "System prompt:       -   800  (SLM Minimal preset)",
        "Conversation so far: -   600",
        "Retrieved docs:      -   500  (knowledge base budget)",
        "Tool results:        -   300",
        "-------------------------------------------",
        "Room for the reply:  = 1,896 tokens  (~1,400 words)",
      ),
      b.p("Now imagine enabling every module instead. System prompt grows past 6,000 tokens - larger than the whole window. The model cannot even fit its instructions, and generation collapses. This is precisely the trade the /modules page shows before you commit."),
      b.h2("The three levers you control"),
      b.bullet("Choose a smaller preset when the model is small. SLM Minimal exists for exactly this."),
      b.bullet("Bound retrieval. The knowledge base returns only what fits your stated budget instead of everything vaguely related."),
      b.bullet("Prefer digests over transcripts in group work. Swarm blackboards summarize ('14 tests green') instead of replaying everything."),
      b.h2("Speed follows size too"),
      b.p("Generation speed falls as the filled portion of the window grows, because the model rereads everything each step. Keeping sessions lean is not only about fitting - it is the main thing you can control about response time."),
      b.h2("What actually consumes the most tokens"),
      b.p("Not all activities cost alike. The list below ranks the common ones from most expensive to least, with the typical magnitude you should expect. The pattern is consistent: anything that pastes raw content into the window dwarfs anything that summarizes it."),
      b.bullet("Raw page or HTML dumps: 10,000 to 50,000 tokens for one modern web page. The single most expensive mistake an agent session can make; structured extraction of the same page costs hundreds."),
      b.bullet("Full conversation transcripts replayed each turn: grows without bound. Ten turns of a chatty session can exceed the entire window; digests cap the same information at a few hundred tokens."),
      b.bullet("Retries after failures: every failed attempt pays for its prompt again. Three retries at a 2,000-token prompt spend 6,000 tokens to deliver one answer - the worst useful-to-spent ratio in ordinary operation."),
      b.bullet("Unfiltered tool results: a network capture with bodies, a full directory listing, a complete test log. Each can cost thousands; the useful part is usually the tail line."),
      b.bullet("Retrieved passages: bounded by design (the knowledge base respects your budget), typically 300 to 800 tokens - expensive per token but cheap in total because the budget enforces it."),
      b.bullet("System prompt overhead: 800 to 6,000+ tokens depending on preset, paid every single turn. Fixed cost; the only lever is which modules are enabled."),
      b.bullet("The generated answer itself: usually the SMALLEST line item - a good answer is often 100 to 500 tokens. This surprises most people: output is cheap; context is expensive."),
      b.h2("Useful tokens versus spent tokens"),
      b.p("Define token efficiency as the ratio between the tokens that constitute the delivered answer and the total tokens the session consumed producing it. A worked example makes the ratio concrete:"),
      b.code(
        "Task: extract the refund policy from a help page.",
        "",
        "Spent:",
        "  system prompt (SLM Minimal)      800",
        "  raw page dumped into prompt   12,000   <- the mistake",
        "  first answer (hallucinated)      300",
        "  retry with correction prompt   2,100",
        "  final answer                     250",
        "  ------------------------------ -------",
        "  total spent                   15,450",
        "",
        "Useful:                                     250 tokens",
        "Token efficiency: 250 / 15,450 = ~1.6%",
      ),
      b.p("The same task done with structured extraction and a grounded prompt spends roughly 1,900 tokens to deliver the same 250 useful ones - about 13 percent, an eightfold improvement. Nothing about the model changed; only what fed it. This is why the harness invests so heavily in extraction, digests, budgets, and verification: each mechanism exists to delete a category of wasted tokens."),
      b.p("The practical levers, in order of impact: never paste raw pages (extract instead); never replay transcripts (summarize instead); fix prompts rather than retrying (a corrected prompt beats three identical ones); bound every retrieval; and keep the system prompt minimal on small models. Sessions that follow these five rules routinely operate above 20 percent efficiency; sessions that ignore them fall under 2 percent."),
      b.h2("Why an FP16 small model can out-generate a quantized one"),
      b.p("It seems contradictory after the quantization chapter: fewer bits should mean faster. Sometimes the opposite is true, and the reasons are concrete. Throughput is decided by which kernel executes the math, not by bit count alone."),
      b.bullet("Dequantization overhead. Quantized weights are stored compressed but must be unpacked to floating point before the multiply. On hardware whose kernels handle that format natively and fast, the unpacking is nearly free. On hardware without optimized kernels for that format, the unpacking runs as extra arithmetic on every weight, every token - and the savings shrink or vanish."),
      b.bullet("Native FP16 paths. Modern accelerators execute 16-bit floating point directly in hardware, with tuned libraries (chapter on model-making lists them). An FP16 small model rides those optimized kernels; an exotic 4-bit format may fall back to slower generic code. Same model quality, opposite throughput ranking."),
      b.bullet("Compute-bound versus memory-bound. Decoding is usually limited by memory bandwidth, which favors quantization; prefilling a long prompt is compute-heavy, where FP16 tensor paths win. A session that ingests long documents and answers briefly can therefore see FP16 finish sooner overall even when its decode speed per token is lower."),
      b.bullet("Distilled models are a different trade. Distillation transfers a large model's behavior into a smaller one, and the result is not automatically efficient: distilled models can be deeper or differently shaped in ways that suit the teacher's accuracy rather than the student's hardware. Some also answer verbosely, spending more tokens per useful fact. A well-chosen FP16 small model can deliver more USEFUL tokens per second than a distilled one that rambles."),
      b.bullet("Quality-per-token closes the loop. A model that answers correctly on the first try has perfect efficiency; a quantized model that needs one retry just doubled its token cost. Effective throughput - useful tokens per second across the whole task - is what matters, and it can favor the more accurate model even at lower raw speed."),
      b.note("The router resolves this empirically instead of arguing: it benchmarks the candidate model-and-format combinations on YOUR device with YOUR workload and keeps the measured winner (chapter 4 of the core manual). When you see an FP16 model out-pace a quantized one, the reasons above are usually visible in the measurement: kernel support, workload shape, or answer quality."),
    ],
  },
  // ─── F6 ────────────────────────────────────────────────────────
  {
    title: "Quantization: fitting models on real machines",
    blocks: [
      b.p("Inside a model sit millions or billions of decimal numbers. Precision - how many digits each number keeps - decides both the file size and the memory it needs. Quantization means storing those numbers with fewer digits."),
      b.h2("The sizes involved"),
      b.code(
        "Full precision (FP16):  each number ~2 bytes",
        "8-bit  (Q8):            each number ~1 byte    -> half the size",
        "4-bit  (Q4):            each number ~0.5 bytes -> quarter the size",
        "",
        "A 7B-parameter model:",
        "  FP16  ~14 GB   needs a server",
        "  Q8     ~7 GB   needs a good laptop",
        "  Q4    ~4-5 GB  runs on almost anything",
      ),
      b.h2("The full RAM bill: a model needs more than its file size"),
      b.p("The table above is only the first line of the bill. A running model needs three things in memory at once, and only one of them shrinks with quantization."),
      b.bullet("Weights. The billions of numbers themselves. This is the file size, and it is the part quantization shrinks."),
      b.bullet("Context memory (KV cache). While generating, the model keeps notes about every token it has read so far, so it does not re-read the whole conversation for each new token. This grows as the conversation grows, and quantizing the weights does not shrink it. A 7B model with an 8,000-token context can hold another 1-2 GB of these notes."),
      b.bullet("Working space. Scratch memory for the current calculation, plus the runtime program itself. Usually a few hundred megabytes."),
      b.code(
        "Total RAM needed = weights + context memory + working space",
        "",
        "7B model, 8K context:",
        "  FP16:  14 GB weights + ~1.5 GB context + overhead ~= 16 GB",
        "  Q8:     7 GB weights + ~1.5 GB context + overhead ~=  9 GB",
        "  Q4:     4 GB weights + ~1.5 GB context + overhead ~=  6 GB",
        "  b1.58:  2 GB weights + ~1.5 GB context + overhead ~=  4 GB",
      ),
      b.h2("Context memory (the KV cache): what the notes are explained"),
      b.p("Chapter F5 explained that a model reads tokens and predicts one at a time. Here is the problem that creates: when generating token number 500, the model would need to re-read tokens 1 through 499 again - and for token 501, all 500. Without help, a long conversation would get slower with every word. The KV cache is the help. After reading each token, the model writes down a small summary of what that token contributed, per layer. When generating the next token, it reads the summaries instead of the original text."),
      b.p("The name comes from the two kinds of summary stored: keys (how to be found) and values (what to contribute). Every layer keeps its own set, which is why the cache is large."),
      b.h3("How big it gets"),
      b.p("Cache size grows in exact proportion to the conversation: twice the tokens, twice the cache. The formula:"),
      b.code(
        "cache bytes = tokens x layers x 2 (K and V) x bytes-per-number",
        "",
        "A typical 7B model (32 layers, FP16 numbers, 8K tokens):",
        "  8192 x 32 x 2 x 2 bytes x width-factor ~= 1-2 GB",
      ),
      b.p("Notice what this means: the cache is computed at RUN time, in whatever precision the runtime uses - usually FP16. Quantizing the weights on disk does nothing to it. A Q4 model still carries an FP16-sized cache."),
      b.h3("What happens at the limit"),
      b.p("The cache has a maximum size: the context window. When it fills, runtimes drop the oldest tokens (a sliding window). The model does not warn you - the beginning of the conversation simply stops existing for it. If your agent forgot an instruction from an hour ago, this is usually why: the note was evicted, not ignored. The harness counters this with digests and checkpoints (chapter F9): a short summary of evicted history costs far fewer tokens than keeping the history."),
      b.h3("How to shrink the cache"),
      b.bullet("Shorter context. The only complete cure: the cache is proportional to tokens kept."),
      b.bullet("KV-cache quantization. Many runtimes can store the notes at 8-bit or even 4-bit instead of FP16, roughly halving or quartering that line of the bill at a small accuracy cost - most useful for long sessions on tight machines."),
      b.bullet("Efficient architectures. Newer models reduce notes per token through shared keys and values across groups of heads (grouped-query attention) or by only attending to a recent window. When the platform's model catalog lists a model as 'long-context efficient', this is the mechanism behind it."),
      b.h2("Working space: the scratch memory"),
      b.p("The third component is the least discussed and the simplest. To produce one token, the model computes a series of intermediate results - matrices that exist only between two layers and are thrown away the next instant. The runtime reserves one buffer big enough for the largest of these, plus small scratch areas for picking the next token and for its own program code. Unlike the cache, this space is roughly FIXED: it depends on the model's width and how many requests run at once, not on how long the conversation has grown."),
      b.code(
        "Typical working space:",
        "  small model (1-3B):   ~200-400 MB",
        "  7B model:             ~400-800 MB",
        "  4 requests at once:   multiply by ~4 (each needs its own scratch)",
      ),
      b.p("On machines with a graphics card, all three components - weights, cache, and working space - must fit in the card's VRAM instead, and VRAM is smaller than system RAM. This is why the same model that fits a 16 GB machine in system memory may not fit an 8 GB graphics card. The platform's sizer checks VRAM separately for exactly this reason."),
      b.h2("What your machine can actually run"),
      b.p("Subtract what the operating system and your other programs use - typically 2-4 GB - from the machine's total RAM. What remains must cover the full bill above."),
      b.code(
        "Machine RAM   after OS   can run comfortably",
        "  4 GB          ~1.5 GB    1-3B model, Q4 or b1.58, short context",
        "  8 GB          ~5 GB      3B Q8 / 7B Q4, moderate context",
        "  16 GB         ~12 GB     7B Q8 or 13B Q4, long context",
        "  32 GB         ~28 GB     13B Q8 / 30B+ Q4, agent swarms",
      ),
      b.h2("What happens when the model does not fit"),
      b.p("The operating system then starts moving memory to disk (called swapping). The model still runs, but every token now waits on disk access, which is thousands of times slower than RAM. A session that generated 20 tokens per second drops to one token every few seconds. There is no setting that fixes this: the only cures are a smaller model, a lower-precision build, or a shorter context window. This is why the platform checks your free memory before loading anything and says so up front instead of letting a session crawl."),
      b.h2("How quantization shrinks the bill - and what it cannot shrink"),
      b.p("Quantization compresses only the weights. The arithmetic works like this: a model's size in gigabytes is roughly its parameter count in billions, times bits per weight, divided by 8, plus about 20 percent overhead for the context memory and working space."),
      b.code(
        "GB = params(B) x bits-per-weight / 8 x 1.2",
        "",
        "7B at FP16 (16 bits): 7 x 16/8 x 1.2 ~= 17 GB",
        "7B at Q8    ( 8 bits): 7 x  8/8 x 1.2 ~=  8.5 GB",
        "7B at Q4_K_M (~4.8 bits): 7 x 4.8/8 x 1.2 ~= 5.0 GB",
        "7B at b1.58 (1.58 bits): 7 x 1.58/8 x 1.2 ~= 1.7 GB",
      ),
      b.p("Each halving of bits per weight halves the weights line of the bill. The context line stays. Two consequences follow. First, on a machine that is barely large enough, a longer conversation can push a quantized model into swapping even though it loaded fine - so on tight machines, keep context windows short. Second, at extreme context lengths the context memory can rival the weights, which is why some runtimes offer KV-cache quantization (compressing the notes too, at a small accuracy cost). The platform's sizing math uses exactly this formula, which is why its memory estimates match what you see in a system monitor."),
      b.h2("What precision loss feels like"),
      b.p("Going from FP16 to Q8 usually changes almost nothing you can notice. Going to Q4 slightly increases wrong-word errors and weakens long chains of reasoning, but ordinary tasks - summarizing, extracting fields, calling tools, answering from provided documents - work well. Below 4 bits the rules change completely: ordinary quantization starts destroying the model, unless the model was built differently from the start. The rest of this chapter explains the extreme levels honestly, because you will see them offered."),
      b.h2("Names like Q4_K_M decoded"),
      b.p("GGUF files carry names such as Q4_K_M. Read them as: digits = bits per number; letters = method variant. Q4_K_M is the well-regarded middle choice of 4-bit methods and is the default recommendation across this platform. Q8_0 means plain 8-bit."),
      b.h2("Never quantize twice"),
      b.p("Each pass of quantization loses information permanently. Making a 4-bit copy from an already-8-bit file yields worse quality than making it from the original. The downloader therefore follows a strict order: prefer original weights, otherwise use an existing matching quant untouched, otherwise fetch the correct pre-made file - local requantization exists only as a labeled fallback."),
      b.h2("Below 4 bits: why ordinary quantization breaks"),
      b.p("Quantization squeezes each number into fewer digits. At 8 or 4 bits the rounding errors of thousands of numbers cancel each other out, and the model behaves almost the same. Below 4 bits the errors stop canceling: with only 2 or 3 digits of headroom, entire concepts that the model learned start rounding into the same value. The model does not crash - it degrades. Short answers still look fine, which makes the damage hard to notice. The failure shows up exactly where you need precision: multi-step reasoning, code generation, and following long instructions."),
      b.p("This is why the default recommendation everywhere on this platform is Q4_K_M or better. But two families of sub-4-bit builds exist that are genuinely usable, and you should understand both."),
      b.h2("1-bit and 1.58-bit: models born quantized (BitNet)"),
      b.p("A 1-bit build does not mean 'a normal model squeezed to 1 bit'. It means a model whose weights were always extreme values, because it was TRAINED that way. The BitNet family (from Microsoft Research) trains with ternary weights: every weight is one of exactly three values - negative one, zero, or positive one. Because each weight carries about 1.58 bits of information (log2 of 3 choices), these are called b1.58 models."),
      b.p("Why does this work when squeezing an existing model to 1 bit does not? During training, the model learns to compensate. Every time a weight rounds to its extreme value, the training process adjusts the other billions of weights around it. Quantization-aware training bakes the rounding into the model from the first step; post-training quantization inflicts it as a sudden injury. The result: a BitNet b1.58 model at 2-3 GB behaves closer to a 4-bit model of the same size, and its multiply-add math reduces to simple additions, which some hardware runs very fast."),
      b.bullet("What they are good for: chat, summarization, extraction, and tool calling on machines with 2-4 GB free. A 2B-parameter BitNet runs where nothing else fits."),
      b.bullet("What to expect: weaker reasoning than a 7B Q4 model. Choose BitNet for the memory floor, not for capability."),
      b.bullet("How to get one: download a released b1.58 GGUF. Never convert a normal model to 1 bit yourself - that produces the broken kind."),
      b.h2("2-bit and 3-bit builds: the IQ and K-quant families"),
      b.p("GGUF defines real formats between 1 and 4 bits. The common names:"),
      b.code(
        "Q2_K     ~2.6 bits/weight   smallest usable K-quant",
        "IQ2_XXS  ~2.1 bits          importance-matrix 2-bit",
        "IQ2_XS   ~2.3 bits          importance-matrix, slightly larger",
        "Q3_K_S/M ~3.0-3.4 bits      classic 3-bit K-quants",
        "IQ3_XXS  ~3.1 bits          importance-matrix 3-bit",
        "IQ3_XS   ~3.3 bits          importance-matrix, better quality",
      ),
      b.p("The 'IQ' formats use a technique called importance-matrix quantization. Before compressing, the tool runs a small calibration dataset (typically a few hundred KB of representative text) through the original model and records which weights matter most for the outputs. It then spends its scarce bits where they matter and rounds the rest aggressively. An IQ2 build made this way consistently outperforms an older Q2_K of the same size, because the same bits protect the important weights."),
      b.h2("How to create a 2- or 3-bit build correctly"),
      b.p("Follow this order. Skipping the first step is the single most common mistake."),
      b.bullet("1. Start from ORIGINAL weights. Use the FP16 (or BF16) source model. Never quantize an already-quantized file - the compounding loss at 2-3 bits is severe enough to produce gibberish."),
      b.bullet("2. Build the importance matrix. Run the calibration pass over text similar to your workload: documentation for a docs assistant, code for a coding assistant."),
      b.bullet("3. Quantize with the matrix. Produce IQ2_XS first if memory allows; step down to IQ2_XXS only if it does not fit."),
      b.bullet("4. Verify before trusting. Run the same ten questions against the Q4 build and the new build. If answers diverge on simple tasks, the build is too aggressive for your workload - go one level up."),
      b.note("The platform's downloader follows this same decision path automatically: it prefers a pre-made quant from the original publisher, falls back to building one from original weights, and only requantizes an existing file as a clearly labeled last resort (chapter 5 of the core manual)."),
      b.h2("When each level makes sense"),
      b.code(
        "7B model, memory needed:",
        "  Q4_K_M  ~4.5 GB   default choice, best quality-per-byte",
        "  IQ3_XS  ~3.3 GB   tight laptops, small quality cost",
        "  IQ2_XS  ~2.3 GB   4 GB machines, simple workloads only",
        "  Q2_K    ~2.6 GB   older 2-bit fallback, use IQ instead",
        "  b1.58   ~2.0 GB   born-quantized model, best at this size",
      ),
      b.bullet("Use 3-bit when 4-bit barely misses your memory budget and the task is extraction, classification, or tool calling."),
      b.bullet("Use 2-bit only for short, simple tasks on very small machines, and only from an IQ build with a calibration matrix."),
      b.bullet("Use BitNet b1.58 when the machine has 2-4 GB free and you need a model that actually fits - it beats squeezed 2-bit builds at the same size."),
      b.bullet("Avoid sub-4-bit for long reasoning, code generation, or agent swarms: the error rate multiplies across steps, and a failed agent step costs more tokens than the memory you saved."),
      b.h2("Choosing in the interface"),
      b.p("Open the quantization menu, enter your hardware, and read the options. Each row shows estimated memory, expected speed, and a plain-language quality note. Sub-4-bit rows carry explicit warnings describing what degrades. The pre-selected row balances quality and fit; accept it or choose differently. Nothing is ever picked silently."),
    ],
  },
  // ─── F7 ────────────────────────────────────────────────────────
  {
    title: "What makes software an agent",
    blocks: [
      b.p("A chat window answers once and waits. An agent works toward a goal: it plans steps, calls tools to act, reads results, corrects course, and finishes when checks pass. The difference is a loop, not intelligence alone."),
      b.h2("The agent loop"),
      b.p("Nearly every agent framework - including stitaP's - reduces to this loop:"),
      b.code(
        "1. Look at the goal and current situation.",
        "2. Decide the single next action (ask a tool, ask a question, finish).",
        "3. Perform that action.",
        "4. Add the result to what the model sees.",
        "5. Unless finished, go to step 1.",
      ),
      b.p("Step 2 is the model. Steps 3 and 4 are the harness. Step 5 is why agents sometimes run long - and why the guardrails in later chapters exist."),
      b.h2("Tools give agents hands"),
      b.p("Without tools, an agent can only write text. With a screenshot tool it can see pages; with browser tools it can click them; with document tools it can read your help center. Each tool is registered with declared inputs, outputs, and permissions so the harness can enforce safety mechanically rather than trusting the model's judgment."),
      b.h2("Verification separates assistants from workers"),
      b.p("An unsupervised loop that trusts itself eventually produces confident nonsense. stitaP therefore wraps loops with explicit checks: tests must pass before code stories close, acceptance criteria must match evidence, and risky actions pause for a person. Verification converts 'the model says done' into 'done according to criteria.'"),
      b.h2("Memory and knowledge"),
      b.p("Two modules extend what agents know. Persistent memory stores decisions and preferences across sessions. The knowledge base retrieves passages from your own documents on demand. Both respect token budgets from chapter F5 - they add knowledge, not unbounded history."),
      b.h2("Where you come in"),
      b.p("Three human touchpoints matter. Composition: you check modules on and off to define capability. Oversight: approval gates route risky actions to you. Audit: traces record every step with timings and token counts, so reviewing an agent's work takes minutes, not faith."),
    ],
  },
  // ─── F8 ────────────────────────────────────────────────────────
  {
    title: "What a tool harness is, and where stitaP fits",
    blocks: [
      b.p("An agent left alone in an empty room can talk. A harness is everything that makes talking into doing: the tool shelf, the permission rules, the budget meter, the recorder, and the safety gates. This chapter maps those ideas onto stitaP's actual pieces."),
      b.h2("The shelves and the rules"),
      b.p("The tool store holds every capability, each registered with a manifest declaring what inputs it accepts and what permissions it needs. Enforcement is mechanical: a tool that did not declare network access cannot reach the network, no matter what its code tries. Sandboxing adds resource limits so a runaway operation cannot exhaust your machine."),
      b.h2("The meter"),
      b.p("Sessions have finite context windows (chapter F5). The module notebook computes what each enabled capability costs in tokens and shows the remaining room before you start. The same numbers tell the inference router how to tune generation. Composition, budgeting, and speed stay connected because they read one registry."),
      b.h2("The workshop floor"),
      b.p("Swarms run multiple agents with roles - planner, coder, tester, reviewer, documenter, verifier. They coordinate through a shared blackboard of short summaries, mirroring how effective human teams communicate: conclusions and pointers, not full transcripts shouted over each other."),
      b.h2("The foreman's clipboard"),
      b.p("Enterprise projects put governance around long work: your company standards become guideline packs that role-workers receive; user stories move on kanban boards; commits land in git; tickets update in Jira; checkpoints persist progress; and a verification gate demands evidence before anything closes."),
      b.h2("Self-containment, restated"),
      b.p("Every dependency in this repository is written in-house: the HTTP engine, PDF writer, git client, vector store, codecs. Consequences follow directly: no install scripts beyond the app itself, no outbound calls except integrations you configure, and identical behavior on a laptop, an air-gapped server, or a fifteen-year-old workstation."),
      b.h2("Reading order from here"),
      b.p("Part II of the manual (chapters 11 onward) documents each of these systems precisely. If you learn better by doing first, continue with the three walkthroughs - chapters F9, F10, and F11 - and treat Part II as reference material to return to."),
    ],
  },
  // ─── F9 ────────────────────────────────────────────────────────
  {
    title: "Walkthrough: your first session",
    blocks: [
      b.p("This walkthrough takes you from a fresh installation to a working chat session composed of exactly the capabilities you chose. Allow fifteen minutes."),
      b.h2("Step 1: verify the installation"),
      b.p("Run the smoke suites once from the repository root. They confirm every engine works on your machine without network access:"),
      b.code(
        "bun tsc -b --noEmit          # expect: no output, clean exit",
        "bun scripts/store-smoke.ts   # expect: hundreds of passed checks",
      ),
      b.h2("Step 2: open the module notebook"),
      b.p("Navigate to /modules. You see every module grouped by category with checkboxes. The panel beside them shows live totals: modules enabled, context overhead, recommended window, and active tool count."),
      b.h2("Step 3: choose a preset"),
      b.p("Select SLM Minimal if you run a small model or want maximum headroom. Select Balanced otherwise. Watch the budget panel recalculate instantly - this feedback is the point of the notebook."),
      b.h2("Step 4: adjust two modules"),
      b.p("Check the knowledge-base module on and watch dependencies resolve automatically - anything it requires becomes checked too. Now uncheck the video-editor module and watch dependents cascade off. Nothing breaks either way; disabled tools simply report themselves unavailable."),
      b.h2("Step 5: read the budget"),
      b.p("Confirm the overhead figure leaves comfortable room in your model's window using the arithmetic from chapter F5. If the remaining room looks thin, remove modules rather than accepting starvation."),
      b.h2("Step 6: open a session and work"),
      b.p("Start a session from the dashboard. Ask for a task that uses your chosen capabilities - summarize an ingested document, explain a captured screenshot, draft steps for a guide. The session knows only what you enabled; that boundary is deliberate and visible."),
      b.h2("What you learned"),
      b.bullet("Composition happens before conversation, and the budget shows the cost."),
      b.bullet("Dependency resolution and cascading removals prevent broken states."),
      b.bullet("Disabled equals unavailable-and-reported, never crashed."),
    ],
  },
  // ─── F10 ───────────────────────────────────────────────────────
  {
    title: "Walkthrough: your first swarm",
    blocks: [
      b.p("One agent follows instructions. A swarm divides a goal among role-playing agents. This walkthrough configures a correctly sized swarm and interprets its coordination. Allow twenty minutes."),
      b.h2("Step 1: open the configurator"),
      b.p("Go to /modules#swarm. Enter your machine's specifications: physical cores, usable RAM, and the model size you plan to serve (parameters and bits). Use values from your operating system, not marketing labels - physical cores, as chapter F3 explained."),
      b.h2("Step 2: read the sizing verdict"),
      b.p("The configurator recommends a worker count and topology, and shows its reasoning. Typical outcomes: a strong laptop supports three to five workers sharing one loaded model; an old server supports more workers at slower per-worker speed. The recommendation reserves memory honestly using the formula from chapter F6 instead of promising optimistic concurrency."),
      b.h2("Step 3: understand the roles"),
      b.p("Workers adopt roles in a ladder: planner decomposes the goal, coder implements, tester verifies, reviewer checks quality, documenter publishes notes, verifier closes items. You rarely assign roles manually - the topology implies them."),
      b.h2("Step 4: launch a bounded goal"),
      b.p("Give the swarm a small, concrete goal with a clear finish - for example, produce a style guide for screenshots with examples. Bounded goals teach the mechanics; week-long migrations come later, in chapter F11."),
      b.h2("Step 5: watch the blackboard"),
      b.p("As work progresses, the blackboard accumulates short entries: which role produced what, with references to artifacts. Notice what is absent - no worker reads another's full transcript. Digests keep every participant inside its token budget, which is why six small-model workers can cooperate where one small model alone would drown."),
      b.h2("Step 6: inspect completion"),
      b.p("When the verifier accepts the goal, open the run trace. Spans show each story's timeline and token spending. This trace is the same artifact enterprise runs attach to Jira tickets."),
      b.h2("Troubleshooting first swarms"),
      b.bullet("Slow workers? Check that the router picked your fastest backend; the status card shows measurements."),
      b.bullet("Workers repeating each other? Your goal was under-specified; add concrete acceptance criteria."),
      b.bullet("Out-of-memory? Reduce worker count - the formula reserved less than reality demanded."),
    ],
  },
  // ─── F11 ───────────────────────────────────────────────────────
  {
    title: "Walkthrough: your first governed project",
    blocks: [
      b.p("Governed projects are where this platform differs most from chat-based tools: agents execute a planned body of work for days, committing changes, updating tickets, and passing verification gates. This walkthrough stages a small migration end to end. Allow forty minutes, mostly reading what the runner produces."),
      b.h2("Step 1: load a guideline pack"),
      b.p("Prepare your standards as short sections - coding rules, testing requirements, documentation expectations, security constraints. Load them once. Roles receive only their relevant sections within token caps: guidelines steer behavior without consuming context."),
      b.h2("Step 2: describe the project"),
      b.p("Enter the goal - for example, migrate a small utility from Python 2 to Python 3. Planning decomposes it into dependency-ordered user stories, each with acceptance criteria. Order matters: stories whose inputs depend on other outputs wait their turn."),
      b.h2("Step 3: approve the plan"),
      b.p("Review the ordered stories. Edit criteria now, while editing is cheap. Approving the plan commits it to git and opens an epic ticket - the first checkpoint."),
      b.h2("Step 4: let it run, then read the board"),
      b.p("Stories move develop, test, document in sequence. Checkpoints persist after every phase, so interruption resumes cleanly. The board shows each story's state; blocked items explain what evidence they lack."),
      b.h2("Step 5: handle an approval"),
      b.p("Configure one story with elevated risk beforehand if you want to see gating. Its execution pauses in review until you approve, reject, or let it expire. Policy-blocked risks skip cleanly without deadlocking other work."),
      b.h2("Step 6: witness a gate refusal"),
      b.p("Find any story whose criteria were not fully met - the gate sends it back for another development pass. This refusal loop is the platform's core honesty feature: completion requires matching evidence, and the trace waterfall attached to the Jira comment proves it happened."),
      b.h2("Scaling judgment"),
      b.p("After this rehearsal, apply the same flow to real work. Size ambition to hardware using chapters F10 and 7. Start migrations at one-week scale with daily checkpoints before attempting longer autonomous stretches."),
    ],
  },
];

/** Alphabetical glossary chapter appended after foundations. */
export function buildGlossaryChapter(): PdfChapter {
  return {
    title: "Glossary",
    blocks: GLOSSARY.map(([term, def]) => ({
      type: "bullet" as const,
      text: `${term}: ${def}`,
    })),
  };
}

const GLOSSARY: Array<[string, string]> = [
  ["Attention", "The transformer mechanism: each token queries all others (via learned Query/Key/Value projections) and blends their information by relevance. Costs grow quadratically with sequence length."],
  ["Base model", "A model after pretraining only: superb at continuing text, not yet tuned to follow instructions."],
  ["CUDA / cuBLAS", "NVIDIA's GPU computing library and its tuned matrix-math library; the training and inference kernels for NVIDIA hardware."],
  ["Decontamination", "Removing benchmark test data from training sets so reported evaluation scores stay honest."],
  ["Dequantization", "Unpacking compressed (quantized) weights back to floating point before computation; the overhead that can make quantized models slower than FP16 on hardware without native kernels."],
  ["Distillation", "Training a smaller student model to imitate a larger teacher; smaller and cheaper, but not automatically faster or more concise on your hardware."],
  ["FP16", "Sixteen-bit floating point: full-precision weights for small models, executed natively by modern accelerators - sometimes the fastest option, not just the most accurate."],
  ["Fine-tuning", "Continuing training on a small curated dataset to teach a specific behavior; same math as pretraining, different data."],
  ["GLIBC", "The GNU C library - the basic services layer of Linux userspace. Old servers ship old GLIBC, which is why stitaP's legacy builds link statically against musl instead."],
  ["GPU compute libraries", "The tuned kernel libraries that execute attention and matrix math on accelerators: CUDA/cuBLAS (NVIDIA), ROCm (AMD), Metal (Apple), oneDNN/OpenVINO (Intel)."],
  ["Hallucination", "A confident, fluent, factually wrong output. Root cause: models predict plausibility, not truth."],
  ["Learning rate", "How far each training step moves parameters; too large destabilizes training, too small never converges."],
  ["LSTM", "Long short-term memory: a recurrent network with gates that improved memory over plain RNNs; the predecessor displaced by transformers."],
  ["N-gram model", "Early statistical predictor estimating the next word from the previous one or two; the direct ancestor of modern language models."],
  ["Pretraining", "The trillion-token next-token-prediction stage that produces a base model."],
  ["RLHF", "Reinforcement learning from human feedback: humans rank answers, a reward model learns the preferences, the main model optimizes against it."],
  ["Scaling laws", "The observed relationship that model quality improves predictably with compute, data, and parameters - the reason investment followed transformers."],
  ["SFT", "Supervised fine-tuning: training on example conversations so a base model learns the format of being an assistant."],
  ["Stochastic gradient descent", "The core training algorithm: measure the prediction error, nudge every parameter slightly to reduce it, repeat."],
  ["Token efficiency", "Useful output tokens divided by total tokens consumed. Raw-page dumping and retry storms push sessions under 2%; extraction, digests, and bounded retrieval keep them above 20%."],
  ["Transformer", "The 2017 architecture from 'Attention Is All You Need': reads all tokens in parallel with attention, enabling web-scale training. The foundation of every modern LLM."],
  ["Acceptance criteria", "The stated conditions under which a work item counts as done. Verification gates compare delivered evidence against them."],
  ["Agent", "Software that uses a model to decide actions, calls tools to perform them, and repeats until a goal is met."],
  ["AGI-free zone", "A promise: nothing here claims general intelligence. Every module does a defined job."],
  ["Approval gate", "A checkpoint that pauses risky agent actions until a person approves, rejects, or lets them expire."],
  ["Backend", "A specific runtime that generates tokens, such as llama.cpp on CPU or OpenVINO on NPU."],
  ["Benchmark cache", "Saved measurement results keyed to your hardware, so backend selection does not re-test on every launch."],
  ["Blackboard", "The shared message board where swarm workers post short summaries of what they produced."],
  ["Checkpoint", "A saved snapshot of progress that allows resuming after interruption."],
  ["Context overhead", "The number of tokens a module adds to every session prompt while enabled."],
  ["Context window", "The maximum tokens a model considers at once; its working memory."],
  ["Cron", "A scheduling format describing recurring times, such as every 15 minutes on weekdays."],
  ["Digest", "A compressed summary of an event or artifact, sized to cost tens of tokens instead of thousands."],
  ["Embedding", "A numeric representation of text used to measure similarity for retrieval."],
  ["Executor", "The function that performs a tool's work when invoked."],
  ["Fail soft", "Design rule: missing capability produces a reported limitation, never a crash."],
  ["Git", "The standard system for recording file changes; agents commit their work through it."],
  ["Guideline pack", "Your company's standards, loaded once and delivered to each agent role in relevant, token-capped portions."],
  ["Guest worker", "Informal term for a sub-swarm spawned for one bounded subtask."],
  ["Harness", "The system around agents: tools, permissions, budgets, tracing, and gates. stitaP is a harness."],
  ["Inference", "Running a trained model to produce output."],
  ["Jira ticket", "A tracked work item with comments and state, updated automatically by governed runs."],
  ["Kanban board", "Columns of work items moving from To Do toward Done; agents use boards like human teams."],
  ["Knowledge base", "stitaP's local retrieval store: ingest documents, retrieve passages within a token budget."],
  ["LLM", "Large language model: a model trained on vast text that predicts plausible continuations."],
  ["Manifest", "A tool's declaration card: id, parameters, outputs, permissions, supported backends."],
  ["Migration project", "A governed body of work converting software between languages or versions via user stories."],
  ["Module", "A bundled capability set that can be toggled per session; contributes tools plus instruction tokens."],
  ["NPU", "Neural processing unit: a chip specialized for AI math, emphasizing efficiency per watt."],
  ["NUMA", "Memory layout on multi-socket servers; ignoring it halves effective throughput."],
  ["Preset", "A named starting combination of session modules, such as SLM Minimal."],
  ["Quantization", "Storing model numbers with reduced precision to shrink size and speed up inference."],
  ["KV cache", "The notes a model keeps about every token it has read, so it does not re-read the conversation for each new token. It grows with the conversation, is not shrunk by weight quantization, and on long sessions can rival the weights in memory."],
  ["Swapping", "When RAM runs out, the operating system moves memory to disk. The program keeps running but slows by orders of magnitude - the usual symptom of a model that does not quite fit."],
  ["BitNet (b1.58)", "A model family trained from the start with ternary weights (-1, 0, +1), about 1.58 bits per weight. Because training compensates for the rounding, it works where squeezing a normal model to 1 bit would destroy it."],
  ["Ternary weights", "Weights limited to three values: negative one, zero, and positive one. The model learns around this constraint during training instead of suffering it afterward."],
  ["Importance matrix", "A table of which weights matter most for output quality, measured by running calibration text through the original model. IQ-format quants spend their bits where the matrix says it counts."],
  ["IQ quants (IQ2/IQ3)", "GGUF formats between 2 and 3 bits that use an importance matrix. At the same size they outperform older Q2_K/Q3_K formats because the important weights keep more precision."],
  ["Calibration dataset", "A few hundred kilobytes of representative text run through a model before importance-matrix quantization. Match it to your workload: docs for a docs assistant, code for a coding assistant."],
  ["RAG", "Retrieval-augmented generation: fetching your documents into the prompt so answers use them."],
  ["Router", "The component that probes, benchmarks, and selects the fastest inference backend."],
  ["Sandboxing", "Running operations under enforced resource and permission limits."],
  ["Session", "One working conversation with its chosen set of enabled modules."],
  ["SLM", "Small language model: runs on ordinary hardware; the primary target of this platform."],
  ["Smoke test", "A fast automated suite verifying each part still works; all run offline."],
  ["Speculative decoding", "A speed technique: a tiny model drafts tokens, the main model approves them in parallel."],
  ["StateGraph", "stitaP's graph orchestration: typed channels, nodes, conditional edges, loops, checkpoints."],
  ["Swarm", "Multiple agents with roles cooperating on one goal through a blackboard."],
  ["System prompt", "Opening instructions placed before every turn, shaping behavior; grown by enabled modules."],
  ["Ticket", "A tracked unit of work in Jira or similar systems."],
  ["Token", "A text chunk models read and write; roughly three-quarters of an English word."],
  ["Tool", "A named capability agents call, with declared inputs, outputs, and permissions."],
  ["Topologies", "Arrangements for connecting swarm workers: hierarchical, mesh, pipeline, star, ring."],
  ["Trace", "A recorded span tree of one run with timing and token accounting."],
  ["Typecheck", "Automated static analysis catching code mistakes before execution."],
  ["User story", "A unit of desired functionality with acceptance criteria, small enough for one agent pass."],
  ["Vector index", "Storage for embeddings enabling similarity search; Convex hosts stitaP's searchable captures."],
  ["Verifier", "The swarm role responsible for final acceptance against evidence."],
  ["Waterfall", "A timeline visualization of spans showing where a run spent time and tokens."],
  ["Webhook", "An outbound notification channel delivering alerts to a URL you provide."],
  ["Window starvation", "Failure mode where enabled overhead exceeds the context window, collapsing generation."],
  ["KV-cache quantization", "Storing the cache notes at 8- or 4-bit instead of FP16, halving or quartering context memory at a small accuracy cost. Useful for long sessions on tight machines."],
  ["Grouped-query attention (GQA)", "A model design that shares key and value notes across groups of attention heads, shrinking the KV cache per token. Common in newer long-context models."],
  ["Activations", "The intermediate results computed between model layers for the current token. They exist for an instant and are thrown away, but the runtime must reserve a fixed buffer large enough for the biggest one - this is the working space."],
];
