export const needs = [];
export default async ({ run, m, clip, ocrImage, dataDir }) => {
  await run("huggingface.search", { query: "qwen" }, "any");
  await run("huggingface.download", { modelId: "Qwen/Qwen2.5-0.5B-Instruct-GGUF" }, "any");
  const fs = await import("node:fs"); fs.mkdirSync(process.env.STITAP_DATA_DIR + "/models/a/b", { recursive: true }); fs.writeFileSync(process.env.STITAP_DATA_DIR + "/models/a/b/m-Q4_K_M.gguf", "x".repeat(1000));
  await run("huggingface.list_downloaded");
  await run("huggingface.delete", { modelId: "a/b", filename: "m-Q4_K_M.gguf" });
  await run("huggingface.delete", { modelId: "a/b", filename: "../../../x" }, true);
  await run("huggingface.quant_info", { quant: "Q4_K_M" });
  await run("huggingface.quant_info", {});
  await run("huggingface.recommend", { ramGB: 8 });
  await run("llm.call", { provider: "openai", model: "gpt-4o-mini", messages: [{ role: "user", content: "hi" }] }, "any");
  await run("llm.manageContext", { action: "add", messages: [{ role: "system", content: "You are helpful." }, ...Array.from({ length: 30 }, (_, k) => ({ role: k % 2 ? "assistant" : "user", content: `Message ${k}: we decided to use Postgres for table ${k}. ` + "lorem ipsum ".repeat(40) }))] });
  await run("llm.manageContext", { action: "trim", maxTokens: 1500, strategy: "summary" });
  await run("llm.manageContext", { action: "summarize" });
  await run("llm.manageContext", { action: "export" });
  await run("llm.generateScript", { content: "# Create an invoice\n\n1. Open the Billing page\n2. Click New Invoice\n3. Add line items and press Save", title: "Invoices" });
  await run("ocr.indic.postprocess", { text: "నమస్కారం  ప్రపంచం" });
  await run("ocr.indic.recognize", { image: ocrImage, language: "eng" });
  await run("ocr.indic.detect", { image: ocrImage });
  await run("ocr.indic.batch", { images: [ocrImage], language: "eng" });
  await run("ocr.indic.recognize", { image: ocrImage, profile: "telugu-english" }, "any");
  const html = `<html><head><title>Billing API</title></head><body><h1>Getting started</h1><ol><li>Install the CLI with npm i billing</li><li>Run billing login</li><li>Create your first invoice</li></ol><h2>Create invoice</h2><p>POST /v1/invoices/{customerId}</p><table><tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr><tr><td>amount</td><td>integer</td><td>yes</td><td>Amount in paise</td></tr></table><pre>curl -X POST https://api.x/v1/invoices/c1</pre><h2>FAQ</h2><h3>How do I cancel?</h3><p>Use the cancel endpoint.</p><h3>Is there a sandbox?</h3><p>Yes, use test keys.</p></body></html>`;
  await run("doc.extractSteps", { html });
  await run("doc.detectTutorial", { html, url: "https://x/docs/start" });
  await run("doc.parseFAQ", { html });
  await run("doc.generateScript", { steps: ["Open Billing", "Click New Invoice", "Press Save"], title: "Invoices", estimatedDuration: 30 });
  await run("doc.extractAPI", { html, format: "openapi" });
  await run("doc.extractAPI", { html, format: "markdown" });
};
