export const needs = [];
export default async ({ run, m, clip, ocrImage, dataDir }) => {
  process.env.SECRET_TOKEN = "should-not-leak";
  const e = await run("env.create", { name: "py", language: "python", envVars: "GREETING=hi" });
  await run("env.run", { environmentId: e.id, code: "import os,sys\nprint(os.environ.get('GREETING'), os.environ.get('SECRET_TOKEN'), sys.stdin.read().strip())", stdin: "from stdin" });
  const ej = await run("env.create", { name: "js", language: "javascript" });
  await run("env.run", { environmentId: ej.id, code: "console.log([1,2,3].map(x=>x*2).join(','))" });
  const et = await run("env.create", { name: "ts", language: "typescript" });
  await run("env.run", { environmentId: et.id, code: "const n: number = 41; console.log(n + 1)" });
  const es = await run("env.create", { name: "sh", language: "shell" });
  await run("env.run", { environmentId: es.id, code: "echo $((6*7)); pwd" });
  await run("env.run", { environmentId: ej.id, code: "while(true){}", timeoutMs: 1000 });
  await run("env.list", {});
  await run("env.destroy", { environmentId: es.id });
  await run("sandbox.scenarios", { category: "all" });
  const sb = (await run("sandbox.create", { name: "t1", isolationLevel: "full" })).sandbox;
  await run("sandbox.files", { sandboxId: sb.id, action: "write", path: "data/in.txt", content: "hello sandbox" });
  await run("sandbox.exec", { sandboxId: sb.id, code: "import fs from 'node:fs'; console.log(fs.readFileSync('data/in.txt','utf8'), process.env.SECRET_TOKEN ?? 'no-secret')" });
  await run("sandbox.exec", { sandboxId: sb.id, code: "import fs from 'node:fs'; try { fs.readFileSync('/etc/passwd'); console.log('READ-OK') } catch(e) { console.log('blocked:', e.code) }" });
  await run("sandbox.exec", { sandboxId: sb.id, code: "try { await fetch('https://example.com'); console.log('NET-OK') } catch(e) { console.log('net blocked:', e.message) }" });
  await run("sandbox.network", { sandboxId: sb.id, action: "log" });
  await run("sandbox.network", { sandboxId: sb.id, action: "policy", allowPatterns: "https://example.com/*" });
  await run("sandbox.network", { sandboxId: sb.id, action: "summary" });
  await run("sandbox.exec", { sandboxId: sb.id, language: "python", code: "print(sum(range(10)))" });
  const sn = await run("sandbox.snapshot", { sandboxId: sb.id });
  await run("sandbox.files", { sandboxId: sb.id, action: "delete", path: "data/in.txt" });
  await run("sandbox.snapshot", { sandboxId: sb.id, restore: sn.snapshotId });
  await run("sandbox.files", { sandboxId: sb.id, action: "read", path: "data/in.txt" });
  await run("sandbox.files", { sandboxId: sb.id, action: "read", path: "../../../etc/passwd" }, true);
  await run("sandbox.files", { sandboxId: sb.id, action: "list" });
  await run("sandbox.list", {});
  await run("sandbox.destroy", { sandboxId: sb.id });
  await run("agent.memory", { action: "add", type: "user", key: "lang", content: "User prefers Telugu summaries", importance: 0.9, tags: "pref" });
  await run("agent.memory", { action: "query", search: "telugu" });
  await run("agent.memory", { action: "stats" });
  await run("agent.memory", { action: "to-prompt" });
  const sk = await run("agent.skills", { action: "create", name: "Export invoices", description: "Export monthly invoices to CSV", category: "data", steps: '["open billing","filter month","export csv"]', tags: "billing" });
  await run("agent.skills", { action: "search", search: "invoice" });
  await run("agent.skills", { action: "get", skillId: sk.id, format: "slm-prompt" });
  await run("agent.skills", { action: "stats" });
  await run("agent.self-improve", { action: "record", taskData: '{"goal":"export csv","steps":[{"toolId":"browser.click","success":false,"durationMs":300,"error":"timeout"},{"toolId":"browser.click","success":true,"durationMs":200}]}' });
  await run("agent.self-improve", { action: "patterns" });
  await run("agent.self-improve", { action: "summary" });
  await run("agent.terminal", { command: "echo hello && uname" });
  const bg = await run("agent.terminal", { command: "for i in 1 2 3; do echo tick $i; sleep 0.2; done", background: true });
  await run("agent.terminal", { action: "wait", processId: bg.processId, timeoutSecs: 5 });
  await run("agent.terminal", { action: "list" });
  const b = await run("agent.kanban", { action: "create-board", boardName: "Launch" });
  const t1 = await run("agent.kanban", { action: "add-task", boardId: b.id, title: "Write docs", priority: "high" });
  await run("agent.kanban", { action: "fan-out", boardId: b.id, taskId: t1.id, subtasks: '["API docs","User guide"]' });
  await run("agent.kanban", { action: "move-task", boardId: b.id, taskId: t1.id, status: "in-progress" });
  await run("agent.kanban", { action: "snapshot", boardId: b.id });
};
