import { start } from "./site.mjs";
export const needs = ['chromium'];
export default async ({ run, m, clip, ocrImage, dataDir }) => {
  const srv = await start(); const U = `http://127.0.0.1:${srv.address().port}/`;
    try {
  await run("browser.navigate", { url: U });
  await run("browser.console", { action: "snapshot" });
  await run("browser.network", { action: "snapshot", filter: { resourceType: "fetch" } });
  await run("browser.websocket", { action: "snapshot" });
  await run("browser.click", { selector: "#buy" });
  await run("browser.type", { selector: "#email", text: "a@b.com" });
  await run("browser.hover", { selector: "#buy" });
  await run("browser.scroll", { mode: "toBottom" });
  await run("browser.screenshot", { mode: "fullPage" });
  await run("browser.screenshot", { mode: "element", selector: "form", format: "webp" });
  await run("browser.extract", { mode: "tables" });
  await run("browser.extract", { mode: "links" });
  await run("browser.extract", { mode: "metadata" });
  await run("browser.wait", { condition: "text", text: "added" });
  await run("browser.drag", { sourceSelector: "#buy", targetX: 300, targetY: 300 });
  await run("browser.inspect", { selector: "form", includeStyles: true, includeA11y: true });
  await run("browser.storage", {});
  await run("browser.state", {});
  await run("browser.extensions", {});
  await run("browser.source", { types: ["scripts"] });
  await run("browser.domevents", { action: "start", includeMutationObserver: true });
  await run("browser.click", { selector: "#buy" });
  await run("browser.domevents", { action: "snapshot" });
  await run("browser.cookies", { groupedByDomain: true });
  await run("browser.visual-understand", { action: "full" });
  await run("browser.extract-visual-context", { selector: "form" });
  await run("browser.screenshot-to-llm", { url: U, goal: "describe" });
  await run("browser.icon-detect", {});
  await run("browser.color-analyze", {});
  await run("browser.layout-analyze", {});
  await run("browser.performance", { action: "all", duration: 800 });
  await run("browser.interact-test", { selector: "#buy", action: "click", expectNetworkRequest: "/api/cart", expectDomChange: "#out" });
  await run("browser.a11y-audit", { standard: "AA" });
  await run("browser.responsive-test", { viewports: "375x812,1280x800" });
  await run("browser.security-headers", { url: U });
  await run("browser.seo-audit", { url: U });
  await run("browser.visual-regression", { baselineName: "home" });
  await run("browser.visual-regression", { baselineName: "home" });
  await run("browser.test-suggester", { scope: "all" });
  await run("browser.form-test", { formSelector: "#signup" });
  await run("browser.api-test", { action: "all" });
  await run("browser.design-audit", {});
  await run("browser.design-suggest", {});
  await run("browser.design-generate", { component: "pricing card" }, "any");
  await run("browser.color-palette", { action: "generate", brandColor: "#4f46e5" });
  await run("browser.color-palette", { action: "tokens", brandColor: "#0ea5e9", outputFormat: "tailwind" });
  await run("browser.color-palette", { action: "validate" });
  await run("browser.color-palette", { action: "analyse" });
  await run("browser.typography-check", {});
  await run("browser.spacing-check", { checkResponsive: true });
  await run("browser.component-qa", {});
    } finally { await m.closeStoreBrowsers(); srv.close(); }
};
