/* ─── stitaP Video Editor — Video Templates ─── */

import type { Track, Clip, Transition, TextOverlay, EditorMediaSource } from "../types";
import { generateId } from "../types";

export type TemplateCategory = "intro" | "outro" | "lower-third" | "title-card" | "caption" | "transition-pack" | "social";

export interface VideoTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  description: string;
  /** Duration in seconds */
  duration: number;
  /** Recommended project dimensions */
  width: number;
  height: number;
  /** Preview thumbnail color gradient */
  gradient: [string, string];
  /** Template icon */
  icon: string;
  /** Generator function that produces tracks/clips/text */
  generate: (opts?: TemplateGenerateOpts) => TemplateGenerateResult;
}

export interface TemplateGenerateOpts {
  /** Primary text (e.g. title) */
  title?: string;
  /** Secondary text (e.g. subtitle) */
  subtitle?: string;
  /** Primary color */
  primaryColor?: string;
  /** Secondary color */
  secondaryColor?: string;
  /** Background color */
  bgColor?: string;
}

export interface TemplateGenerateResult {
  tracks: Track[];
  textOverlays: TextOverlay[];
  transitions: Transition[];
}

/* ─── Intro Templates ─── */

const introTemplates: VideoTemplate[] = [
  {
    id: "intro_cinematic",
    name: "Cinematic Intro",
    category: "intro",
    description: "Dramatic fade-in with title reveal, perfect for film-style openings",
    duration: 5,
    width: 1920,
    height: 1080,
    gradient: ["#1a1a2e", "#16213e"],
    icon: "🎬",
    generate: (opts) => ({
      tracks: [
        {
          id: generateId("track"),
          name: "Background",
          kind: "video",
          clips: [],
          transitions: [],
          muted: false,
          volume: 1,
          visible: true,
          locked: false,
          color: "#6366f1",
        },
      ],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "YOUR TITLE",
          startOffset: 1.5,
          duration: 3.5,
          x: 50,
          y: 45,
          fontSize: 72,
          fontFamily: "Georgia, serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "A cinematic experience",
          startOffset: 2.5,
          duration: 2.5,
          x: 50,
          y: 58,
          fontSize: 24,
          fontFamily: "Georgia, serif",
          color: "#a0a0a0",
          backgroundColor: "transparent",
          bold: false,
          italic: true,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "intro_modern",
    name: "Modern Minimal",
    category: "intro",
    description: "Clean, minimalist intro with animated text slide-in",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#0f0f0f", "#1a1a1a"],
    icon: "✨",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "MODERN TITLE",
          startOffset: 0.5,
          duration: 3.5,
          x: 50,
          y: 48,
          fontSize: 64,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "clean & minimal",
          startOffset: 1.2,
          duration: 2.8,
          x: 50,
          y: 60,
          fontSize: 20,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#888888",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "intro_gradient",
    name: "Gradient Splash",
    category: "intro",
    description: "Vibrant gradient background with bold centered text",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#667eea", "#764ba2"],
    icon: "🌈",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "HELLO WORLD",
          startOffset: 0.3,
          duration: 3.7,
          x: 50,
          y: 50,
          fontSize: 80,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "intro_typewriter",
    name: "Typewriter",
    category: "intro",
    description: "Classic typewriter effect — text appears letter by letter",
    duration: 6,
    width: 1920,
    height: 1080,
    gradient: ["#2d2d2d", "#1a1a1a"],
    icon: "⌨️",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "Once upon a time...",
          startOffset: 0.5,
          duration: 5,
          x: 50,
          y: 50,
          fontSize: 36,
          fontFamily: "'Courier New', monospace",
          color: "#00ff41",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "intro_countdown",
    name: "Countdown",
    category: "intro",
    description: "3-2-1 countdown with numbers and flash",
    duration: 5,
    width: 1920,
    height: 1080,
    gradient: ["#000000", "#111111"],
    icon: "🔢",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: "3",
          startOffset: 0,
          duration: 1.5,
          x: 50,
          y: 50,
          fontSize: 120,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: "2",
          startOffset: 1.5,
          duration: 1.5,
          x: 50,
          y: 50,
          fontSize: 120,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: "1",
          startOffset: 3,
          duration: 1.5,
          x: 50,
          y: 50,
          fontSize: 120,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.title || "GO!",
          startOffset: 4.5,
          duration: 0.5,
          x: 50,
          y: 50,
          fontSize: 140,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ef4444",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
];

/* ─── Outro Templates ─── */

const outroTemplates: VideoTemplate[] = [
  {
    id: "outro_thanks",
    name: "Thanks for Watching",
    category: "outro",
    description: "Classic end screen with subscribe and like prompts",
    duration: 8,
    width: 1920,
    height: 1080,
    gradient: ["#1a1a2e", "#0f3460"],
    icon: "🙏",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "Thanks for Watching!",
          startOffset: 0.5,
          duration: 7,
          x: 50,
          y: 35,
          fontSize: 56,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "LIKE  •  SUBSCRIBE  •  SHARE",
          startOffset: 2,
          duration: 5.5,
          x: 50,
          y: 55,
          fontSize: 22,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#a0a0a0",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "outro_next_video",
    name: "Next Video Preview",
    category: "outro",
    description: "End screen with 'Next Video' placeholder and subscribe button",
    duration: 10,
    width: 1920,
    height: 1080,
    gradient: ["#0d1117", "#161b22"],
    icon: "▶️",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "NEXT VIDEO",
          startOffset: 1,
          duration: 8,
          x: 30,
          y: 40,
          fontSize: 36,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "#1e293b",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "SUBSCRIBE",
          startOffset: 1,
          duration: 8,
          x: 70,
          y: 40,
          fontSize: 24,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "#ef4444",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "outro_credits",
    name: "Credits Roll",
    category: "outro",
    description: "Scrolling credits style outro with roles and names",
    duration: 12,
    width: 1920,
    height: 1080,
    gradient: ["#000000", "#0a0a0a"],
    icon: "🎬",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "DIRECTED BY\nYour Name",
          startOffset: 1,
          duration: 10,
          x: 50,
          y: 30,
          fontSize: 28,
          fontFamily: "Georgia, serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "Produced by\nStudio Name",
          startOffset: 3,
          duration: 8,
          x: 50,
          y: 60,
          fontSize: 22,
          fontFamily: "Georgia, serif",
          color: "#888888",
          backgroundColor: "transparent",
          bold: false,
          italic: true,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
];

/* ─── Lower Third Templates ─── */

const lowerThirdTemplates: VideoTemplate[] = [
  {
    id: "lower_third_modern",
    name: "Modern Lower Third",
    category: "lower-third",
    description: "Clean name + title bar at bottom of screen",
    duration: 5,
    width: 1920,
    height: 1080,
    gradient: ["#1e293b", "#334155"],
    icon: "🏷️",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "John Doe",
          startOffset: 0.5,
          duration: 4,
          x: 15,
          y: 82,
          fontSize: 32,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "left",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "Senior Developer",
          startOffset: 0.8,
          duration: 3.7,
          x: 15,
          y: 88,
          fontSize: 18,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#60a5fa",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "left",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "lower_third_news",
    name: "News Style",
    category: "lower-third",
    description: "Breaking news style lower third with ticker",
    duration: 6,
    width: 1920,
    height: 1080,
    gradient: ["#b91c1c", "#7f1d1d"],
    icon: "📺",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "BREAKING NEWS",
          startOffset: 0.3,
          duration: 5.4,
          x: 10,
          y: 80,
          fontSize: 36,
          fontFamily: "Impact, sans-serif",
          color: "#ffffff",
          backgroundColor: "#dc2626",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "left",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "Major development announced today",
          startOffset: 0.6,
          duration: 5.1,
          x: 10,
          y: 88,
          fontSize: 20,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "#1e293b",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "left",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "lower_third_minimal",
    name: "Minimal Bar",
    category: "lower-third",
    description: "Simple thin bar with name at bottom",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#ffffff", "#f0f0f0"],
    icon: "━",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "Speaker Name",
          startOffset: 0.5,
          duration: 3,
          x: 8,
          y: 88,
          fontSize: 20,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#1a1a1a",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "left",
        },
      ],
      transitions: [],
    }),
  },
];

/* ─── Title Card Templates ─── */

const titleCardTemplates: VideoTemplate[] = [
  {
    id: "title_split",
    name: "Split Title",
    category: "title-card",
    description: "Two-tone split background with centered title",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#6366f1", "#ec4899"],
    icon: "🎫",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "THE TITLE",
          startOffset: 0.3,
          duration: 3.7,
          x: 50,
          y: 45,
          fontSize: 72,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "2024 EDITION",
          startOffset: 1,
          duration: 3,
          x: 50,
          y: 60,
          fontSize: 18,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#e0e0e0",
          backgroundColor: "transparent",
          bold: false,
          italic: true,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "title_bold",
    name: "Bold Statement",
    category: "title-card",
    description: "Large bold text with minimal background",
    duration: 3,
    width: 1920,
    height: 1080,
    gradient: ["#000000", "#1a1a1a"],
    icon: "💪",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "BOLD\nSTATEMENT",
          startOffset: 0.2,
          duration: 2.8,
          x: 50,
          y: 50,
          fontSize: 96,
          fontFamily: "Impact, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "title_question",
    name: "Question Card",
    category: "title-card",
    description: "Big question mark with title text",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#1e1b4b", "#312e81"],
    icon: "❓",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "Did you know?",
          startOffset: 0.5,
          duration: 3,
          x: 50,
          y: 45,
          fontSize: 52,
          fontFamily: "Georgia, serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: false,
          italic: true,
          shadow: true,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
];

/* ─── Caption Templates ─── */

const captionTemplates: VideoTemplate[] = [
  {
    id: "caption_subtitle",
    name: "Subtitle Style",
    category: "caption",
    description: "Standard subtitle formatting with dark background",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#1e293b", "#0f172a"],
    icon: "📝",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "This is a subtitle caption with dark background",
          startOffset: 0.5,
          duration: 3,
          x: 50,
          y: 88,
          fontSize: 24,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "rgba(0,0,0,0.7)",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "caption_karaoke",
    name: "Karaoke Style",
    category: "caption",
    description: "Large centered text with color highlight",
    duration: 4,
    width: 1920,
    height: 1080,
    gradient: ["#000000", "#0a0a0a"],
    icon: "🎤",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "SING ALONG WITH ME",
          startOffset: 0.5,
          duration: 3,
          x: 50,
          y: 50,
          fontSize: 56,
          fontFamily: "Impact, sans-serif",
          color: "#facc15",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "caption_callout",
    name: "Callout Caption",
    category: "caption",
    description: "Arrow-pointer style callout pointing to area",
    duration: 5,
    width: 1920,
    height: 1080,
    gradient: ["#1e293b", "#334155"],
    icon: "📌",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "← Click here",
          startOffset: 1,
          duration: 3.5,
          x: 65,
          y: 30,
          fontSize: 28,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "#ef4444",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "left",
        },
      ],
      transitions: [],
    }),
  },
];

/* ─── Social Media Templates ─── */

const socialTemplates: VideoTemplate[] = [
  {
    id: "social_ig_story",
    name: "Instagram Story",
    category: "social",
    description: "9:16 vertical format with trendy styling",
    duration: 6,
    width: 1080,
    height: 1920,
    gradient: ["#f09433", "#dc2743"],
    icon: "📱",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "Swipe Up!",
          startOffset: 0.5,
          duration: 5,
          x: 50,
          y: 45,
          fontSize: 64,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "social_tiktok",
    name: "TikTok Style",
    category: "social",
    description: "9:16 format with bold text and hashtags",
    duration: 8,
    width: 1080,
    height: 1920,
    gradient: ["#010101", "#1a1a1a"],
    icon: "🎵",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "WAIT FOR IT 😱",
          startOffset: 0.5,
          duration: 7,
          x: 50,
          y: 40,
          fontSize: 52,
          fontFamily: "Impact, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "#viral #fyp #trending",
          startOffset: 1,
          duration: 6,
          x: 50,
          y: 55,
          fontSize: 20,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ef4444",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "social_twitter",
    name: "Twitter/X Post",
    category: "social",
    description: "16:9 format optimized for Twitter/X video posts",
    duration: 5,
    width: 1280,
    height: 720,
    gradient: ["#0f1419", "#1a2734"],
    icon: "🐦",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "Thread 🧵",
          startOffset: 0.5,
          duration: 4,
          x: 50,
          y: 50,
          fontSize: 48,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#1d9bf0",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
  {
    id: "social_youtube",
    name: "YouTube Thumbnail",
    category: "social",
    description: "16:9 thumbnail-style with bold text and emoji",
    duration: 4,
    width: 1280,
    height: 720,
    gradient: ["#ff0000", "#cc0000"],
    icon: "📺",
    generate: (opts) => ({
      tracks: [],
      textOverlays: [
        {
          id: generateId("txt"),
          text: opts?.title || "THIS CHANGED EVERYTHING",
          startOffset: 0.3,
          duration: 3.7,
          x: 50,
          y: 45,
          fontSize: 56,
          fontFamily: "Impact, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: true,
          italic: false,
          shadow: true,
          alignment: "center",
        },
        {
          id: generateId("txt"),
          text: opts?.subtitle || "😱😱😱",
          startOffset: 0.5,
          duration: 3.5,
          x: 80,
          y: 20,
          fontSize: 48,
          fontFamily: "Helvetica, Arial, sans-serif",
          color: "#ffffff",
          backgroundColor: "transparent",
          bold: false,
          italic: false,
          shadow: false,
          alignment: "center",
        },
      ],
      transitions: [],
    }),
  },
];

/* ─── All Templates ─── */

export const ALL_TEMPLATES: VideoTemplate[] = [
  ...introTemplates,
  ...outroTemplates,
  ...lowerThirdTemplates,
  ...titleCardTemplates,
  ...captionTemplates,
  ...socialTemplates,
];

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string; icon: string }[] = [
  { id: "intro", label: "Intros", icon: "🎬" },
  { id: "outro", label: "Outros", icon: "🙏" },
  { id: "lower-third", label: "Lower Thirds", icon: "🏷️" },
  { id: "title-card", label: "Title Cards", icon: "🎫" },
  { id: "caption", label: "Captions", icon: "📝" },
  { id: "social", label: "Social Media", icon: "📱" },
];

/** Get templates by category */
export function getTemplatesByCategory(category: TemplateCategory): VideoTemplate[] {
  return ALL_TEMPLATES.filter((t) => t.category === category);
}
